/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Encryptor */

#ifndef _Included_Encryptor
#define _Included_Encryptor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
