-- GENERATED BY QueryOne AT 2021-03-04 14:18:00
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.SVRCD_SEL           
(ACPTNO IN VARCHAR2,SVRCD IN VARCHAR2,PRCSYS IN VARCHAR2)          
                                                                                       
                                                                                       
RETURN INTEGER                                                                          
IS                                                                                     
    CNTVAL INTEGER := 0;     
    CNCLSTEP VARCHAR2(10);   
    VCNT   INTEGER := 0;   
        
-- 리턴값 0:처리 1:미처리                                                              
BEGIN   
    CNTVAL := 1;   
    IF SVRCD <> '23' AND SVRCD <> '25' AND SVRCD <> '13' AND SVRCD <> '15' AND SVRCD <> '03' AND SVRCD <> '05' THEN   
       RETURN 1;   
    END IF;   
   -- dbms_OUTPUT.PUT_LINE('17 Line VCNT=' || VCNT || ' SVRCD=' || SVRCD || ' PRCSYS=' || PRCSYS);   
    IF (PRCSYS = 'SYSDCB' OR PRCSYS = 'SYSDGB') AND SVRCD = '23' THEN   
       CNTVAL := 0;   
    ELSIF PRCSYS = 'SYSDED' AND SVRCD = '25' THEN   
       CNTVAL := 0;   
    ELSIF (PRCSYS = 'SYSTCB' OR PRCSYS = 'SYSTGB') AND SVRCD = '13' THEN   
       CNTVAL := 0;   
    ELSIF PRCSYS = 'SYSTED' AND SVRCD = '15' THEN   
       CNTVAL := 0;   
    ELSIF (PRCSYS = 'SYSCB' OR PRCSYS = 'SYSGB') AND SVRCD = '03' THEN   
       CNTVAL := 0;   
    ELSIF PRCSYS = 'SYSED' AND SVRCD = '05' THEN   
       CNTVAL := 0;   
    ELSIF PRCSYS = 'SYSCCB' OR PRCSYS = 'SYSCED' OR PRCSYS = 'SYSCGB' THEN   
       CNCLSTEP := NULL;   
       --dbms_OUTPUT.PUT_LINE('32 Line VCNT=' || VCNT || ' SVRCD=' || SVRCD || ' PRCSYS=' || PRCSYS);    
       BEGIN  
           SELECT CR_CNCLSTEP    
             INTO CNCLSTEP   
             FROM CMR1000   
            WHERE CR_ACPTNO=ACPTNO   
              AND CR_CNCLSTEP IS NOT NULL   
              AND NVL(CR_CNCLSTEP,'****') LIKE 'SYS%';   
           EXCEPTION                                          
             WHEN  NO_DATA_FOUND  Then                                          
                  CNCLSTEP := PRCSYS;     
        END;         
     -- dbms_OUTPUT.PUT_LINE('39 Line VCNT=' || VCNT || ' SVRCD=' || SVRCD || ' PRCSYS=' || PRCSYS);      
        SELECT COUNT(*)   
          INTO VCNT   
          FROM CMR9900 A       
         WHERE A.CR_ACPTNO=ACPTNO       
           AND A.CR_LOCAT<>'00'       
           AND A.CR_TEAMCD='1'       
           AND A.CR_TEAM=DECODE(SVRCD,'23','SYSDCB','25','SYSDED','13','SYSTCB','15','SYSTED','03','SYSCB','SYSED')   
           AND A.CR_STATUS<>'0'    
           AND A.CR_CONFDATE IS NOT NULL;         
       -- dbms_OUTPUT.PUT_LINE('48 Line VCNT=' || VCNT || ' SVRCD=' || SVRCD || ' PRCSYS=' || PRCSYS);   
        IF VCNT > 0 THEN   
           CNTVAL := 0;   
        ELSE   
           IF CNCLSTEP IS NOT NULL THEN   
              IF (CNCLSTEP = 'SYSDCB' OR CNCLSTEP = 'SYSDGB') AND SVRCD = '23' THEN   
                 CNTVAL := 0;   
              ELSIF CNCLSTEP = 'SYSDED' AND SVRCD = '25' THEN   
                 CNTVAL := 0;   
              ELSIF (CNCLSTEP = 'SYSTCB' OR CNCLSTEP = 'SYSTGB') AND SVRCD = '13' THEN   
                 CNTVAL := 0;   
              ELSIF CNCLSTEP = 'SYSTED' AND SVRCD = '15' THEN   
                 CNTVAL := 0;   
              ELSIF (CNCLSTEP = 'SYSCB' OR CNCLSTEP = 'SYSGB') AND SVRCD = '03' THEN   
                 CNTVAL := 0;   
              ELSIF CNCLSTEP = 'SYSED' AND SVRCD = '05' THEN   
                 CNTVAL := 0;   
              END IF;   
           END IF;   
        END IF;    
    ELSE   
       CNTVAL := 1;   
    END IF;   
    -- dbms_OUTPUT.PUT_LINE('72 Line VCNT=' || VCNT || ' SVRCD=' || SVRCD || ' PRCSYS=' || PRCSYS);                                                                
   RETURN CNTVAL;                                                                                    
END;