-- GENERATED BY QueryOne AT 2021-03-04 14:18:53
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.RELATNO_UPDT
(
 Call_Key_AcptNo       IN   Varchar2)
 IS
 ErrSw              Varchar2 (01);
 BASENO             Varchar2 (12);
 CONFNO             Varchar2 (12);
 CMRSTA             VARCHAR2 (1);
 CNT                INTEGER;
CURSOR  REQLIST  IS
     Select A.CR_QRYCD REQUEST,B.CR_BASEITEM CR_ITEMID,B.CR_QRYCD,
            NVL(B.CR_CONFNO,A.CR_ACPTNO) CR_CONFNO,
            NVL(B.CR_BASENO,A.CR_ACPTNO) CR_BASENO,
            NVL(B.CR_TSTCHG,'0') CR_TSTCHG
       From CMR1010 B,CMR1000 A
      Where A.CR_ACPTNO=Call_Key_AcptNo
        And A.CR_ACPTNO=B.CR_ACPTNO
        And B.CR_STATUS<>'3'
        AND B.CR_ITEMID=B.CR_BASEITEM;

Begin
    ErrSw          := NULL;


    IF SUBSTR(Call_Key_AcptNo,5,2) = '04' THEN
       CMRSTA := '7';
    ELSIF SUBSTR(Call_Key_AcptNo,5,2) = '07' THEN
       CMRSTA := 'A';
    ELSIF SUBSTR(Call_Key_AcptNo,5,2) = '11' THEN
       CMRSTA := '6';
    ELSE
       CMRSTA := '4';
    END IF;
    UPDATE CMR0020
       SET CR_SAVESTA=CR_STATUS,
           CR_STATUS=CMRSTA,
           CR_EDITOR=(SELECT CR_EDITOR FROM CMR1000
                       WHERE CR_ACPTNO=Call_Key_AcptNo)
     WHERE CR_ITEMID IN (SELECT CR_ITEMID FROM CMR1010
                          WHERE CR_ACPTNO=Call_Key_AcptNo
                            AND CR_ITEMID=CR_BASEITEM
                            AND CR_PRCDATE IS NULL);

   IF SUBSTR(Call_Key_AcptNo,5,2) = '11' THEN
      UPDATE CMR1010
         SET CR_CONFNO=Call_Key_AcptNo
       WHERE CR_ITEMID IN (SELECT CR_ITEMID FROM CMR1010
                          WHERE CR_ACPTNO=Call_Key_AcptNo
                            AND CR_ITEMID=CR_BASEITEM
                            AND CR_PRCDATE IS NULL)
          AND SUBSTR(CR_ACPTNO,5,2) IN ('01','02','03','07')
          AND CR_CONFNO IS NULL;
   END IF;

End RELATNO_UPDT;