-- GENERATED BY QueryOne AT 2021-03-04 14:21:18
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

DROP TABLE ECAMS.CMR9900 CASCADE CONSTRAINTS PURGE;

CREATE TABLE ECAMS.CMR9900
(
    CR_ACPTNO CHAR(12) NOT NULL,
    CR_SEQNO NUMBER NOT NULL,
    CR_LOCAT CHAR(2) NOT NULL,
    CR_CONFNAME VARCHAR2(50) NULL,
    CR_TEAM VARCHAR2(50) NULL,
    CR_TEAMCD CHAR(1) NULL,
    CR_STATUS CHAR(1) NULL,
    CR_CONGBN CHAR(1) NULL,
    CR_COMMON CHAR(1) NULL,
    CR_BLANK CHAR(1) NULL,
    CR_EMGER CHAR(1) NULL,
    CR_HOLI CHAR(1) NULL,
    CR_SGNGBN VARCHAR2(100) NULL,
    CR_BLANKCD VARCHAR2(2) NULL,
    CR_ORGSTEP VARCHAR2(1) NULL,
    CR_BASEUSR VARCHAR2(10) NULL,
    CR_CONFDATE DATE NULL,
    CR_CONFUSR VARCHAR2(10) NULL,
    CR_CONMSG VARCHAR2(500) NULL,
    CR_EMGAFT CHAR(1) NULL,
    CR_PRCSW CHAR(1) DEFAULT 'N' NULL,
    CR_QRYCD VARCHAR2(2) NULL,
    CR_STDATE DATE NULL
)
SEGMENT CREATION IMMEDIATE
STORAGE
(
    INITIAL 512K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01;

CREATE INDEX ECAMS.CMR9900_IDX1
ON ECAMS.CMR9900
(
    CR_LOCAT ASC
)
INITRANS 2
STORAGE
(
    INITIAL 22M
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR9900_IDX2
ON ECAMS.CMR9900
(
    CR_TEAM ASC
)
INITRANS 2
STORAGE
(
    INITIAL 22M
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR9900_IDX3
ON ECAMS.CMR9900
(
    CR_TEAMCD ASC
)
INITRANS 2
STORAGE
(
    INITIAL 16M
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR9900_IDX4
ON ECAMS.CMR9900
(
    CR_STATUS ASC
)
INITRANS 2
STORAGE
(
    INITIAL 22M
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR9900_IDX5
ON ECAMS.CMR9900
(
    CR_ACPTNO ASC
)
INITRANS 2
STORAGE
(
    INITIAL 35M
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE UNIQUE INDEX ECAMS.CMR9900_PK
ON ECAMS.CMR9900
(
    CR_ACPTNO ASC,
    CR_SEQNO ASC,
    CR_LOCAT ASC
)
INITRANS 2
STORAGE
(
    INITIAL 43M
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

ALTER TABLE ECAMS.CMR9900
ADD CONSTRAINT CMR9900_PK PRIMARY KEY(CR_ACPTNO,CR_SEQNO,CR_LOCAT)
     USING INDEX ECAMS.CMR9900_PK;

CREATE OR REPLACE TRIGGER "ECAMS".CMR9900_Trg 
   
    BEFORE INSERT or UPDATE or DELETE ON ECAMS.CMR9900              
                  
FOR EACH ROW
Declare              
   V_Editor      CMR1000.cr_editor%Type;              
   V_PassCd      CMR1000.cr_PassCd%Type;              
   V_UserName    CMM0040.CM_USERNAME%Type;              
   V_ConfUsr     CMR9900.CR_CONFUSR%Type;              
   V_AcptDate    Varchar2(10);   
   V_LinkUrl     Varchar2(200);   
   V_CNT         INTEGER;   
   V_SRID        CMR1000.CR_ITSMID%TYPE; 
   V_MSGACPT     VARCHAR2(50); 
   V_OWNER       VARCHAR2(50); 
                 
 Begin
 
         
            
   IF :NEW.cr_status = '0' AND :NEW.cr_team is not null AND               
      :NEW.cr_teamcd <> '1' AND :NEW.cr_locat = '00' AND :NEW.cr_confusr <> '9999' THEN 
      BEGIN              
        SELECT a.cr_editor,b.cm_codename,to_char(a.cr_acptdate,'yyyy/mm/dd'),A.CR_ITSMID,C.CM_URL,D.CM_USERNAME   
          INTO V_Editor,V_PassCd,V_AcptDate,V_SRID,V_LinkUrl,V_UserName   
          FROM cmr1000 a,cmm0020 b,CMM0010 C,CMM0040 D              
         WHERE a.cr_acptno=:NEW.cr_acptno         
           and b.cm_macode='REQUEST'         
           and b.cm_micode=a.cr_qrycd 
           AND C.CM_STNO='ECAMS' 
           AND A.CR_EDITOR=D.CM_USERID;              
         EXCEPTION              
              WHEN NO_DATA_FOUND THEN              
                   V_Editor := '';              
      END;   
       
      IF (:NEW.cr_teamcd = '3' OR :NEW.cr_teamcd = 'P') AND V_Editor = :NEW.cr_team THEN   
         V_Editor := '';   
      END IF;    
         
      IF V_Editor is not null THEN     
         V_MSGACPT := '신청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7,6); 
          
         V_LinkUrl := V_LinkUrl || 'ecams_win_flex/';   
         IF substr(:NEW.cr_acptno,5,2) = '01' or substr(:NEW.cr_acptno,5,2) = '02' or    
            substr(:NEW.cr_acptno,5,2) = '11' or substr(:NEW.cr_acptno,5,2) = '12' THEN    
            V_LinkUrl := V_LinkUrl || 'eCmr0150.jsp?ReqNo=' || :NEW.CR_ACPTNO;    
         ELSIF substr(:NEW.cr_acptno,5,2) = '03' or substr(:NEW.cr_acptno,5,2) = '04' or substr(:NEW.cr_acptno,5,2) = '07'    
            or substr(:NEW.cr_acptno,5,2) = '06' or substr(:NEW.cr_acptno,5,2) = '16' THEN    
            V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;  
         ELSIF substr(:NEW.cr_acptno,5,2) = '41' OR substr(:NEW.cr_acptno,5,2) = '69' THEN    
            V_LinkUrl := V_LinkUrl || 'eCmc0900.jsp?ReqNo=' || :NEW.CR_ACPTNO || '&IsrId=' || V_SRID;  
         ELSE /*substr(:NEW.cr_acptno,5,2) = '87' THEN */    
            V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;     
         END IF;     
                       
         IF :NEW.cr_teamcd = '4' OR :NEW.cr_teamcd = '5' OR :NEW.cr_teamcd = '9' THEN         
            INSERT INTO CMR9910              
               (cr_conusr, cr_senddate, cr_status, cr_acptno, cr_sendusr,cr_sgnmsg,cr_title,cr_linkurl,CR_NOTIGBN,CR_NOTICD,CR_SMSMSG)              
               (SELECT distinct A.CM_USERID,SYSDATE,'0',:NEW.cr_acptno, V_Editor,              
                       '1. 요청일 : ' || V_AcptDate || chr(13) ||              
                       '2. ' || V_MSGACPT || Chr(13) ||              
                       '3. 요청내용 : ' || V_PassCd || Chr(13) || '      에 대한 결재요청이 있습니다.' || Chr(13) ||               
                       '      형상관리시스템(eCAMS)에 접속하여 확인하여 주시기 바랍니다.'           
                       ,'형상관리 ' || C.CM_CODENAME || ' 결재요청'            
                       ,replace(V_LinkUrl,'UserId=?','UserId=' || A.CM_USERID)   
                       ,'CO','SMS'                        
                       ,'[형상관리 ' || C.CM_CODENAME || ' 결재요청]' || chr(10) ||
                        '요청일시:' || V_AcptDate || chr(10) ||   
                        '요청자:' || V_UserName
                  FROM CMM0040 A,CMM0043 B,CMM0020 C              
                 WHERE INSTR(:NEW.CR_TEAM,B.CM_RGTCD)>0              
                   AND B.CM_USERID=A.CM_USERID              
                   AND A.CM_ACTIVE='1' 
                   AND C.CM_MACODE='REQUEST' 
                   AND C.CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));            
         ELSE              
            INSERT INTO CMR9910              
               (cr_conusr, cr_senddate, cr_status, cr_acptno, cr_sendusr,cr_sgnmsg,cr_title,cr_linkurl,CR_NOTIGBN,CR_NOTICD,CR_SMSMSG)              
               (SELECT :NEW.cr_team, SYSDATE, '0', :NEW.cr_acptno, V_Editor,              
                        '1. 요청일 : ' || V_AcptDate || chr(13) ||              
                        '2. ' || V_MSGACPT || Chr(13) ||              
                        '3. 요청내용 : ' || V_PassCd || Chr(13) || '      에 대한 결재요청이 있습니다.' || Chr(13) ||               
                        '       형상관리시스템(eCAMS)에 접속하여 확인하여 주시기 바랍니다.'          
                        ,'형상관리 ' ||CM_CODENAME || ' 결재요청'             
                        ,replace(V_LinkUrl,'UserId=?','UserId=' || :NEW.cr_team) 
                        ,'CO','SMS'                        
                        ,'[형상관리 ' || CM_CODENAME || ' 결재요청]' || chr(10) ||
                        '요청일시:' || V_AcptDate || chr(10) ||   
                        '요청자:' || V_UserName
                  FROM CMM0020 
                 WHERE CM_MACODE='REQUEST' 
                   AND CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2)); 
         END IF;              
      END IF;              
   End If;              
                 
   IF :NEW.cr_status = '0' AND :NEW.cr_teamcd = '1' AND :NEW.cr_locat = '00' AND SUBSTR(:NEW.CR_ACPTNO,5,2) < '30' AND               
      (:OLD.CR_CONFUSR<>:NEW.CR_CONFUSR or :OLD.cr_team<>:NEW.cr_team)  THEN              
      UPDATE CMR1010              
         SET CR_SYSSTEP=0,              
             CR_PUTCODE='',              
             CR_PID=NULL,              
             CR_SRCCMP='Y'              
       WHERE CR_ACPTNO=:NEW.CR_ACPTNO;   
                
   END IF;              
 
   IF :NEW.cr_locat<>'00' AND :NEW.cr_status <> '0' AND :OLD.cr_status = '0' THEN              
      UPDATE CMR1000              
         SET CR_LASTDATE=SYSDATE,  
             CR_SYSSTEP=0  
       WHERE CR_ACPTNO=:NEW.CR_ACPTNO;              
   END IF;  
    
                 
End CMR9900_Trg;
/

COMMENT ON TABLE ECAMS.CMR9900 IS '신청건별 결재 정보';

COMMENT ON COLUMN ECAMS.CMR9900.CR_ACPTNO IS '신청번호';

COMMENT ON COLUMN ECAMS.CMR9900.CR_SEQNO IS '일련번호';

COMMENT ON COLUMN ECAMS.CMR9900.CR_LOCAT IS '단계';

COMMENT ON COLUMN ECAMS.CMR9900.CR_CONFNAME IS '단계명칭';

COMMENT ON COLUMN ECAMS.CMR9900.CR_TEAM IS '결재가능사번';

COMMENT ON COLUMN ECAMS.CMR9900.CR_TEAMCD IS '소속팀';

COMMENT ON COLUMN ECAMS.CMR9900.CR_STATUS IS '상태';

COMMENT ON COLUMN ECAMS.CMR9900.CR_CONGBN IS '결재처리구분';

COMMENT ON COLUMN ECAMS.CMR9900.CR_COMMON IS '정상인 경우 처리';

COMMENT ON COLUMN ECAMS.CMR9900.CR_BLANK IS '부재중인 경우 처리';

COMMENT ON COLUMN ECAMS.CMR9900.CR_EMGER IS '긴급인 경우 처리';

COMMENT ON COLUMN ECAMS.CMR9900.CR_HOLI IS '휴일인 경우 처리';

COMMENT ON COLUMN ECAMS.CMR9900.CR_SGNGBN IS '결재가능팀 또는 업무';

COMMENT ON COLUMN ECAMS.CMR9900.CR_BLANKCD IS '부재사유';

COMMENT ON COLUMN ECAMS.CMR9900.CR_ORGSTEP IS '조직단계';

COMMENT ON COLUMN ECAMS.CMR9900.CR_BASEUSR IS '원결재자사번';

COMMENT ON COLUMN ECAMS.CMR9900.CR_CONFDATE IS '결재일시';

COMMENT ON COLUMN ECAMS.CMR9900.CR_CONFUSR IS '결재자사번';

COMMENT ON COLUMN ECAMS.CMR9900.CR_CONMSG IS '결재의견';

COMMENT ON COLUMN ECAMS.CMR9900.CR_EMGAFT IS '정상결재시 처리구분(SGNCD)';

COMMENT ON COLUMN ECAMS.CMR9900.CR_PRCSW IS '완료처리단계여부';

COMMENT ON COLUMN ECAMS.CMR9900.CR_QRYCD IS '결재사유';

COMMENT ON COLUMN ECAMS.CMR9900.CR_STDATE IS '처리시작시간';