-- GENERATED BY QueryOne AT 2021-03-04 14:18:03
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.TESTSVR_YN
(SYSCD IN VARCHAR2,REQCD IN VARCHAR2)
RETURN VARCHAR2
IS
   VCNT INT := 0;
 --- 개발/테스트서버 유무
BEGIN
   IF REQCD = '03' THEN
        select count(*) cnt
          into VCNT
          from CMM0031
         where CM_SYSCD=SYSCD
           AND CM_SVRCD IN ('13','15')
           AND CM_CLOSEDT IS NULL;
         IF VCNT = 0 THEN
            RETURN 'NO';
         ELSE RETURN 'OK';
         END IF;
   ELSIF REQCD = '08' THEN
        select count(*) cnt
          into VCNT
          from CMM0031
         where CM_SYSCD=SYSCD
           AND CM_SVRCD IN ('23','25')
           AND CM_CLOSEDT IS NULL;
         IF VCNT = 0 THEN
            RETURN 'NO';
         ELSE RETURN 'OK';
         END IF;
   ELSE
      RETURN 'OK';
   END IF;

end;