-- GENERATED BY QueryOne AT 2021-03-04 14:18:03
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.TESTREQYN
(ACPTNO IN VARCHAR2)
RETURN VARCHAR2
IS
   VCNT INT := 0;
 --- 테스트서버 유무
BEGIN
        select count(*) cnt
          into VCNT
          from CMR1010
         where CR_ACPTNO=ACPTNO
           AND SUBSTR(CR_CONFNO,5,2)='03';
         IF VCNT = 0 THEN
            RETURN 'NO';
         ELSE RETURN 'OK';
         END IF;

end;