-- GENERATED BY QueryOne AT 2021-03-04 14:18:49
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.CLOSEPGM_OPEN
(
 SYSCD     IN   Varchar2,
 RSRCNAME  IN   VARCHAR2)
 IS
  SVITEMID   VARCHAR2(12);
  VCNT     INTEGER;

BEGIN
    VCNT := 0;
    SELECT COUNT(*)
      INTO VCNT
      FROM CMR0020
     WHERE CR_SYSCD=SYSCD
                       AND CR_RSRCNAME=RSRCNAME
                       AND CR_STATUS='9';

    IF VCNT > 1  AND SYSCD <> '01000' AND SYSCD <>'02000' AND UPPER(SUBSTR(RSRCNAME,-2)) <> '.C' THEN
        Raise_Application_Error (-20011,'프로그램명이 UNIQUE하지 않습니다.');
    ELSIF VCNT = 0 THEN
        Raise_Application_Error (-20012,'프로그램명이 존재하지 않습니다.');
    END IF;

    IF (SYSCD = '01000' OR SYSCD = '02000') AND UPPER(SUBSTR(RSRCNAME,-2)) = '.C' THEN
        UPDATE CMR0020
           SET CR_STATUS='0',
               CR_CLSDATE='',
               CR_TESTSTA='0',
               CR_REALSTA='0',
               CR_DEVSTA='0'
         WHERE CR_ITEMID IN (Select CR_ITEMID
                           From CMR0020
                          Where CR_SYSCD=SYSCD
                           AND SUBSTR(CR_RSRCNAME,1,LENGTH(RSRCNAME)-1)=SUBSTR(RSRCNAME,1,LENGTH(RSRCNAME)-1)
                           AND CR_STATUS='9');
    ELSE
        UPDATE CMR0020
           SET CR_STATUS='0',
               CR_CLSDATE='',
               CR_TESTSTA='0',
               CR_REALSTA='0',
               CR_DEVSTA='0'
         WHERE CR_ITEMID=(Select CR_ITEMID
                           From CMR0020
                          Where CR_SYSCD=SYSCD
                           AND CR_RSRCNAME=RSRCNAME
                           AND CR_STATUS='9');
    END IF;
End CLOSEPGM_OPEN;