-- GENERATED BY QueryOne AT 2021-03-04 14:18:53
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.SYSHOME2_STR        
(DIRCD IN VARCHAR2,                    
 SYSCD IN VARCHAR2,                     
 SVRIP IN VARCHAR2)                    
 IS                    
 ErrSw              Varchar2 (01);                    
 chgDirPath         CMM0070.CM_DIRPATH%TYPE;                 
 SvDirpath          CMM0070.CM_DIRPATH%TYPE;                 
 SvDirpath2         CMM0070.CM_DIRPATH%TYPE;                 
 SvHomeDir          CMM0070.CM_DIRPATH%TYPE;                 
 SvSvrIp            CMM0031.CM_SVRIP%TYPE;                 
 SvSysCd            CMM0030.CM_SYSCD%TYPE;                 
 SvDsnCd            CMM0070.CM_DSNCD%TYPE;                 
 SvSvrCd            CMM0031.CM_SVRCD%TYPE;                 
 WKSVRIP            CMM0031.CM_SVRIP%TYPE;                 
 FINDSW             BOOLEAN;                   
 VCNT               INTEGER;                
                     
CURSOR  Conf1 IS                    
    SELECT /*+NO_EXPAND LEADING(C E)*/        
           e.cm_svrip,e.cm_portno,e.cm_syscd,e.cm_svrcd,e.cm_seqno,f.cm_rsrccd,A.CM_DIRPATH,a.cm_dsncd, e.cm_sysos               
      FROM cmm0031 e,cmm0038 f,               
          (SELECT /*+NO_MERGE NO_EXPAND NO_USE_HASH_AGGREGATION LEADING(Y Z X) USE_HASH(Z X) SWAP_JOIN_INPUTS(X) SWAP_JOIN_INPUTS(Z)*/               
                   y.cr_syscd,y.cr_rsrccd,x.cm_dirpath,x.cm_dsncd                    
              from CMM0026 Z,cmr0020 y,CMM0070 x                   
             where Z.CM_SYSCD=DECODE(SYSCD,'ALL',Z.CM_SYSCD,SYSCD)               
               AND Z.CM_SYSCD IN (SELECT DISTINCT CM_SYSCD FROM CMM0031               
                                   WHERE CM_CLOSEDT IS NULL               
                                     AND CM_SYSCD=DECODE(SYSCD,'ALL',CM_SYSCD,SYSCD)               
                                     AND CM_SVRCD ='05'    
                                     AND CM_SVRIP=DECODE(WKSVRIP,'ALL',CM_SVRIP,WKSVRIP))                     
               AND Z.CM_RUNCD='01'                    
               AND Z.CM_EXISTYN='N'                       
               AND Y.CR_SYSCD=Z.CM_SYSCD                
               AND y.cr_lstver>0                    
               and y.cr_status<>'9'                    
               and y.cr_syscd=x.cm_syscd                    
               and y.cr_dsncd=x.cm_dsncd        
             group by y.cr_syscd,y.cr_rsrccd,x.cm_dirpath,x.cm_dsncd) a,                    
           cmm0030 b              
          , cmm0036 J        
     where b.cm_closedt is null                    
       AND B.CM_SYSCD=DECODE(SYSCD,'ALL',B.CM_SYSCD,SYSCD)                    
       AND b.cm_syscd=e.cm_syscd                    
       and e.cm_closedt is null                    
       AND E.CM_SVRIP=DECODE(WKSVRIP,'ALL',E.CM_SVRIP,WKSVRIP)                    
       --and e.cm_svrcd IN ('03','05')                
       AND e.cm_svrcd  = '05'       
       AND EXISTS (SELECT /*+NO_UNNEST PUSH_SUBQ*/1                 
                    FROM CMM0027 C                            
                   WHERE E.CM_SYSCD=C.CM_SYSCD                     
                     AND E.CM_SVRIP=C.CM_SVRIP                     
                     AND C.CM_RUNCD='01'                           
                     AND C.CM_EXISTYN='N')                         
       and e.cm_syscd=f.cm_syscd                    
       and e.cm_svrcd=f.cm_svrcd                    
       and e.cm_seqno=f.cm_seqno                    
       and f.cm_syscd=a.cr_syscd                    
       and f.cm_rsrccd=a.cr_rsrccd           
       and a.cr_syscd = J.cm_syscd       
       and a.cr_rsrccd = J.cm_rsrccd       
       and J.cm_closedt is null       
       and substr(J.cm_info, 60, 1) = '0'                
       and (a.cm_dirpath not like '%resources/help%' and a.cm_dirpath not like '%WEB-INF/classes-biz%' and a.cm_dirpath not like '%/eiswebapp/WEB-INF/.warjspwork%')    
     group by e.cm_svrip,e.cm_portno,e.cm_syscd,e.cm_svrcd,e.cm_seqno,A.CM_DIRPATH,f.cm_rsrccd,a.cm_dsncd,  e.cm_sysos                    
     order by e.cm_svrip,E.CM_SYSCD,A.CM_DIRPATH;                    
               
               
Begin                    
    SvDirPath := '';                    
    SvSvrIp := null;                    
    SvDirPath2 := '';                    
    chgDirPath := '';                    
    SvSysCd := null;                 
    SvSvrCd := null;               
           
    DELETE CMM0026                    
     WHERE CM_SYSCD NOT IN (SELECT CM_SYSCD FROM CMM0030                    
                             WHERE CM_CLOSEDT IS NULL);                    
                                             
    INSERT INTO CMM0026                    
      (CM_STNO,CM_RUNCD,CM_SYSCD,CM_LASTDT,CM_EXISTYN,CM_BASEDIRCD,CM_EXECD)                    
      (SELECT 'ECAMS','01',CM_SYSCD,SYSDATE,'N','C','C'                    
         FROM CMM0030                    
        WHERE CM_CLOSEDT IS NULL                    
        MINUS                    
       SELECT 'ECAMS','01',CM_SYSCD,SYSDATE,'N','C','C'                    
         FROM CMM0026                    
        WHERE CM_STNO='ECAMS'                    
          AND CM_RUNCD='01');                    
                        
    DELETE CMM0027;                    
                                                 
    INSERT INTO CMM0027                    
       (CM_STNO,CM_RUNCD,CM_SYSCD,CM_SVRIP,CM_LASTDT,CM_BASEDIRCD,CM_EXECD,CM_EXISTYN)                    
        SELECT DISTINCT       
               'ECAMS','01',A.CM_SYSCD,A.CM_SVRIP,SYSDATE,'C','C','N'                
          FROM CMM0031 A,CMM0026 B                    
         WHERE B.CM_STNO='ECAMS'                    
           AND B.CM_RUNCD='01'                    
           AND B.CM_EXISTYN='N'                    
           AND B.CM_SYSCD=A.CM_SYSCD                    
           AND A.CM_CLOSEDT IS NULL                    
           AND A.CM_SVRCD IN ('03','05');              
                               
    IF SVRIP IS NULL THEN                    
       WKSVRIP := 'ALL';                    
    ELSE                    
       WKSVRIP := SVRIP;                    
    END IF;                  
    IF SYSCD = 'ALL' AND WKSVRIP = 'ALL' THEN                   
        DELETE CMM0074 ;                   
    ELSIF SYSCD <> 'ALL' AND SVRIP <> 'ALL' THEN                  
        DELETE CMM0074                   
         WHERE CM_SYSCD=SYSCD               
           AND CM_SVRIP=SVRIP;                
    ELSE               
       IF SYSCD <> 'ALL' THEN                   
          DELETE CMM0074                   
           WHERE CM_SYSCD=SYSCD;                 
       ELSE                 
          DELETE CMM0074                   
           WHERE CM_SYSCD=SVRIP;                   
       END IF;               
    END IF;                    
               
                        
    For Dir In Conf1  Loop                    
        FINDSW := TRUE;                    
               
        IF SvSysCd IS NULL THEN                    
           FINDSW := FALSE;                    
                               
--           IF SUBSTR(Dir.CM_DIRPATH,1,1) <> '/' AND Dir.CM_SYSOS = '01' THEN                    
--              SvDirpath2 := '/' || Dir.CM_DIRPATH;                    
--           ELSE                    
              SvDirpath2 := Dir.CM_DIRPATH;                    
--           END IF;        
                  
           SvDirpath := CHG_DIRPATH(Dir.CM_SYSCD,Dir.CM_SVRCD,Dir.CM_SEQNO,Dir.CM_SVRIP,Dir.CM_PORTNO,Dir.CM_RSRCCD,SvDirpath2,'');                    
                  
           IF SUBSTR(SvDirpath,1,1) <> '/'  AND Dir.CM_SYSOS = '01' THEN                    
              SvDirpath := '/' || SvDirpath;                    
           END IF;                    
           IF DIRCD <> 'C' THEN                    
               IF INSTR(SvDirpath,'/',INSTR(SvDirpath,'/',1,3)) > 0 THEN                    
                  SvHomeDir := SUBSTR(SvDirpath,1,INSTR(SvDirpath,'/',1,3) -1);                    
               ELSE                    
                  SvHomeDir := SvDirpath;                    
               END IF;                    
           ELSE                    
               SvHomeDir := SvDirpath;                      
           END IF;           
                  
           SvDirpath := SvHomeDir;                    
           SvSvrIp := Dir.CM_SVRIP;                    
           SvSysCd := Dir.CM_SYSCD;               
           SvSvrCd := Dir.CM_SVRCD;               
           chgDirPath := Dir.CM_DIRPATH;       
                  
           SvDsnCd := Dir.CM_DSNCD;                    
           IF DIRCD = 'C' THEN                    
              FINDSW := FALSE;                    
           END IF;                    
        ELSIF DIRCD = 'C' THEN                    
            IF SvSysCd <> Dir.CM_SYSCD OR SvSvrIp <> Dir.CM_SVRIP OR SvSvrCd <> Dir.CM_SVRCD OR chgDirPath <> Dir.CM_DIRPATH THEN                    
               FINDSW := FALSE;                    
            END IF;                               
        ELSIF SvSysCd <> Dir.CM_SYSCD OR SvSvrIp <> Dir.CM_SVRIP THEN                            
           FINDSW := FALSE;                    
        END IF;                    
                              
        IF FINDSW = TRUE AND DIRCD <> 'C' THEN                    
           FINDSW := FALSE;                    
--           IF SUBSTR(Dir.CM_DIRPATH,1,1) <> '/'  AND Dir.CM_SYSOS = '01' THEN                    
--              SvDirpath2 := '/' || Dir.CM_DIRPATH;                    
--           ELSE                    
              SvDirpath2 := Dir.CM_DIRPATH;                    
--           END IF;                    
           SvDirpath2 := CHG_DIRPATH(Dir.CM_SYSCD,Dir.CM_SVRCD,Dir.CM_SEQNO,Dir.CM_SVRIP,Dir.CM_PORTNO,Dir.CM_RSRCCD,SvDirpath2,'');                    
           IF SUBSTR(SvDirpath2,1,1) <> '/'  AND Dir.CM_SYSOS = '01' THEN                    
              SvDirpath2 := '/' || SvDirpath2;                    
           END IF;                    
           IF INSTR(SvDirpath2,'/',INSTR(SvDirpath2,'/',1,3)) > 0 THEN                    
              SvHomeDir := SUBSTR(SvDirpath2,1,INSTR(SvDirpath2,'/',1,3) -1);                    
           ELSE                    
              SvHomeDir := SvDirpath2;                    
           END IF;                    
                               
           IF LENGTH(SvDirpath) < LENGTH(SvHomeDir) THEN                    
              IF SUBSTR(SvHomeDir,1,LENGTH(SvDirpath)) <> SvDirpath THEN                    
                 FINDSW := TRUE;                      
              END IF;                    
           ELSIF LENGTH(SvDirpath) = LENGTH(SvHomeDir) THEN                    
              IF SvDirpath <> SvHomeDir THEN                    
                 FINDSW := TRUE;                    
              END IF;                    
           ELSE                    
              IF SUBSTR(SvDirpath,1,LENGTH(SvHomeDir)) <> SvHomeDir THEN                    
                 FINDSW := TRUE;                      
              ELSE                    
                 SvDirpath := SvHomeDir;                    
              END IF;                               
           END IF;                    
        ELSIF DIRCD = 'C' AND FINDSW = TRUE THEN                    
           FINDSW := FALSE;                    
           --dbms_OUTPUT.PUT_LINE('117 Line' || Dir.CM_SVRIP || ', ' ||  Dir.CM_SYSCD || ', ' || Dir.CM_DIRPATH);                     
        ELSE                    
           IF DIRCD = 'C' THEN                    
--               IF SUBSTR(Dir.CM_DIRPATH,1,1) <> '/'  AND Dir.CM_SYSOS = '01' THEN                    
--                  SvDirpath2 := '/' || Dir.CM_DIRPATH;                    
--               ELSE                    
                  SvDirpath2 := Dir.CM_DIRPATH;                    
--               END IF;                    
               SvDirpath := CHG_DIRPATH(Dir.CM_SYSCD,Dir.CM_SVRCD,Dir.CM_SEQNO,Dir.CM_SVRIP,Dir.CM_PORTNO,Dir.CM_RSRCCD,SvDirpath2,'');                    
               IF SUBSTR(SvDirpath,1,1) <> '/'  AND Dir.CM_SYSOS = '01' THEN                    
                  SvDirpath := '/' || SvDirpath;                    
               END IF;                    
               SvHomeDir := SvDirpath;                    
               SvDirpath := SvHomeDir;                    
               SvSvrIp := Dir.CM_SVRIP;                    
               SvSysCd := Dir.CM_SYSCD;              
               SvSvrCd := Dir.CM_SVRCD;               
                              
               chgDirPath := Dir.CM_DIRPATH;          
                      
               SvDsnCd := Dir.CM_DSNCD;                    
               FINDSW := TRUE;                               
           END IF;                    
           IF SvSysCd <> Dir.CM_SYSCD OR SvSvrIp <> Dir.CM_SVRIP OR DIRCD = 'C' THEN                    
              FINDSW := TRUE;                    
           END IF;                    
        END IF;                    
                            
        IF FINDSW = TRUE THEN                    
           IF DIRCD <> 'C' THEN                     
              SvDsnCd := NULL;                    
           END IF;                 
                        
           IF Dir.CM_SYSOS = '01' THEN       
              SvDirpath := REPLACE(SvDirpath, '\', '/');       
              SvDirpath := REPLACE(SvDirpath, '//', '/');       
           END IF;       
                  
           IF Dir.CM_SYSOS = '03' THEN       
              SvDirpath := REPLACE(SvDirpath, '//', '/');       
              SvDirpath := REPLACE(SvDirpath, '/', '\');       
           END IF;       
                  
           VCNT := 0;               
           SELECT COUNT(*)               
             INTO VCNT               
             FROM CMM0074               
            WHERE CM_SYSCD   = SvSysCd                    
              AND CM_DIRPATH = replace(replace(SvDirpath,'/WebContent',''),'\WebContent','')                   
              AND CM_SVRIP   = SvSvrIp;               
                          
           IF VCNT = 0 THEN                     
              INSERT INTO CMM0074 (CM_SVRIP,CM_SYSCD,CM_DIRPATH,CM_DSNCD,CM_SVRCD)                    
               VALUES               
               (SvSvrIp,SvSysCd,replace(replace(SvDirpath,'/WebContent',''),'\WebContent',''),SvDsnCd, SvSvrCd);               
               COMMIT;               
           END IF;               
                                    
           IF DIRCD <> 'C' THEN                    
--               IF SUBSTR(Dir.CM_DIRPATH,1,1) <> '/'  AND Dir.CM_SYSOS = '01' THEN                    
--                  SvDirpath2 := '/' || Dir.CM_DIRPATH;                    
--               ELSE                    
                  SvDirpath2 := Dir.CM_DIRPATH;                    
--               END IF;                    
               SvDirpath := CHG_DIRPATH(Dir.CM_SYSCD,Dir.CM_SVRCD,Dir.CM_SEQNO,Dir.CM_SVRIP,Dir.CM_PORTNO,Dir.CM_RSRCCD,SvDirpath2,'');                    
               IF SUBSTR(SvDirpath,1,1) <> '/'  AND Dir.CM_SYSOS = '01' THEN                    
                  SvDirpath := '/' || SvDirpath;                    
               END IF;                    
               IF INSTR(SvDirpath,'/',INSTR(SvDirpath,'/',1,3)) > 0 THEN                    
                  SvHomeDir := SUBSTR(SvDirpath,1,INSTR(SvDirpath,'/',1,3) -1);                    
               ELSE                    
                  SvHomeDir := SvDirpath;                    
               END IF;                    
               SvDirpath := SvHomeDir;                    
               SvSvrIp := Dir.CM_SVRIP;                    
               SvSysCd := Dir.CM_SYSCD;                  
               SvSvrCd := Dir.CM_SVRCD;                                
           END IF;                    
        END IF;                    
    End Loop;                    
                 
    IF SvSvrIp IS NOT NULL AND DIRCD <> 'C' THEN                        
       VCNT := 0;               
       SELECT COUNT(*)               
         INTO VCNT               
         FROM CMM0074               
        WHERE CM_SYSCD   = SvSysCd                    
          AND CM_DIRPATH = replace(replace(SvDirpath,'/WebContent',''),'\WebContent','')                    
          AND CM_SVRIP   = SvSvrIp;               
                      
       IF VCNT = 0 THEN          
           INSERT INTO CMM0074 (CM_SVRIP,CM_SYSCD,CM_DIRPATH, CM_SVRCD)                    
                     VALUES (SvSvrIp,SvSysCd,replace(replace(SvDirpath,'/WebContent',''),'\WebContent',''), SvSvrCd);        
       END IF;       
    END IF;                    
                        
    UPDATE CMM0074                
       SET CM_DIFFYN= GET_DIFFYN   (CM_SYSCD, CM_DSNCD);                
         
    DELETE  CMM0074       
     WHERE  CM_DIFFYN = 'Y';       
            
End SYSHOME2_STR;