-- GENERATED BY QueryOne AT 2021-03-04 14:17:52
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.CHECK_NOTICD
(NOTIGB IN VARCHAR2)        
RETURN VARCHAR2        
IS        
   VCNT1 INT := 0;  
   HOLIGB VARCHAR2(2) := 'N';
   VRETMSG VARCHAR2(100);
   NOTICD  VARCHAR2(10);
   
   
 -- 알림에 대한 체크 펑션
 -- 01	결재,02	반려,03	완료,04	오류,05	Agent장애
 
BEGIN   
    IF NOTIGB = '' THEN  
       RETURN 'Y';  
    END IF;  
    

    BEGIN
        SELECT COUNT(*) AS CNT 
          INTO VCNT1
          FROM CMM0050                     
         WHERE CM_HOLIDAY=TO_CHAR(SYSDATE,'YYYYMMDD')           
           AND CM_CLOSEDT IS NULL  ; 
       EXCEPTION
           WHEN  NO_DATA_FOUND THEN
               VCNT1 := 0;
    END;
                           
   IF VCNT1 > 0 THEN   
      HOLIGB := 'Y';  
   ELSE HOLIGB := 'N';  
   END IF;  
    
    
    SELECT DECODE(HOLIGB, 'Y', '03', DECODE(TO_CHAR(SYSDATE,'D'),1,'03',6,'02',7,'03','01'))
      INTO NOTICD
      FROM DUAL;
    
    BEGIN
        SELECT COUNT(*)
          INTO VCNT1
          FROM CMM0014 A                                     
         WHERE A.CM_STNO='ECAMS'                             
           AND NOTICD = A.CM_TIMECD
           AND   (     (    A.CM_STTIME <= TO_CHAR(SYSDATE,'HH24MI')
                        AND A.CM_EDTIME >= TO_CHAR(SYSDATE,'HH24MI')
                       )
                  OR   (    A.CM_STTIME <= TO_CHAR(SYSDATE,'HH24MI')
                        OR  A.CM_EDTIME >= TO_CHAR(SYSDATE,'HH24MI')
                       )
                 );
           EXCEPTION
               WHEN  NO_DATA_FOUND THEN
                   VCNT1 := 0;
    END;
                           

    BEGIN
        SELECT  DECODE(DECODE(VCNT1, 0, CM_HOLIGBN, CM_WORKGBN), 'S', 'SMS', 'M', 'UM', 'N')
          INTO  VRETMSG
          FROM  CMM0011
         WHERE  CM_NOTICD = NOTIGB;
        EXCEPTION 
            WHEN NO_DATA_FOUND THEN
                VRETMSG := 'N';
    END;
    
 
    RETURN  VRETMSG;
    
end;