-- GENERATED BY QueryOne AT 2021-03-04 14:17:02
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE TRIGGER "ECAMS".CMR9900_Trg 
   
    BEFORE INSERT or UPDATE or DELETE ON ECAMS.CMR9900              
                  
FOR EACH ROW
Declare              
   V_Editor      CMR1000.cr_editor%Type;              
   V_PassCd      CMR1000.cr_PassCd%Type;              
   V_UserName    CMM0040.CM_USERNAME%Type;              
   V_ConfUsr     CMR9900.CR_CONFUSR%Type;              
   V_AcptDate    Varchar2(10);   
   V_LinkUrl     Varchar2(200);   
   V_CNT         INTEGER;   
   V_SRID        CMR1000.CR_ITSMID%TYPE; 
   V_MSGACPT     VARCHAR2(50); 
   V_OWNER       VARCHAR2(50); 
                 
 Begin
 
         
            
   IF :NEW.cr_status = '0' AND :NEW.cr_team is not null AND               
      :NEW.cr_teamcd <> '1' AND :NEW.cr_locat = '00' AND :NEW.cr_confusr <> '9999' THEN 
      BEGIN              
        SELECT a.cr_editor,b.cm_codename,to_char(a.cr_acptdate,'yyyy/mm/dd'),A.CR_ITSMID,C.CM_URL,D.CM_USERNAME   
          INTO V_Editor,V_PassCd,V_AcptDate,V_SRID,V_LinkUrl,V_UserName   
          FROM cmr1000 a,cmm0020 b,CMM0010 C,CMM0040 D              
         WHERE a.cr_acptno=:NEW.cr_acptno         
           and b.cm_macode='REQUEST'         
           and b.cm_micode=a.cr_qrycd 
           AND C.CM_STNO='ECAMS' 
           AND A.CR_EDITOR=D.CM_USERID;              
         EXCEPTION              
              WHEN NO_DATA_FOUND THEN              
                   V_Editor := '';              
      END;   
       
      IF (:NEW.cr_teamcd = '3' OR :NEW.cr_teamcd = 'P') AND V_Editor = :NEW.cr_team THEN   
         V_Editor := '';   
      END IF;    
         
      IF V_Editor is not null THEN     
         V_MSGACPT := '신청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7,6); 
          
         V_LinkUrl := V_LinkUrl || 'ecams_win_flex/';   
         IF substr(:NEW.cr_acptno,5,2) = '01' or substr(:NEW.cr_acptno,5,2) = '02' or    
            substr(:NEW.cr_acptno,5,2) = '11' or substr(:NEW.cr_acptno,5,2) = '12' THEN    
            V_LinkUrl := V_LinkUrl || 'eCmr0150.jsp?ReqNo=' || :NEW.CR_ACPTNO;    
         ELSIF substr(:NEW.cr_acptno,5,2) = '03' or substr(:NEW.cr_acptno,5,2) = '04' or substr(:NEW.cr_acptno,5,2) = '07'    
            or substr(:NEW.cr_acptno,5,2) = '06' or substr(:NEW.cr_acptno,5,2) = '16' THEN    
            V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;  
         ELSIF substr(:NEW.cr_acptno,5,2) = '41' OR substr(:NEW.cr_acptno,5,2) = '69' THEN    
            V_LinkUrl := V_LinkUrl || 'eCmc0900.jsp?ReqNo=' || :NEW.CR_ACPTNO || '&IsrId=' || V_SRID;  
         ELSE /*substr(:NEW.cr_acptno,5,2) = '87' THEN */    
            V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;     
         END IF;     
                       
         IF :NEW.cr_teamcd = '4' OR :NEW.cr_teamcd = '5' OR :NEW.cr_teamcd = '9' THEN         
            INSERT INTO CMR9910              
               (cr_conusr, cr_senddate, cr_status, cr_acptno, cr_sendusr,cr_sgnmsg,cr_title,cr_linkurl,CR_NOTIGBN,CR_NOTICD,CR_SMSMSG)              
               (SELECT distinct A.CM_USERID,SYSDATE,'0',:NEW.cr_acptno, V_Editor,              
                       '1. 요청일 : ' || V_AcptDate || chr(13) ||              
                       '2. ' || V_MSGACPT || Chr(13) ||              
                       '3. 요청내용 : ' || V_PassCd || Chr(13) || '      에 대한 결재요청이 있습니다.' || Chr(13) ||               
                       '      형상관리시스템(eCAMS)에 접속하여 확인하여 주시기 바랍니다.'           
                       ,'형상관리 ' || C.CM_CODENAME || ' 결재요청'            
                       ,replace(V_LinkUrl,'UserId=?','UserId=' || A.CM_USERID)   
                       ,'CO','SMS'                        
                       ,'[형상관리 ' || C.CM_CODENAME || ' 결재요청]' || chr(10) ||
                        '요청일시:' || V_AcptDate || chr(10) ||   
                        '요청자:' || V_UserName
                  FROM CMM0040 A,CMM0043 B,CMM0020 C              
                 WHERE INSTR(:NEW.CR_TEAM,B.CM_RGTCD)>0              
                   AND B.CM_USERID=A.CM_USERID              
                   AND A.CM_ACTIVE='1' 
                   AND C.CM_MACODE='REQUEST' 
                   AND C.CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));            
         ELSE              
            INSERT INTO CMR9910              
               (cr_conusr, cr_senddate, cr_status, cr_acptno, cr_sendusr,cr_sgnmsg,cr_title,cr_linkurl,CR_NOTIGBN,CR_NOTICD,CR_SMSMSG)              
               (SELECT :NEW.cr_team, SYSDATE, '0', :NEW.cr_acptno, V_Editor,              
                        '1. 요청일 : ' || V_AcptDate || chr(13) ||              
                        '2. ' || V_MSGACPT || Chr(13) ||              
                        '3. 요청내용 : ' || V_PassCd || Chr(13) || '      에 대한 결재요청이 있습니다.' || Chr(13) ||               
                        '       형상관리시스템(eCAMS)에 접속하여 확인하여 주시기 바랍니다.'          
                        ,'형상관리 ' ||CM_CODENAME || ' 결재요청'             
                        ,replace(V_LinkUrl,'UserId=?','UserId=' || :NEW.cr_team) 
                        ,'CO','SMS'                        
                        ,'[형상관리 ' || CM_CODENAME || ' 결재요청]' || chr(10) ||
                        '요청일시:' || V_AcptDate || chr(10) ||   
                        '요청자:' || V_UserName
                  FROM CMM0020 
                 WHERE CM_MACODE='REQUEST' 
                   AND CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2)); 
         END IF;              
      END IF;              
   End If;              
                 
   IF :NEW.cr_status = '0' AND :NEW.cr_teamcd = '1' AND :NEW.cr_locat = '00' AND SUBSTR(:NEW.CR_ACPTNO,5,2) < '30' AND               
      (:OLD.CR_CONFUSR<>:NEW.CR_CONFUSR or :OLD.cr_team<>:NEW.cr_team)  THEN              
      UPDATE CMR1010              
         SET CR_SYSSTEP=0,              
             CR_PUTCODE='',              
             CR_PID=NULL,              
             CR_SRCCMP='Y'              
       WHERE CR_ACPTNO=:NEW.CR_ACPTNO;   
                
   END IF;              
 
   IF :NEW.cr_locat<>'00' AND :NEW.cr_status <> '0' AND :OLD.cr_status = '0' THEN              
      UPDATE CMR1000              
         SET CR_LASTDATE=SYSDATE,  
             CR_SYSSTEP=0  
       WHERE CR_ACPTNO=:NEW.CR_ACPTNO;              
   END IF;  
    
                 
End CMR9900_Trg;