-- GENERATED BY QueryOne AT 2021-03-04 14:18:50
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.CMR0020_Insert 
( 
 Call_Key_AcptNo       IN   Varchar2, 
 PrcSys                IN   Varchar2) 
 IS 
 ErrSw              Varchar2 (01); 
 VCNT               INTEGER := 0; 
Begin 
    IF PrcSys <> 'SYSPF' THEN 
        SELECT COUNT(*) 
          INTO VCNT 
          FROM CMR9900 
         WHERE CR_ACPTNO=Call_Key_AcptNo 
           AND CR_TEAM='SYSPF' 
           AND CR_LOCAT<>'00'; 
    END IF; 
     
    --IF PrcSys = 'SYSPF' OR VCNT = 0 THEN    20160203 수정 
    IF PrcSys = 'SYSPF' THEN    
       INSERT INTO CMR0020 
            ( CR_SYSCD 
            , CR_ITEMID 
            , CR_DSNCD 
            , CR_RSRCNAME 
            , CR_RSRCCD 
            , CR_JOBCD 
            , CR_LANGCD 
            , CR_STATUS 
            , CR_CREATOR 
            , CR_STORY 
            , CR_OPENDATE 
            , CR_LASTDATE 
            , CR_LSTVER 
            , CR_EDITOR 
            , CR_NOMODIFY 
            , CR_LSTUSR 
            , CR_LSTDAT 
            , CR_PGMTYPE 
            ) 
         (SELECT  A.CR_SYSCD 
               , LPAD(ITEMID_SEQ.NEXTVAL, 12, '0') 
               , A.CR_DSNCD 
               , A.CR_RSRCNAME 
               , A.CR_RSRCCD 
               , A.CR_JOBCD 
               , A.CR_LANGCD 
               , DECODE(A.CR_QRYCD, '09', '3' 
                                        , DECODE(B.CR_QRYCD, '03', 'A' 
                                                                 , '7' 
                                                ) 
                       ) 
               , A.CR_EDITOR 
               , A.CR_EDITCON 
               , SYSDATE 
               , SYSDATE 
               , '0' 
               , A.CR_EDITOR 
               , DECODE(A.CR_QRYCD, '09', '1', '0') 
               , A.CR_EDITOR 
               , SYSDATE 
               , A.CR_PGMTYPE 
           FROM  CMR1010 A 
               , CMR1000 B 
               , (SELECT  CR_SYSCD 
                        , CR_DSNCD 
                        , CR_RSRCNAME 
                    FROM  CMR1010 
                   WHERE  CR_ACPTNO = Call_Key_AcptNo 
                     AND  CR_ITEMID IS NULL 
                     AND  CR_BASEITEM IS NULL 
                   MINUS 
                  SELECT  X.CR_SYSCD 
                        , X.CR_DSNCD 
                        , X.CR_RSRCNAME 
                    FROM  CMR0020 X 
                        , CMR1010 Y 
                   WHERE  Y.CR_ACPTNO = Call_Key_AcptNo 
                     AND  Y.CR_ITEMID IS NULL 
                     AND  Y.CR_BASEITEM IS NULL 
                     AND  Y.CR_SYSCD    = X.CR_SYSCD 
                     AND  Y.CR_DSNCD    = X.CR_DSNCD 
                     AND  Y.CR_RSRCNAME = X.CR_RSRCNAME 
                 ) C 
          WHERE  A.CR_ACPTNO   = Call_Key_AcptNo 
            AND  A.CR_ACPTNO   = B.CR_ACPTNO 
            AND  A.CR_PRCDATE  IS NULL 
            AND  A.CR_ITEMID IS NULL 
            AND  A.CR_BASEITEM IS NULL 
            AND  A.CR_SYSCD    = C.CR_SYSCD 
            AND  A.CR_DSNCD    = C.CR_DSNCD 
            AND  A.CR_RSRCNAME = C.CR_RSRCNAME); 
    ELSE 
        INSERT INTO CMR0020 
            ( CR_SYSCD 
            , CR_ITEMID 
            , CR_DSNCD 
            , CR_RSRCNAME 
            , CR_RSRCCD 
            , CR_JOBCD 
            , CR_LANGCD 
            , CR_STATUS 
            , CR_CREATOR 
            , CR_STORY 
            , CR_OPENDATE 
            , CR_LASTDATE 
            , CR_LSTVER 
            , CR_EDITOR 
            , CR_NOMODIFY 
            , CR_LSTUSR 
            , CR_LSTDAT 
            , CR_PGMTYPE 
            ) 
         (SELECT  A.CR_SYSCD 
               , LPAD(ITEMID_SEQ.NEXTVAL, 12, '0') 
               , A.CR_DSNCD 
               , A.CR_RSRCNAME 
               , A.CR_RSRCCD 
               , A.CR_JOBCD 
               , A.CR_LANGCD 
               , DECODE(A.CR_QRYCD, '09', '3' 
                                        , DECODE(B.CR_QRYCD, '03', 'A' 
                                                                 , '7' 
                                                ) 
                       ) 
               , A.CR_EDITOR 
               , C.CR_STORY 
               , SYSDATE 
               , SYSDATE 
               , '0' 
               , A.CR_EDITOR 
               , DECODE(A.CR_QRYCD, '09', '1', '0') 
               , A.CR_EDITOR 
               , SYSDATE 
               , A.CR_PGMTYPE 
           FROM  CMR1010 A 
               , CMR1000 B 
               , CMR0020 C 
               , (SELECT  CR_SYSCD 
                        , CR_DSNCD 
                        , CR_RSRCNAME 
                    FROM  CMR1010 
                   WHERE  CR_ACPTNO = Call_Key_AcptNo 
                     AND  CR_ITEMID IS NULL 
                   MINUS 
                  SELECT  X.CR_SYSCD 
                        , X.CR_DSNCD 
                        , X.CR_RSRCNAME 
                    FROM  CMR0020 X 
                        , CMR1010 Y 
                   WHERE  Y.CR_ACPTNO = Call_Key_AcptNo 
                     AND  Y.CR_ITEMID IS NULL 
                     AND  Y.CR_SYSCD    = X.CR_SYSCD 
                     AND  Y.CR_DSNCD    = X.CR_DSNCD 
                     AND  Y.CR_RSRCNAME = X.CR_RSRCNAME 
                 ) D 
          WHERE  A.CR_ACPTNO   = Call_Key_AcptNo 
            AND  A.CR_ACPTNO   = B.CR_ACPTNO 
            AND  A.CR_BASEITEM = C.CR_ITEMID 
            AND  A.CR_PRCDATE  IS NULL 
            AND  A.CR_ITEMID IS NULL 
            AND  A.CR_SYSCD    = D.CR_SYSCD 
            AND  A.CR_DSNCD    = D.CR_DSNCD 
            AND  A.CR_RSRCNAME = D.CR_RSRCNAME); 
    END IF; 
End CMR0020_Insert;