-- GENERATED BY QueryOne AT 2021-03-04 14:17:56
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.MAKEPRCCNT 
(AcptNo IN VARCHAR2, 
 PrcSys IN VARCHAR2, 
 SerNo  IN NUMBER) 
RETURN NUMBER 
IS 
   VCNT  integer := 0; 
   V1CNT integer := 0; 
   V2CNT integer := 0; 
   V3CNT integer := 0; 
 
 
BEGIN 
    IF PrcSys = 'SYSDN' THEN                --체크아웃 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMR1000 F,CMM0038 E,CMM0031 D,CMM0036 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=F.CR_ACPTNO 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND A.CR_SYSCD=B.CM_SYSCD 
               AND A.CR_RSRCCD=B.CM_RSRCCD 
               AND SUBSTR(B.CM_INFO,3,1)=DECODE(F.CR_QRYCD,'13',SUBSTR(B.CM_INFO,3,1),'0') 
               AND SUBSTR(B.CM_INFO,45,1)='0'; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMR1000 F,CMM0038 E,CMM0031 D,CMM0036 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=F.CR_ACPTNO 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND A.CR_SYSCD=B.CM_SYSCD 
               AND A.CR_RSRCCD=B.CM_RSRCCD 
               AND SUBSTR(B.CM_INFO,3,1)=DECODE(F.CR_QRYCD,'13',SUBSTR(B.CM_INFO,3,1),'0') 
               AND SUBSTR(B.CM_INFO,45,1)='0'; 
       END IF; 
    END IF; 
 
    IF PrcSys = 'SYSPDN' THEN                --PC체크아웃 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMR1000 F,CMM0038 E,CMM0031 D,CMM0036 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=F.CR_ACPTNO 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND A.CR_SYSCD=B.CM_SYSCD 
               AND A.CR_RSRCCD=B.CM_RSRCCD 
               AND SUBSTR(B.CM_INFO,3,1)='0' 
               AND SUBSTR(B.CM_INFO,45,1)='1'; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMR1000 F,CMM0038 E,CMM0031 D,CMM0036 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=F.CR_ACPTNO 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND A.CR_SYSCD=B.CM_SYSCD 
               AND A.CR_RSRCCD=B.CM_RSRCCD 
               AND SUBSTR(B.CM_INFO,3,1)='0' 
               AND SUBSTR(B.CM_INFO,45,1)='1'; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSDNC' THEN                --체크아웃취소 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0036 B,CMM0038 E,CMM0031 D,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_QRYCD<>'03' 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND E.CM_SYSCD=B.CM_SYSCD 
               AND E.CM_RSRCCD=B.CM_RSRCCD 
               AND SUBSTR(B.CM_INFO,3,1)='0'; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0036 B,CMM0038 E,CMM0031 D,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_QRYCD<>'03' 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND E.CM_SYSCD=B.CM_SYSCD 
               AND E.CM_RSRCCD=B.CM_RSRCCD 
               AND SUBSTR(B.CM_INFO,3,1)='0'; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSFMK' THEN                --버전파일생성 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMR1000 F,CMM0036 B,CMM0038 E,CMM0031 D,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=F.CR_ACPTNO 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND E.CM_SYSCD=B.CM_SYSCD 
               AND E.CM_RSRCCD=B.CM_RSRCCD 
               AND SUBSTR(B.CM_INFO,3,1)='0' 
               AND SUBSTR(B.CM_INFO,45,1)='1'; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMR1000 F,CMM0036 B,CMM0038 E,CMM0031 D,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=F.CR_ACPTNO 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND E.CM_SYSCD=B.CM_SYSCD 
               AND E.CM_RSRCCD=B.CM_RSRCCD 
               AND SUBSTR(B.CM_INFO,3,1)='0' 
               AND SUBSTR(B.CM_INFO,45,1)='1'; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSUP' AND SUBSTR(AcptNo,5,2) <> '16' THEN                --형상관리저장(일괄등록아님) 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND (SUBSTR(C.CM_INFO,DECODE(SUBSTR(AcptNo,5,2),'07',22,'03',63,'08',49,11),1)='1' OR   --형상관리저장스크립트실행 
                    SUBSTR(C.CM_INFO,DECODE(SUBSTR(AcptNo,5,2),'07',24,'03',62,'08',42,13),1)='1')     --개발서버에서체크인 
-- 2016.05.24 추가 
               AND SUBSTR(C.CM_INFO,12,1) = '1'
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND (SUBSTR(C.CM_INFO,DECODE(SUBSTR(AcptNo,5,2),'07',22,'03',63,'08',49,11),1)='1' OR   --형상관리저장스크립트실행 
                    SUBSTR(C.CM_INFO,DECODE(SUBSTR(AcptNo,5,2),'07',24,'03',62,'08',42,13),1)='1')     --개발서버에서체크인 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               and SUBSTR(C.CM_INFO,27,1)='0'; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSUP' AND SUBSTR(AcptNo,5,2) = '16' THEN                --형상관리저장(일괄등록) 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,24,1)='1'     --개발서버에서체크인 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD=B.CR_SVRCD 
               AND D.CM_SEQNO=B.CR_SVRSEQ 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,24,1)='1'     --개발서버에서체크인 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD=B.CR_SVRCD 
               AND D.CM_SEQNO=B.CR_SVRSEQ 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSPUP' THEN                --PC파일UP-LOAD 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMR1000 F,CMM0038 E,CMM0031 D,CMM0036 C,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=F.CR_ACPTNO 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,24,1)='1'     --개발서버에서체크인 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,45,1)='1'; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMR1000 F,CMM0038 E,CMM0031 D,CMM0036 C,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=F.CR_ACPTNO 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,24,1)='1'     --개발서버에서체크인 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_SVRCD='01' 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,45,1)='1'; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSCB' THEN 
       IF SerNo = 0 THEN 
            --검증서버컴파일 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               --AND (B.CR_QRYCD='03' or B.CR_SYSCD NOT IN ('00005','00006') OR 
               --     (B.CR_QRYCD<>'03' AND B.CR_SYSCD IN ('00005','00006') AND A.CR_RSRCCD IN ('12','20','46','47','48','49','50'))) 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','13','16','13','08','23','03') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND (SUBSTR(C.CM_INFO,DECODE(B.CR_QRYCD,'08',42,'03',62,13),1)='1'  OR    --검증서버파일COPY 
                    SUBSTR(C.CM_INFO,DECODE(B.CR_QRYCD,'08',39,'03',61,1),1)='1')  --검증서버컴파일 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
 
       ELSE  -- 특정프로그램 
            --검증서버컴파일 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','13','16','13','08','23','03') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND (SUBSTR(C.CM_INFO,DECODE(B.CR_QRYCD,'08',42,'03',62,13),1)='1'  OR    --검증서버파일COPY 
                    SUBSTR(C.CM_INFO,DECODE(B.CR_QRYCD,'08',39,'03',61,1),1)='1')  --검증서버컴파일 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSGB' THEN 
       IF SerNo = 0 THEN 
            -- 검증서버체크인 
            SELECT COUNT(*) 
              INTO V2CNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               --AND (B.CR_QRYCD='03' or B.CR_SYSCD NOT IN ('00005','00006')) 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','13','16','13','08','23','03') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,25,1)='1'    --검증서버체크인 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       ELSE 
            -- 검증서버체크인 
            SELECT COUNT(*) 
              INTO V2CNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               --AND (B.CR_QRYCD='03' or B.CR_SYSCD NOT IN ('00005','00006')) 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','13','16','13','08','23','03') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,25,1)='1'    --검증서버체크인 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSED' THEN                    --배포처리 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','15','16','15','08','25','05','07','25') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND (SUBSTR(C.CM_INFO,DECODE(B.CR_QRYCD,'07',49,'03',63,11),1)='1' OR        --운영서버파일COPY 
                    SUBSTR(C.CM_INFO,DECODE(B.CR_QRYCD,'07',51,'03',64,21),1)='1')          --배포스크립트실행 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       ELSE -- 일련번호 들어옴 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','15','16','15','08','25','05','07','25') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND (SUBSTR(C.CM_INFO,DECODE(B.CR_QRYCD,'07',49,'03',63,11),1)='1' OR        --운영서버파일COPY 
                    SUBSTR(C.CM_INFO,DECODE(B.CR_QRYCD,'07',51,'03',64,21),1)='1')          --배포스크립트실행 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSRC' THEN                    --적용처리 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','15','07','25','05') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,35,1)='1'      --적용스크립트실행 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','15','07','25','05') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,35,1)='1'      --적용스크립트실행 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSCL' THEN                    --폐기처리 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','13','08','23','03') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,18,1)='1' 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
       ELSE -- 일련번호 들어옴 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD=DECODE(B.CR_QRYCD,'03','13','08','23','03') 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,18,1)='1' 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD ; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSAR' THEN                    --사후처리 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_STATUS<>'3' 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD='09' 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,40,1)='1'       --사후처리쉘실행 
               AND SUBSTR(C.CM_INFO,41,1)<>'1'      --사후처리일괄쉘실행 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
 
            SELECT COUNT(*) 
              INTO V1CNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_STATUS<>'3' 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD='09' 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,40,1)='1'      --적용스크립트실행 
               AND SUBSTR(C.CM_INFO,41,1)='1'      --사후처리일괄쉘실행 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
 
            IF V1CNT > 0 THEN 
               V1CNT := 1; 
            END IF; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD='09' 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,40,1)='1'      --사후스크립트실행 
               AND SUBSTR(C.CM_INFO,41,1)<>'1'     --사후스크립트일괄실행 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
 
            SELECT COUNT(*) 
              INTO V1CNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND D.CM_SVRCD='09' 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,40,1)='1'      --사후스크립트실행 
               AND SUBSTR(C.CM_INFO,41,1)<>'1'     --사후스크립트일괄실행 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD; 
 
            IF V1CNT > 0 THEN 
               V1CNT := 1; 
            END IF; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSAL' THEN                    --영향분석파일전송 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 D,CMM0031 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_STATUS<>'3' 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND B.CR_SYSCD=C.CM_SYSCD 
               AND C.CM_SVRCD='90' 
               AND C.CM_CLOSEDT IS NULL 
               AND C.CM_SYSCD=D.CM_SYSCD 
               AND C.CM_SVRCD=D.CM_SVRCD 
               AND C.CM_SEQNO=D.CM_SEQNO 
               AND A.CR_RSRCCD=D.CM_RSRCCD; 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 D,CMM0031 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND B.CR_SYSCD=C.CM_SYSCD 
               AND C.CM_SVRCD='90' 
               AND C.CM_CLOSEDT IS NULL 
               AND C.CM_SYSCD=D.CM_SYSCD 
               AND C.CM_SVRCD=D.CM_SVRCD 
               AND C.CM_SEQNO=D.CM_SEQNO 
               AND A.CR_RSRCCD=D.CM_RSRCCD; 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSANL' THEN                    --영향분석연계 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_STATUS<>'3' 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,34,1)='1';      --영향분석대상 
       ELSE 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND SUBSTR(C.CM_INFO,34,1)='1';      --영향분석대상 
       END IF; 
    END IF; 
 
    IF PrcSys = 'SYSCED' AND SUBSTR(AcptNo,5,2) <> '03' AND SUBSTR(AcptNo,5,2) <> '04' THEN 
       --원복처리 (테스트적용요청,운영체크인요청이 아닌 경우) 
       -- '12' : 테스트적용취소 
       -- '06' : 롤백 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND INSTR(DECODE(B.CR_QRYCD,'06','05'),D.CM_SVRCD)>0 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND ( 
                    (D.CM_SVRCD IN ('03','13') AND SUBSTR(C.CM_INFO,13,1)='1') OR   --빌드서버파일COPY 
                    (D.CM_SVRCD IN ('05','15') AND (SUBSTR(C.CM_INFO,11,1)='1' OR        --배포서버파일COPY(운영) 
                         (SUBSTR(C.CM_INFO,21,1)='1' AND SUBSTR(C.CM_INFO,29,1)='0'))) 
                                                           --배포스크립트실행  
                   ) 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD ; 
 
            --파일COPY없이 일괄링크만 하는 건수 
            SELECT COUNT(*) 
              INTO V1CNT 
              FROM (SELECT B.CR_JOBCD,B.CR_RSRCCD 
                      FROM CMR1000 A, CMR1010 B, CMM0031 C, CMM0038 D, CMM0036 E 
                     WHERE B.CR_ACPTNO = AcptNo 
                       AND	B.CR_PRCDATE IS  NULL 
                       AND	B.CR_ACPTNO = A.CR_ACPTNO 
                       AND	B.CR_SYSCD	= C.CM_SYSCD 
                       AND INSTR(DECODE(B.CR_QRYCD,'06','15,05','15'),D.CM_SVRCD)>0 
                       AND	C.CM_CLOSEDT IS NULL 
                       AND	C.CM_SYSCD	= D.CM_SYSCD 
                       AND	C.CM_SVRCD	= D.CM_SVRCD 
                       AND	C.CM_SEQNO	= D.CM_SEQNO 
                       AND	B.CR_RSRCCD	= D.CM_RSRCCD 
                       AND  D.CM_SYSCD  = E.CM_SYSCD 
                       AND  D.CM_RSRCCD = E.CM_RSRCCD 
                       AND  SUBSTR(E.CM_INFO,21,1) = '1'   --배포스크립트실행 
                       AND  SUBSTR(E.CM_INFO,11,1) = '0'   --배포서버파일COPY 
                       AND  SUBSTR(E.CM_INFO,29,1) = '1'   --일괄쉘실행 
                    group by b.cr_jobcd,b.cr_rsrccd); 
       ELSE -- 일련번호 들어옴 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND INSTR(DECODE(B.CR_QRYCD,'06','13,15,03,05','13,15'),D.CM_SVRCD)>0 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND ( 
                    (D.CM_SVRCD IN ('03','13') AND SUBSTR(C.CM_INFO,13,1)='1') OR   --빌드서버파일COPY 
                    (D.CM_SVRCD IN ('05','15') AND (SUBSTR(C.CM_INFO,11,1)='1' OR        --배포서버파일COPY(운영) 
                         (SUBSTR(C.CM_INFO,21,1)='1' AND SUBSTR(C.CM_INFO,29,1)='0'))) 
                                                           --배포스크립트실행  
                   ) 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD ; 
 
            --파일COPY없이 일괄링크만 하는 건수 
            SELECT COUNT(*) 
              INTO V1CNT 
              FROM (SELECT B.CR_JOBCD,B.CR_RSRCCD 
                      FROM CMR1000 A, CMR1010 B, CMM0031 C, CMM0038 D, CMM0036 E 
                     WHERE  B.CR_ACPTNO = AcptNo 
                       AND  B.CR_SERNO=SerNo 
                       AND	B.CR_PRCDATE IS  NULL 
                       AND	B.CR_ACPTNO = A.CR_ACPTNO 
                       AND	B.CR_SYSCD	= C.CM_SYSCD 
                       AND INSTR(DECODE(B.CR_QRYCD,'06','15,05','15'),D.CM_SVRCD)>0 
                       AND	C.CM_CLOSEDT IS NULL 
                       AND	C.CM_SYSCD	= D.CM_SYSCD 
                       AND	C.CM_SVRCD	= D.CM_SVRCD 
                       AND	C.CM_SEQNO	= D.CM_SEQNO 
                       AND	B.CR_RSRCCD	= D.CM_RSRCCD 
                       AND  D.CM_SYSCD  = E.CM_SYSCD 
                       AND  D.CM_RSRCCD = E.CM_RSRCCD 
                       AND  SUBSTR(E.CM_INFO,21,1) = '1'   --배포스크립트실행 
                       AND  SUBSTR(E.CM_INFO,11,1) = '0'   --배포서버파일COPY 
                       AND  SUBSTR(E.CM_INFO,29,1) = '1'   --일괄쉘실행 
                    group by b.cr_jobcd,b.cr_rsrccd); 
       END IF; 
    END IF; 
    IF PrcSys = 'SYSCED' AND (SUBSTR(AcptNo,5,2) = '03' OR SUBSTR(AcptNo,5,2) = '04') THEN 
       -- 테스트적용요청,운영체크인요청 중 원복처리 
       -- '03' : 테스트적용 
       -- '04' : 운영적용 
       IF SerNo = 0 THEN 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND INSTR(ROLLBACK_SVR(B.CR_ACPTNO,B.CR_QRYCD,'F'),D.CM_SVRCD)>0 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND ( 
                    (D.CM_SVRCD IN ('03','13') AND SUBSTR(C.CM_INFO,13,1)='1') OR   --빌드서버파일COPY 
                    (D.CM_SVRCD IN ('05','15') AND (SUBSTR(C.CM_INFO,11,1)='1' OR        --배포서버파일COPY(운영) 
                         (SUBSTR(C.CM_INFO,21,1)='1' AND SUBSTR(C.CM_INFO,29,1)='0'))) 
                                                           --배포스크립트실행  
                   ) 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD ; 
 
            --파일COPY없이 일괄링크만 하는 건수 
            SELECT COUNT(*) 
              INTO V1CNT 
              FROM (SELECT B.CR_JOBCD,B.CR_RSRCCD 
                      FROM CMR1000 A, CMR1010 B, CMM0031 C, CMM0038 D, CMM0036 E 
                     WHERE B.CR_ACPTNO = AcptNo 
                       AND	B.CR_PRCDATE IS  NULL 
                       AND	B.CR_ACPTNO = A.CR_ACPTNO 
                       AND	B.CR_SYSCD	= C.CM_SYSCD 
                       AND  INSTR(ROLLBACK_SVR(A.CR_ACPTNO,A.CR_QRYCD,'F'),C.CM_SVRCD)>0 
                       AND	C.CM_CLOSEDT IS NULL 
                       AND	C.CM_SYSCD	= D.CM_SYSCD 
                       AND	C.CM_SVRCD	= D.CM_SVRCD 
                       AND	C.CM_SEQNO	= D.CM_SEQNO 
                       AND	B.CR_RSRCCD	= D.CM_RSRCCD 
                       AND  D.CM_SYSCD  = E.CM_SYSCD 
                       AND  D.CM_RSRCCD = E.CM_RSRCCD 
                       AND  SUBSTR(E.CM_INFO,21,1) = '1'   --배포스크립트실행 
                       AND  SUBSTR(E.CM_INFO,11,1) = '0'   --배포서버파일COPY 
                       AND  SUBSTR(E.CM_INFO,29,1) = '1'   --일괄쉘실행 
                    group by b.cr_jobcd,b.cr_rsrccd); 
       ELSE -- 일련번호 들어옴 
            SELECT COUNT(*) 
              INTO VCNT 
              FROM CMM0038 E,CMM0031 D,CMM0036 C,CMR1000 B,CMR1010 A 
             WHERE A.CR_ACPTNO=AcptNo 
               AND A.CR_SERNO=SerNo 
               AND A.CR_PRCDATE IS NULL 
               AND A.CR_ACPTNO=B.CR_ACPTNO 
               AND INSTR(ROLLBACK_SVR(B.CR_ACPTNO,B.CR_QRYCD,'F'),D.CM_SVRCD)>0 
               AND A.CR_SYSCD=C.CM_SYSCD 
               AND A.CR_RSRCCD=C.CM_RSRCCD 
               AND ( 
                    (D.CM_SVRCD IN ('03','13') AND SUBSTR(C.CM_INFO,13,1)='1') OR   --빌드서버파일COPY 
                    (D.CM_SVRCD IN ('05','15') AND (SUBSTR(C.CM_INFO,11,1)='1' OR        --배포서버파일COPY(운영) 
                         (SUBSTR(C.CM_INFO,21,1)='1' AND SUBSTR(C.CM_INFO,29,1)='0'))) 
                                                           --배포스크립트실행  
                   ) 
               AND A.CR_SYSCD=D.CM_SYSCD 
               AND D.CM_CLOSEDT IS NULL 
               AND D.CM_SYSCD=E.CM_SYSCD 
               AND D.CM_SVRCD=E.CM_SVRCD 
               AND D.CM_SEQNO=E.CM_SEQNO 
               AND A.CR_RSRCCD=E.CM_RSRCCD ; 
 
            --파일COPY없이 일괄링크만 하는 건수 
            SELECT COUNT(*) 
              INTO V1CNT 
              FROM (SELECT B.CR_JOBCD,B.CR_RSRCCD 
                      FROM CMR1000 A, CMR1010 B, CMM0031 C, CMM0038 D, CMM0036 E 
                     WHERE  B.CR_ACPTNO = AcptNo 
                       AND  B.CR_SERNO=SerNo 
                       AND	B.CR_PRCDATE IS  NULL 
                       AND	B.CR_ACPTNO = A.CR_ACPTNO 
                       AND	B.CR_SYSCD	= C.CM_SYSCD 
                       AND  INSTR(ROLLBACK_SVR(B.CR_ACPTNO,B.CR_QRYCD,'F'),D.CM_SVRCD)>0 
                       AND	C.CM_CLOSEDT IS NULL 
                       AND	C.CM_SYSCD	= D.CM_SYSCD 
                       AND	C.CM_SVRCD	= D.CM_SVRCD 
                       AND	C.CM_SEQNO	= D.CM_SEQNO 
                       AND	B.CR_RSRCCD	= D.CM_RSRCCD 
                       AND  D.CM_SYSCD  = E.CM_SYSCD 
                       AND  D.CM_RSRCCD = E.CM_RSRCCD 
                       AND  SUBSTR(E.CM_INFO,21,1) = '1'   --배포스크립트실행 
                       AND  SUBSTR(E.CM_INFO,11,1) = '0'   --배포서버파일COPY 
                       AND  SUBSTR(E.CM_INFO,29,1) = '1'   --일괄쉘실행 
                    group by b.cr_jobcd,b.cr_rsrccd); 
       END IF; 
    END IF; 
    VCNT := VCNT + V1CNT + V2CNT; 
 
    return VCNT; 
end;