-- GENERATED BY QueryOne AT 2021-03-04 14:17:56
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.NAMECHANGE
(INSYSCD IN VARCHAR2,
 INRSRCNAME IN VARCHAR2,
 INSAMENAME IN VARCHAR2,
 INDIRPATH  IN VARCHAR2,
 INBASEITEM IN VARCHAR2,
 INACPTNO   IN VARCHAR2,
 INRSRCCD   IN VARCHAR2)
RETURN VARCHAR2
IS
   VCNT1 INT := 0;
   STRWORK1           VARCHAR2(300);
   STRWORK2           VARCHAR2(300);
   STRWORK3           VARCHAR2(300);
   STRWORK4           VARCHAR2(300);
   STRWORK5           VARCHAR2(300);
   BASEDIR            VARCHAR2(300);
   BASENAME           VARCHAR2(300);
   BASERSRC           VARCHAR2(2);
   RSTMSG             VARCHAR2(10000);
   ERRSW              BOOLEAN;
   I   INTEGER := 0;
   J   INTEGER := 0;
 --- 자신의 기준프로그램이 동시적용여부 CHECK
BEGIN
    STRWORK1 := INSAMENAME;
    STRWORK2 := NULL;
    STRWORK3 := NULL;
    STRWORK4 := NULL;
    STRWORK5 := NULL;
    BASEDIR := NULL;
    BASENAME := NULL;
    BASERSRC := NULL;
    ERRSW := FALSE;
    RSTMSG := '';

    IF INSTR(STRWORK1,'?#BASEDIR')>0 OR INSTR(STRWORK1,'?#PARENT')>0 THEN
       SELECT B.CM_DIRPATH,A.CR_RSRCNAME,A.CR_RSRCCD
         INTO BASEDIR,BASENAME,BASERSRC
         FROM CMM0070 B,CMR0020 A
        WHERE A.CR_ITEMID=INBASEITEM
          AND A.CR_SYSCD=B.CM_SYSCD
          AND A.CR_DSNCD=B.CM_DSNCD;
       IF BASEDIR IS NULL THEN
          RETURN 'ERROR 기준프로그램정보 추출오류';
       END IF;
    END IF;

    LOOP
       STRWORK4 := STRWORK1;
       IF INSTR(STRWORK4,'?#') = 0 THEN
          RSTMSG := 'ERROR';
          EXIT;
       END IF;
       J := INSTR(STRWORK4,'?#')+2;
       STRWORK4 := SUBSTR(STRWORK4,J);
       J := INSTR(STRWORK4,'#');
       IF J = 0 THEN
          RSTMSG := 'ERROR';
          EXIT;
       END IF;
       STRWORK2 := '?#' || SUBSTR(STRWORK4,1,J);

       dbms_OUTPUT.PUT_LINE('63 Line STRWORK1=' || STRWORK1 || ', STRWORK2=' || STRWORK2);
       STRWORK3 := STRWORK1;
       IF STRWORK2 = '?#ACPTNO#' THEN
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,INACPTNO);
       ELSIF STRWORK2 = '?#SRCFILE#' THEN
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,INRSRCNAME);
       ELSIF STRWORK2 = '?#SYSCD#' THEN
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,INSYSCD);
       ELSIF STRWORK2 = '?#SRCDIR#' THEN
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,INDIRPATH);
       ELSIF STRWORK2 = '?#BASEDIR#' THEN
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,BASEDIR);
       ELSIF STRWORK2 = '?#EXENAME#' OR
             STRWORK2 = '?#LOWEXENAME#' OR
             STRWORK2 = '?#UPEXENAME#' THEN
          IF INSTR(INRSRCNAME,'.')>0 THEN
             STRWORK4 := SUBSTR(INRSRCNAME,1,INSTR(INRSRCNAME,'.',-1)-1);
          ELSE
             STRWORK4 := INRSRCNAME;
          END IF;
          IF STRWORK2 = '?#LOWEXENAME#' THEN
             STRWORK4 := LOWER(STRWORK4);
          ELSIF STRWORK2 = '?#UPEXENAME#' THEN
             STRWORK4 := UPPER(STRWORK4);
          END IF;
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,STRWORK4);
       ELSIF STRWORK2 = '?#BEFEXENAME#' THEN
          IF INSTR(INRSRCNAME,'.')>0 THEN
             STRWORK4 := SUBSTR(INRSRCNAME,1,INSTR(INRSRCNAME,'.')-1);
          ELSE
             STRWORK4 := INRSRCNAME;
          END IF;
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,STRWORK4);
       --   dbms_OUTPUT.PUT_LINE('96 Line STRWORK1=' || STRWORK1 || ', STRWORK4=' || STRWORK4);
       ELSIF STRWORK2 = '?#AFTEXE#' THEN
          IF INSTR(INRSRCNAME,'.')>0 THEN
             STRWORK4 := SUBSTR(INRSRCNAME,INSTR(INRSRCNAME,'.',-1)+1);
          ELSE
             STRWORK4 := '';
          END IF;
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,STRWORK4);
       ELSIF STRWORK2 = '?#TABLENM#' THEN
          IF INSTR(INRSRCNAME,'_')>0 THEN
             STRWORK4 := SUBSTR(INRSRCNAME,1,INSTR(INRSRCNAME,'_',-1)-1);
          ELSE
             STRWORK4 := '';
          END IF;
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,STRWORK4);
       ELSIF STRWORK2 = '?#SRCHOME#' THEN
          STRWORK5 := NULL;
          SELECT C.CM_VOLPATH
            INTO STRWORK5
            FROM CMM0038 C,CMM0031 B,CMM0030 A
           WHERE A.CM_SYSCD=INSYSCD
             AND A.CM_SYSCD=B.CM_SYSCD
             AND A.CM_DIRBASE=B.CM_SVRCD
             AND B.CM_CLOSEDT IS NULL
             AND B.CM_SYSCD=C.CM_SYSCD
             AND B.CM_SVRCD=C.CM_SVRCD
             AND B.CM_SEQNO=C.CM_SEQNO
             AND C.CM_RSRCCD=INRSRCCD;

          IF STRWORK5 IS NULL THEN
             RSTMSG := 'ERROR홈경로미설정';
             EXIT;
          END IF;

          STRWORK1 := REPLACE(STRWORK3,STRWORK2,STRWORK5);
       ELSIF STRWORK2 = '?#PARENTEXENM#' THEN
          IF INSTR(BASENAME,'.') >0 THEN
             STRWORK5 := SUBSTR(BASENAME,1,INSTR(BASENAME,'.')-1);
          ELSE
             STRWORK5 := BASENAME;
          END IF;
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,STRWORK5);
       ELSIF STRWORK2 = '?#SRCDIRA1S#' OR
             STRWORK2 = '?#SRCDIRA2S#' OR
             STRWORK2 = '?#SRCDIRA3S#' OR
             STRWORK2 = '?#SRCDIRA4S#' OR
             STRWORK2 = '?#SRCDIRA5S#' OR
             STRWORK2 = '?#SRCDIRA6S#' OR
             STRWORK2 = '?#SRCDIRA7S#' OR
             STRWORK2 = '?#SRCDIRA8S#' OR
             STRWORK2 = '?#SRCDIRA9S#' OR
             STRWORK2 = '?#BASEDIRA1S#' OR
             STRWORK2 = '?#BASEDIRA2S#' OR
             STRWORK2 = '?#BASEDIRA3S#' OR
             STRWORK2 = '?#BASEDIRA4S#' OR
             STRWORK2 = '?#BASEDIRA5S#' OR
             STRWORK2 = '?#BASEDIRA6S#' OR
             STRWORK2 = '?#BASEDIRA7S#' OR
             STRWORK2 = '?#BASEDIRA8S#' OR
             STRWORK2 = '?#BASEDIRA9S#' THEN
          IF SUBSTR(STRWORK2,3,3) = 'SRC' THEN
             STRWORK5 := INDIRPATH;
             J := SUBSTR(STRWORK2,10,1);
          ELSE
             STRWORK5 := BASEDIR;
             J := SUBSTR(STRWORK2,11,1);
          END IF;

          I := 0;
          LOOP
             I := I+1;
             IF INSTR(STRWORK5,'/') = 0 THEN
                IF SUBSTR(STRWORK2,3,3) = 'SRC' THEN
                   RSTMSG := 'ERROR경로확인' || INDIRPATH;
                ELSE
                   RSTMSG := 'ERROR경로확인' || BASEDIR;
                END IF;
                EXIT;
             END IF;
             STRWORK4 := SUBSTR(STRWORK5,INSTR(STRWORK5,'/',-1)+1);
             STRWORK5 := SUBSTR(STRWORK5,1,INSTR(STRWORK5,'/',-1)-1);
             IF I= J THEN
                EXIT;
             END IF;
          END LOOP;
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,STRWORK4);
       ELSIF STRWORK2 = '?#SRCDIRB1S#' OR
             STRWORK2 = '?#SRCDIRB2S#' OR
             STRWORK2 = '?#SRCDIRB3S#' OR
             STRWORK2 = '?#SRCDIRB4S#' OR
             STRWORK2 = '?#SRCDIRB5S#' OR
             STRWORK2 = '?#SRCDIRB6S#' OR
             STRWORK2 = '?#SRCDIRB7S#' OR
             STRWORK2 = '?#SRCDIRB8S#' OR
             STRWORK2 = '?#SRCDIRB9S#' OR
             STRWORK2 = '?#BASEDIRB1S#' OR
             STRWORK2 = '?#BASEDIRB2S#' OR
             STRWORK2 = '?#BASEDIRB3S#' OR
             STRWORK2 = '?#BASEDIRB4S#' OR
             STRWORK2 = '?#BASEDIRB5S#' OR
             STRWORK2 = '?#BASEDIRB6S#' OR
             STRWORK2 = '?#BASEDIRB7S#' OR
             STRWORK2 = '?#BASEDIRB8S#' OR
             STRWORK2 = '?#BASEDIRB9S#' THEN
          IF SUBSTR(STRWORK2,3,3) = 'SRC' THEN
             STRWORK5 := INDIRPATH;
             J := SUBSTR(STRWORK2,10,1);
          ELSE
             STRWORK5 := BASEDIR;
             J := SUBSTR(STRWORK2,11,1);
          END IF;

          IF SUBSTR(STRWORK5,1,1) = '/' THEN
             STRWORK5 := SUBSTR(STRWORK5,2);
          END IF;
          I := 0;
          LOOP
             I := I+1;

             IF STRWORK5 IS NULL THEN
                IF SUBSTR(STRWORK2,3,3) = 'SRC' THEN
                   RSTMSG := 'ERROR경로확인' || INDIRPATH;
                ELSE
                   RSTMSG := 'ERROR경로확인' || BASEDIR;
                END IF;
                EXIT;
             END IF;
             IF INSTR(STRWORK5,'/')=0 THEN
                STRWORK4 := STRWORK5;
                STRWORK5 := NULL;
             ELSE
	             STRWORK4 := SUBSTR(STRWORK5,1,INSTR(STRWORK5,'/')-1);
	             STRWORK5 := SUBSTR(STRWORK5,INSTR(STRWORK5,'/')+1);
	         END IF;
             dbms_OUTPUT.PUT_LINE('63 Line I=' || I || ', STRWORK4=' || STRWORK4 || ', STRWORK5=' || STRWORK5);
             IF I= J THEN
                EXIT;
             END IF;
          END LOOP;
          IF RSTMSG IS NOT NULL THEN
             IF SUBSTR(RSTMSG,1,5) = 'ERROR' THEN
                EXIT;
             END IF;
          END IF;

          STRWORK1 := REPLACE(STRWORK3,STRWORK2,STRWORK4);
       ELSIF STRWORK2 = '?#SRCDIRB1#' OR
             STRWORK2 = '?#SRCDIRB2#' OR
             STRWORK2 = '?#SRCDIRB3#' OR
             STRWORK2 = '?#SRCDIRB4#' OR
             STRWORK2 = '?#SRCDIRB5#' OR
             STRWORK2 = '?#SRCDIRB6#' OR
             STRWORK2 = '?#SRCDIRB7#' OR
             STRWORK2 = '?#SRCDIRB8#' OR
             STRWORK2 = '?#SRCDIRB9#' OR
             STRWORK2 = '?#BASEDIRB1#' OR
             STRWORK2 = '?#BASEDIRB2#' OR
             STRWORK2 = '?#BASEDIRB3#' OR
             STRWORK2 = '?#BASEDIRB4#' OR
             STRWORK2 = '?#BASEDIRB5#' OR
             STRWORK2 = '?#BASEDIRB6#' OR
             STRWORK2 = '?#BASEDIRB7#' OR
             STRWORK2 = '?#BASEDIRB8#' OR
             STRWORK2 = '?#BASEDIRB9#' THEN
          IF SUBSTR(STRWORK2,3,3) = 'SRC' THEN
             STRWORK5 := INDIRPATH;
             J := SUBSTR(STRWORK2,10,1);
          ELSE
             STRWORK5 := BASEDIR;
             J := SUBSTR(STRWORK2,11,1);
          END IF;

          I := 0;
          STRWORK4 := NULL;
          IF SUBSTR(STRWORK5,1,1) = '/' THEN
             STRWORK5 := SUBSTR(STRWORK5,2);
          END IF;
          LOOP
             I := I+1;

             IF STRWORK5 IS NULL THEN
                IF SUBSTR(STRWORK2,3,3) = 'SRC' THEN
                   RSTMSG := 'ERROR경로확인' || INDIRPATH;
                ELSE
                   RSTMSG := 'ERROR경로확인' || BASEDIR;
                END IF;
                EXIT;
             END IF;

             IF INSTR(STRWORK5,'/')=0 THEN
                STRWORK4 := STRWORK4 || '/' || STRWORK5;
                STRWORK5 := NULL;
             ELSE
	             STRWORK4 := STRWORK4 || '/' || SUBSTR(STRWORK5,1,INSTR(STRWORK5,'/')-1);
	             STRWORK5 := SUBSTR(STRWORK5,INSTR(STRWORK5,'/')+1);
	         END IF;
             IF I= J THEN
                EXIT;
             END IF;
          END LOOP;
          IF RSTMSG IS NOT NULL THEN
             IF SUBSTR(RSTMSG,1,5) = 'ERROR' THEN
                EXIT;
             END IF;
          END IF;
        --  dbms_OUTPUT.PUT_LINE('299 Line STRWORK3=' || STRWORK3 || ', STRWORK2=' || STRWORK2  || ', STRWORK4=' || STRWORK4);
          STRWORK1 := REPLACE(STRWORK3,STRWORK2,STRWORK4);
       ELSE
          RSTMSG := 'ERROR변환방법미정의 [' || STRWORK2 || ']';
          EXIT;
       END IF;
       IF INSTR(STRWORK1,'?#')=0 THEN
          EXIT;
       END IF;
    END LOOP;

    IF RSTMSG IS NOT NULL THEN
       IF SUBSTR(RSTMSG,1,5) = 'ERROR' THEN
          RETURN RSTMSG;
       END IF;
    END IF;
    RETURN STRWORK1;
end;