-- GENERATED BY QueryOne AT 2021-03-04 14:16:59
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE TRIGGER ECAMS.CMC0100_Trg 

BEFORE UPDATE ON CMC0100                   
                       
FOR EACH ROW
Declare                   
     
   V_CNT         INTEGER;        
                      
 Begin
 
    IF :NEW.cc_reqgrade = '01' and :NEW.cc_status = '13' AND (:OLD.cc_status = '11' OR :OLD.cc_status = '12') THEN  -- 11 :개발계획서 작성 완료, 12 :개발중   
                 
        INSERT INTO CMR9910                   
           (cr_conusr, cr_senddate, cr_status, cr_acptno, cr_sendusr,cr_sgnmsg,cr_title,cr_linkurl,cr_noticd)                   
        VALUES                   
           (:NEW.cc_owner, SYSDATE, '0', '999999999999', :NEW.cc_addusr,                   
            '1. 요청일 : ' || to_char(sysdate,'yyyy/mm/dd hh24:mi:ss') || chr(13) ||         
            '2. SR정보 : ' || :NEW.cc_srid || ' [' || :NEW.cc_title || '] '  || chr(13) ||                     
            '3. SR내용 : ' || :NEW.cc_comment || Chr(13) ||    
            '     개발완료 되었습니다.' || chr(13) ||  
            '     SR확인 후 적용요청 하시기 바랍니다.',  
            '     SR개발완료 알림메세지','',CHECK_NOTICD('01'));       
    END IF;   
                      
End CMC0100_Trg;