-- GENERATED BY QueryOne AT 2021-03-04 14:17:53
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.CHG_DIRPATH
(SYSCD varchar2,
SVRCD varchar2,
SEQNO INTEGER,
SVRIP varchar2,
SVRPORT INTEGER,
RSRCCD varchar2,
DIRPATH varchar2,
RSRCNAME varchar2)
return VARCHAR2
IS
    V_DEVHOME   VARCHAR2(100);
    V_PRODHOME  VARCHAR2(100);
    V_DIRPATH   VARCHAR2(200);
    V_SEQNO     INTEGER;
    VCNT        INTEGER;

BEGIN
      IF SEQNO = 0 THEN
          BEGIN
              SELECT MIN(CM_SEQNO)
                INTO V_SEQNO
                FROM CMM0031
               WHERE CM_SYSCD=SYSCD
                 AND CM_SVRCD=SVRCD
                 AND CM_SVRIP=SVRIP
                 AND CM_PORTNO=SVRPORT
                 AND CM_CLOSEDT IS NULL;
              EXCEPTION
                 WHEN  NO_DATA_FOUND  Then
                      V_SEQNO := 0;
          END;

      ELSE
          V_SEQNO := SEQNO;
      END IF;

      SELECT  COUNT(*)
        INTO  VCNT
        FROM  CMM0031 A,CMM0038 B,CMM0030 C
       WHERE  C.CM_SYSCD=SYSCD
         AND  C.CM_SYSCD=A.CM_SYSCD
         AND  A.CM_CLOSEDT IS NULL
         AND  A.CM_SVRCD=NVL(C.CM_DIRBASE,'01')
         AND  A.CM_SYSCD=B.CM_SYSCD
         AND  A.CM_SVRCD=B.CM_SVRCD
         AND  A.cm_seqno=B.cm_seqno
         AND  B.CM_RSRCCD=RSRCCD;

      IF VCNT = 1 THEN
          BEGIN
              SELECT  NVL(B.CM_VOLPATH,'/')
                INTO  V_DEVHOME
                FROM  CMM0031 A,CMM0038 B,CMM0030 C
               WHERE  C.CM_SYSCD=SYSCD
                 AND  C.CM_SYSCD=A.CM_SYSCD
                 AND  A.CM_CLOSEDT IS NULL
                 AND  A.CM_SVRCD=NVL(C.CM_DIRBASE,'01')
                 AND  A.CM_SYSCD=B.CM_SYSCD
                 AND  A.CM_SVRCD=B.CM_SVRCD
                 AND  A.cm_seqno=B.cm_seqno
                 AND  B.CM_RSRCCD=RSRCCD;
              EXCEPTION
                 WHEN  NO_DATA_FOUND  Then
                      RETURN DIRPATH;
          END;
      ELSIF VCNT > 1 THEN
          BEGIN
              SELECT  NVL(B.CM_VOLPATH,'/')
                INTO  V_DEVHOME
                FROM  CMM0031 A,CMM0038 B,CMM0030 C
               WHERE  C.CM_SYSCD=SYSCD
                 AND  C.CM_SYSCD=A.CM_SYSCD
                 AND  A.CM_CLOSEDT IS NULL
                 AND  A.CM_SVRCD=NVL(C.CM_DIRBASE,'01')
                 AND  A.CM_SYSCD=B.CM_SYSCD
                 AND  A.CM_SVRCD=B.CM_SVRCD
                 AND  A.cm_seqno=B.cm_seqno
                 AND  B.CM_RSRCCD=RSRCCD
                 AND  NVL(A.CM_CMPSVR,'N')='Y'
                 AND  ROWNUM=1;
              EXCEPTION
                 WHEN  NO_DATA_FOUND  Then
                      RETURN DIRPATH;
          END;
      ELSE
         RETURN DIRPATH;
      END IF;
      BEGIN
          SELECT  NVL(B.CM_VOLPATH,'/')
            INTO  V_PRODHOME
            FROM  CMM0031 A,CMM0038 B
           WHERE  A.CM_SYSCD=SYSCD
             AND  A.CM_SVRCD=SVRCD
             AND  A.CM_SEQNO=V_SEQNO
             AND  A.CM_SVRIP=SVRIP
             AND  A.CM_CLOSEDT IS NULL
             AND  A.CM_SYSCD=B.CM_SYSCD
             AND  A.CM_SVRCD=B.CM_SVRCD
             AND  A.cm_seqno=B.cm_seqno
             AND  B.CM_RSRCCD=RSRCCD;
          EXCEPTION
             WHEN  NO_DATA_FOUND  Then
                  RETURN DIRPATH;
    END;

    IF V_DEVHOME = V_PRODHOME THEN
       RETURN DIRPATH;
    END IF;

    IF SUBSTR(DIRPATH,1,LENGTH(V_DEVHOME)) = V_DEVHOME THEN
       IF V_DEVHOME = DIRPATH THEN
          V_DIRPATH := V_PRODHOME;
       ELSE
          V_DIRPATH := V_PRODHOME || SUBSTR(DIRPATH,LENGTH(V_DEVHOME)+1);
       END IF;
    ELSE
       V_DIRPATH := DIRPATH;
    END IF;

    return V_DIRPATH;

END ;