-- GENERATED BY QueryOne AT 2021-03-04 14:17:58
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.RUNCHECK_UNIT
(AcptNo IN VARCHAR2,SERNO IN NUMBER,PrcSys IN VARCHAR2,PASSOK IN VARCHAR,CMINFO
IN VARCHAR2,

    SYSCD IN VARCHAR2, SVRCD IN VARCHAR, SEQNO IN NUMBER)
RETURN NUMBER
IS
    CNTVAL NUMBER := 0;
    SYSINFO VARCHAR2(10);
    SVPRCSYS VARCHAR2(10);

-- 리턴값 0:처리 1:미처리
BEGIN
    return 0;
    IF substr(AcptNo,5,2) <> '04' AND substr(AcptNo,5,2) <> '16' THEN
        return 0;
    END IF;

    IF PrcSys not in ('SYSUA','SYSGB','SYSED','SYSRC') THEN
        return 0;
    END IF;

    SVPRCSYS := PrcSys;

    SELECT CM_SYSINFO
    INTO SYSINFO
    FROM CMM0030
    WHERE CM_SYSCD = SYSCD;

   IF PASSOK = '0' AND SUBSTR(SYSINFO,6,1) = '1' AND SUBSTR(CMINFO,55,1) = '1' THEN
      -- 일반적용,정기배포사용,전신청건대상중복제거
--        SELECT count(*)
--        INTO CNTVAL
--        FROM CMR1060
--        WHERE CR_ACPTNO = AcptNo
--        AND   CR_SERNO  = SERNO
--        AND   CR_SVRCD  = SVRCD
--        AND   CR_SEQNO  = SEQNO
--        AND   CR_PRCSYS = SVPRCSYS;


        IF CNTVAL > 0 THEN
            return 0;
        ELSE
            return 1;
        END IF;
    ELSE
        return 0;
    END IF;
end;