-- GENERATED BY QueryOne AT 2021-03-04 14:18:52
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.GYUL_CHECK
(
 Call_Key_AcptNo       IN   Varchar2,
 SV_UserID             IN   Varchar2,
 RETVAL                OUT  NUMBER)
 IS
 ErrSw              Varchar2 (01);
 Sv_SignPos         Varchar2 (10);
 Sv_NxtSign         Varchar2 (10);
 Sv_NxtPosition     Varchar2 (4);
 Sv_NxtConCd        Varchar2 (1);
 Sv_DaeSw           Varchar2 (10);
 FindSw             Varchar2 (01);
 Wk_NxtConCd        Varchar2 (20);
 Wk_NxtSign         Varchar2 (20);
 Sv_Gubun           Varchar2 (02);
 WkBaseUsr          Varchar2 (20);
 SV_DaeUsr          Varchar2 (10);
 WKNext             Varchar2 (10);
 WK_User            Varchar2 (100);
 CNT                INTEGER;
CURSOR  DaeUsr  IS
     Select CM_UserID
       From CMM0042
      Where CM_DaeUsr=SV_UserID
        And CM_BlkSeq=9999
        And CM_BlkStDate<=SYSDATE
        And CM_BlkEdDate>=SYSDATE;
CURSOR  Conf1 IS
     Select  a.CR_Team, a.CR_TeamCD,a.CR_Locat,a.CR_BaseUsr,a.CR_SgnGbn              
       From  CMR9900 a,CMM0043 c,CMR1000 B              
      Where  a.CR_AcptNo = Call_Key_AcptNo              
        And  a.CR_Status = '0'         
        And  a.Cr_TeamCd not in ('1','2','3','6','7','8','P')              
        And  instr(a.CR_Team,c.cm_RgtCd)>0              
        And  c.CM_UserId=SV_UserID              
        And  CR_Locat >= (Select  SUBSTR(CR_ConfUsr, 1, 2)              
                            From  CMR9900              
                           Where  CR_AcptNo = Call_Key_AcptNo              
                             And  CR_Locat  = '00')              
        And  CR_Locat <= (Select  SUBSTR(CR_ConfUsr, 3,2)              
                            From  CMR9900              
                           Where  CR_AcptNo = Call_Key_AcptNo              
                             And  CR_Locat  = '00')    
        AND A.CR_ACPTNO=B.CR_ACPTNO 
        AND B.CR_SYSCD=DECODE(C.CM_RGTCD,'57',(SELECT DISTINCT CM_SYSCD 
                                                 FROM CMM0044 
                                                WHERE CM_SYSCD=B.CR_SYSCD 
                                                  AND CM_USERID=SV_UserID 
                                                  AND CM_CLOSEDT IS NULL), 
                                              B.CR_SYSCD) 
       group by a.CR_Team, a.CR_TeamCD,a.CR_Locat,a.CR_BaseUsr,a.CR_SgnGbn   
       Order by a.Cr_Locat;
Begin
    ErrSw          := NULL;
    Sv_NxtSign     := '';
    Sv_NxtPosition := NULL;
    Sv_SignPos     := '';
    Sv_NxtConCd    := '';
    WkBaseUsr      := '';
    SV_DaeSw := '0';
    RETVAL := 0;

    -- SV_NxtConCD Setting
    -- CR_TeamCD  결재구분
    --    1:자동처리,2:본인확인,3:팀내책임자,4:특정팀,5:처리팀,6:팀내책임자2
    --    7:관리자,8:관련팀참조,9:관련팀승인
    IF SUBSTR(Call_Key_AcptNo,5,2) < '30' THEN
        Begin
          Select  a.CR_TeamCD,a.CR_TEAM
            Into  SV_NxtConCD,Wk_NxtSign
            From  CMR9900 a,CMR1000 b
           Where  a.CR_AcptNo = Call_Key_AcptNo
             And  a.CR_LOCAT='00'
             And  a.CR_AcptNo = b.CR_AcptNo;
          EXCEPTION
              WHEN NO_DATA_FOUND Then
              RETVAL := 3;    -- 결재 정보가 없을때...
        End;
    ELSE
        Begin
          Select  a.CR_TeamCD,a.CR_TEAM
            Into  SV_NxtConCD,Wk_NxtSign
            From  CMR9900 a,CMC0300 b
           Where  a.CR_AcptNo = Call_Key_AcptNo
             And  a.CR_LOCAT='00'
             And  a.CR_AcptNo = b.CC_AcptNo;
          EXCEPTION
              WHEN NO_DATA_FOUND Then
              RETVAL := 3;    -- 결재 정보가 없을때...
        End;
    END IF;
    FindSw := '0';

    -- 기본 Sv값 Setting
    IF SV_NxtConCD = '1' OR SV_NxtConCD = '2' OR SV_NxtConCD = '3' OR SV_NxtConCD = '6' OR SV_NxtConCd = '7' OR SV_NxtConCd = '8' OR SV_NxtConCd = 'P' THEN
       Begin
         Select  rtrim(CR_Team), CR_TeamCD,   CR_Locat     , CR_TeamCD, rtrim(CR_BaseUsr)
           Into  SV_NxtSign,     SV_NxtConCD, SV_NxtPosition, SV_Gubun , WkBaseUsr
           From  CMR9900
          Where  CR_AcptNo = Call_Key_AcptNo
            And  CR_Team   = SV_UserID
            And  CR_Status = '0'
            And  CR_Locat >= (Select  SUBSTR(CR_ConfUsr, 1, 2)
                                From  CMR9900
                               Where  CR_AcptNo = Call_Key_AcptNo
                                 And  CR_Locat  = '00')
            And  CR_Locat <= (Select  SUBSTR(CR_ConfUsr, 3, 2)
                                From  CMR9900
                               Where  CR_AcptNo = Call_Key_AcptNo
                                 And  CR_Locat  = '00');
         EXCEPTION
            WHEN NO_DATA_FOUND Then
		    RETVAL := 1;  -- 정당한 결재자가 아닐때
       End;

       -- 대결재자 Check
       IF WkBaseUsr != SV_NxtSign Then
          SV_DaeSw := '1';
          FindSw := '1';
       End If;
    ELSE
       -- Sv_NxtConCd = '1' 은 자동처리
       dbms_OUTPUT.PUT_LINE('SV_NxtConCD ' || SV_NxtConCD);
       For Usr2 In Conf1  Loop
           SV_NxtPosition := Usr2.CR_Locat;
           dbms_OUTPUT.PUT_LINE('SV_NxtPosition ' || SV_NxtPosition);
           Exit;
       End Loop;
       IF SV_NxtPosition IS NUll THEN
          Wk_User := '';
          For Usr In DaeUsr Loop
              IF Wk_User <> '' THEN
                 Wk_User := Wk_User || ',';
              END IF;
              Wk_User := Wk_User || rtrim(Usr.CM_UserID);
          End Loop;
          dbms_OUTPUT.PUT_LINE('Wk_User ' || Wk_User);
          For Usr In Conf1 Loop
              SV_NxtPosition := Usr.CR_Locat;
           dbms_OUTPUT.PUT_LINE('SV_NxtPosition 2 ' || SV_NxtPosition);
              Exit;
          End Loop;
       END IF;

       IF SV_NxtPosition IS NUll THEN
		  RETVAL := 1;
       END IF;

    END IF;

End GYUL_CHECK;