-- GENERATED BY QueryOne AT 2021-03-04 14:18:50
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.CMR9900_STR    
(                            
 Call_Key_AcptNo       IN   Varchar2,                            
 SV_UserID             IN   Varchar2,                            
 SV_SGNMSG             IN   Varchar2,                            
 Sv_SgnCd              IN   Varchar2,                            
 Sv_ReqCd              IN   Varchar2,                            
 Sv_CnclSw             IN   Varchar2)                            
 IS                            
 ErrSw              Varchar2 (01);                            
 Sv_SignPos         Varchar2 (100);                            
 Sv_NxtSign         Varchar2 (10);                            
 Sv_NxtPosition     Varchar2 (4);                            
 Sv_NxtConCd        Varchar2 (1);                            
 Sv_LastStatus      Varchar2 (03);                   
 Sv_SysCd           Varchar2 (05);                 
 Sv_Status          Varchar2 (02);                            
 Sv_DaeSw           Varchar2 (10);                            
 FindSw             Varchar2 (01);                            
 Wk_NxtConCd        Varchar2 (20);                            
 Wk_NxtSign         Varchar2 (20);                            
 Sv_Gubun           Varchar2 (02);                            
 SV_ListSw          Varchar2 (01);                            
 SV_PrcSw           Varchar2 (01);                            
 WkBaseUsr          Varchar2 (20);                            
 SV_DaeUsr          Varchar2 (10);                            
 WKNext             Varchar2 (10);                            
 BefCnt             Number (04) := 0;                            
 Sv_ConfNO          Varchar2 (12);                            
 Wk_ConfNo          Varchar2(12);                             
 WkA                Varchar2(10);                            
 Wk_Auto            Varchar2(10);                            
 WkB                Varchar2(20);                            
 WkC                Varchar2(12);                            
 InsFg              Varchar2(1);                            
 WkPos              Varchar2(3);                            
 I                  Number   (04) := 0;                            
 WK_Status          Varchar2 (02);                            
 SV_Cnt             Number        := 0;                            
 WK_PassOK          Varchar2 (10);                            
 WK_User            Varchar2 (100);                            
 Wk_CnclSw          Varchar2 (1);                            
 Wk_QaSw            Varchar2 (1);                            
 STIME1_S           Varchar2 (4);                            
 STIME1_E           Varchar2 (4);                            
 STIME2_S           Varchar2 (4);                            
 STIME2_E           Varchar2 (4);                            
 STIME3_S           Varchar2 (4);                            
 STIME3_E           Varchar2 (4);                            
 WEEKCD             Varchar2 (1);                            
 NOWTIME            Varchar2 (4);                            
 HOLICNT            Number := 0;                            
 CnclEdCnt          Number := 0;                                                            
 CnclCbCnt          Number := 0;                           
 CnclRkCnt          Number := 0;                          
 HoliSw1            Boolean;                        
 HoliSw2            Boolean;               
 SKIPSW             Boolean;                         
 TimeCd             Varchar2 (2);                         
 Sv_ITSMID          Varchar2 (20);         
 SV_EDITOR          Varchar2 (10);         
 Sv_PassOk          Varchar2 (1);   
 SV_ECLIPSE         Varchar2 (1);   
 SV_VERSION         Varchar2 (1);   
 SV_SRID            VARCHAR2 (20); 
 SV_ERRYN           CHAR(1);                                     
 CCSTA              VARCHAR2 (2);                                
 SVCCSTA            VARCHAR2 (2);                 
 SV_CONFNAME        VARCHAR2 (50);           
 Wk_VerManage       Varchar2 (1);   
 
 SV_DEMDYR          VARCHAR2 (4); 
 SV_SRNO            Number := 0; 
 
 
CURSOR  DaeUsr  IS                            
     Select CM_UserID                            
       From CMM0042                            
      Where CM_DaeUsr=SV_UserID                            
        And CM_BlkSeq=9999                            
        And CM_BlkStDate<=SYSDATE                            
        And CM_BlkEdDate>=SYSDATE;                            
CURSOR  Conf1 IS                            
     Select  a.CR_Team, a.CR_TeamCD,a.CR_Locat,a.CR_BaseUsr,a.CR_SgnGbn                            
       From  CMR9900 a,CMM0043 c                            
      Where  a.CR_AcptNo = Call_Key_AcptNo                            
        And  a.CR_Status = '0'                            
        And  a.CR_locat <> '00'                            
        And  a.Cr_TeamCd not in ('1','2','3','6','7','B')                            
        And  instr(a.CR_Team,c.cm_RgtCd)>0                            
        And  c.CM_UserId=SV_UserID                            
        And  CR_Locat >= (Select  SUBSTR(CR_ConfUsr, 1, 2)                            
                            From  CMR9900                            
                           Where  CR_AcptNo = Call_Key_AcptNo                            
                             And  CR_Locat  = '00')                            
        And  CR_Locat <= (Select  SUBSTR(CR_ConfUsr, 3,2)                            
                            From  CMR9900                            
                           Where  CR_AcptNo = Call_Key_AcptNo                            
                             And  CR_Locat  = '00')          
       group by a.CR_Team, a.CR_TeamCD,a.CR_Locat,a.CR_BaseUsr,a.CR_SgnGbn          
       Order by Cr_Locat;                               
CURSOR  POS    IS                            
     Select  cr_team, cr_locat, cr_teamcd, cr_sgngbn, cr_congbn                            
       From  CMR9900                            
      Where  CR_acptno = Call_Key_AcptNo                            
        and  cr_locat <> '00'                            
        and  CR_status = '0'                            
        --and  CR_congbn in ('2','3','5') 
        and  CR_congbn in ('2','3','5') 
      order  by CR_locat;                            
CURSOR  LOC    IS                            
     Select  cr_locat, cr_teamcd                            
       From  CMR9900                            
      Where  CR_acptno = Call_Key_AcptNo                            
        and  CR_Locat >= SV_NxtPosition                            
        and  cr_locat <> '00'                            
        and  CR_status = '0'                            
      order  by CR_locat;                              
CURSOR  LOC_AUTO    IS                            
     Select  CR_LOCAT, CR_TEAMCD, CR_TEAM                            
       From  CMR9900                            
      Where  CR_acptno = Call_Key_AcptNo                            
        and  CR_Locat > SV_NxtPosition                            
        and  cr_locat <> '00'                            
        and  CR_status = '0'                            
      order  by CR_locat;                                    
CURSOR  MSG    IS                            
     Select  cr_sgngbn, cr_team                            
       From  CMR9900                            
      Where  CR_acptno = WkC                            
        and  CR_Locat<>'00'                            
        and  CR_status = '9'                            
      order  by CR_team,cr_sgngbn;                                                                     
CURSOR  SYSPROC IS                                                        
     Select  CR_TEAM                                                     
       From  CMR9900                                                           
      Where  CR_acptno = Call_Key_AcptNo                                                           
        and  CR_Locat<>'00'                                                           
        and  CR_status='0'                                                           
      order  by CR_LOCAT;                                    
Begin                         
    Sv_LastStatus := NULL;                              
    Sv_NxtSign     := '';                    
                          
                                  
    Sv_Status := '0';                            
    I := 0;                            
    ErrSw          := NULL;                          
    Sv_NxtPosition := '';                            
    Sv_SignPos     := '';                            
    Sv_NxtConCd    := '';                            
    WkBaseUsr      := '';                            
    SV_DaeSw := '0';                            
    Wk_QaSw  := '0';                            
    Wk_CnclSw := Sv_CnclSw;    
    SV_SRID   := ''; 
    SV_DEMDYR := '';
    SV_SRNO   := '0';
         
    IF SUBSTR(Call_Key_AcptNo,5,2)<'30' THEN 
        Begin                            
            Select  a.Cr_status,a.cr_syscd,b.cr_team,A.CR_EDITOR,A.CR_PASSOK,NVL(A.CR_ECLIPSE,'R'),A.CR_ITSMID,NVL(A.CR_VERSION,'Y'),SUBSTR(C.CM_SYSINFO,12,1)                        
              Into  Sv_LastStatus,Sv_SysCd,Sv_NxtSign,SV_EDITOR, Sv_PassOk, SV_ECLIPSE,SV_SRID,SV_VERSION,SV_ERRYN                             
              From  CMR1000 a,CMR9900 b,CMM0030 c                            
             Where  a.Cr_acptno = Call_Key_AcptNo                          
               And  a.cr_acptno=b.cr_acptno                
               And  b.cr_locat='00' 
               AND  a.CR_SYSCD = c.CM_SYSCD;                               
            EXCEPTION                            
               WHEN  NO_DATA_FOUND  Then                            
                  Sv_LastStatus := NULL;                         
        End;  
    ELSE 
        Begin                            
            Select  a.CC_status,'99999',b.cr_team,A.CC_EDITOR,'0','R',A.CC_SRID,'N'                        
              Into  Sv_LastStatus,Sv_SysCd,Sv_NxtSign,SV_EDITOR, Sv_PassOk, SV_ECLIPSE,SV_SRID,SV_VERSION                             
              From  CMC0300 a,CMR9900 b                            
             Where  a.CC_acptno = Call_Key_AcptNo                          
               And  a.cC_acptno=b.cr_acptno                
               And  b.cr_locat='00';                               
            EXCEPTION                            
               WHEN  NO_DATA_FOUND  Then                            
                  Sv_LastStatus := NULL;                         
        End;  
    END IF; 
    IF Wk_CnclSw = '9' THEN  -- 취소                          
       IF Sv_ReqCd != '' THEN                            
           Begin                            
             Select  Count(*)                            
               Into  SV_Cnt                            
               From  CMR9900                            
              Where  CR_AcptNo = Call_Key_AcptNo                            
                And  CR_LOCAT='00'                            
                And  to_number(substr(CR_ConfUsr,1,2))<=to_number(Sv_ReqCd)                
                and  to_number(substr(CR_ConfUsr,3,2))>=to_number(Sv_ReqCd);                            
                  EXCEPTION                            
                     WHEN  NO_DATA_FOUND  Then                            
                          SV_Cnt := 0;                            
           End;                            
           IF SV_Cnt IS NULL Then                            
              SV_Cnt := 0;                            
           End If;                   
           Sv_NxtPosition := Sv_ReqCd;                
           If  SV_Cnt > 0 Then                            
               Raise_Application_Error (-20021,'취소가능한 결재단계가 아닙니다.');                            
           End If;                       
       ELSE                           
           Begin                            
             Select  SUBSTR(CR_ConfUsr,1,2)                            
               Into  SV_NxtPosition                            
               From  CMR9900                            
              Where  CR_AcptNo = Call_Key_AcptNo                            
                And  CR_LOCAT='00';                            
           End;                 
       END IF;                            
      dbms_OUTPUT.PUT_LINE('237 Line SV_NxtPosition' || SV_NxtPosition );                         
       IF SV_NxtPosition = '' THEN                            
          SV_NxtPosition := '00';                            
       END IF;                            
       IF SV_NxtPosition IS NULL THEN                            
          SV_NxtPosition := '00';                            
       END IF;                            
       dbms_OUTPUT.PUT_LINE('255 Line SV_NxtPosition=' || SV_NxtPosition);                         
       Begin                            
         Select  rtrim(CR_Team), CR_TeamCD,   CR_Locat     ,  CR_TeamCD, CR_BaseUsr, CR_PrcSw                            
           Into  SV_NxtSign,     SV_NxtConCD, SV_NxtPosition, SV_Gubun , WkBaseUsr, SV_PrcSw                            
           From  CMR9900                            
          Where  CR_AcptNo = Call_Key_AcptNo                            
            And  CR_LOCAT  = SV_NxtPosition;                            
         EXCEPTION                            
             WHEN NO_DATA_FOUND Then                            
                Raise_Application_Error (-20010,'결재정보가 없습니다.');                            
       End;                    
       Wk_NxtSign := SV_NxtSign;                  
    END IF;                         
    -- 취소END                  
    IF SV_UserID != '000000' AND Wk_CnclSw <>'9' Then                            
       Begin                            
         Select  rtrim(CR_Team), CR_TeamCD,   CR_Locat     ,  CR_TeamCD, CR_BaseUsr, CR_PrcSw                            
           Into  SV_NxtSign,     SV_NxtConCD, SV_NxtPosition, SV_Gubun , WkBaseUsr, SV_PrcSw                            
           From  CMR9900                            
          Where  CR_AcptNo = Call_Key_AcptNo                            
            And  CR_LOCAT='00';                            
         EXCEPTION                            
             WHEN NO_DATA_FOUND Then                            
                Raise_Application_Error (-20010,'결재정보가 없습니다.');                            
       End;                            
       FindSw := '0';                            
       Wk_NxtSign := SV_NxtSign;                  
                         
    -- SV_NxtConCD Setting                            
    -- CR_TeamCD  결재구분                            
    --    1:자동처리,2:본인확인,3:팀내책임자,4:특정팀,5:처리팀,6:팀내책임자2                            
    --    7:관리자,8:관련팀참조,9:관련팀승인                            
       dbms_OUTPUT.PUT_LINE('278 Line SV_NxtConCD=' || SV_NxtConCD || ' SV_NxtSign=' || SV_NxtSign);                    
                                   
       IF SV_NxtConCD = '1' OR SV_NxtConCD = '2' OR SV_NxtConCD = '3' OR SV_NxtConCD = '6' OR SV_NxtConCD = '7' OR SV_NxtConCD = '8'  OR SV_NxtConCD = 'P' THEN                            
          Begin                            
            Select  rtrim(CR_Team), CR_TeamCD,   CR_Locat     , CR_TeamCD,  CR_BaseUsr, CR_PrcSw                            
              Into  SV_NxtSign,     SV_NxtConCD, SV_NxtPosition, SV_Gubun , WkBaseUsr, SV_PrcSw                            
              From  CMR9900                            
             Where  CR_AcptNo = Call_Key_AcptNo                            
               And  CR_Team   = SV_UserID                            
               And  CR_Status = '0'                            
               And  CR_Locat  <> '00'                            
               And  CR_Locat >= (Select  SUBSTR(CR_ConfUsr, 1, 2)                            
                                   From  CMR9900                            
                                  Where  CR_AcptNo = Call_Key_AcptNo                            
                                    And  CR_Locat  = '00')                            
               And  CR_Locat <= (Select  SUBSTR(CR_ConfUsr, 3, 2)                            
                                   From  CMR9900                            
                                  Where  CR_AcptNo = Call_Key_AcptNo                            
                                    And  CR_Locat  = '00');                            
            EXCEPTION                            
               WHEN NO_DATA_FOUND Then                            
                Raise_Application_Error (-20011,'정당한 결재자가 아닙니다.');                            
          End;                            
                            
          IF WkBaseUsr != SV_NxtSign Then                            
             SV_DaeSw := '1';                            
             FindSw := '1';                            
          End If;                            
       ELSE                            
          For Usr2 In Conf1  Loop                            
              SV_NxtSign := Usr2.CR_Team;                            
              SV_NxtConCd := Usr2.CR_TeamCD;                            
              SV_NxtPosition := Usr2.CR_Locat;                            
              SV_Gubun := Usr2.CR_TeamCD;                            
              WkBaseUsr := Usr2.CR_BaseUsr;                            
              dbms_OUTPUT.PUT_LINE('Sv_NxtSign-1 ' || Sv_NxtSign);                            
              Exit;                            
          End Loop;                            
          dbms_OUTPUT.PUT_LINE('Sv_NxtPosition-1 ' || Sv_NxtPosition);                            
          IF SV_NxtPosition = '' THEN                            
             Raise_Application_Error (-20012,'정당한 결재자가 아닙니다.');                            
          END IF;                            
       END IF;                            
       WKNext := SV_NxtPosition;                            
       If Wk_CnclSw != '3' Then                            
       	  WK_Status := '9';                            
       Else                            
          WK_Status := '3';                            
       End If;                            
       Wk_NxtConCd := SV_NxtConCd;                            
                            
       dbms_OUTPUT.PUT_LINE('WK_Status111 ' || WK_Status);                            
       dbms_OUTPUT.PUT_LINE('Sv_NxtPosition ' || Sv_NxtPosition);                            
                            
       IF TO_NUMBER(Sv_NxtPosition) = 0 THEN                            
          Raise_Application_Error (-20012,'정당한 결재자가 아닙니다.');                            
       END IF; 
                 
       UPDate  CMR9900                            
          Set  CR_Status = WK_Status,                            
               CR_ConfUsr = SV_UserID,                            
               CR_ConMsg  = SV_SGNMSG,                            
               CR_ConfDate = SYSDATE                            
        Where  CR_AcptNo = Call_Key_AcptNo                            
          And  TO_NUMBER(CR_locat) = TO_NUMBER(Sv_NxtPosition);   
       
       IF SV_SRID IS NOT NULL THEN 
          -- 버전관리 자원코드 SR 상태 변경 시작      
          IF SUBSTR(Call_Key_AcptNo,5,2) = '04' THEN      
             BEGIN                                                 
              Select  Count(*)                                                           
                Into  Wk_VerManage                                                           
                From  CMR9900 a                                                       
               Where  A.CR_AcptNo = Call_Key_AcptNo                                                    
                 AND  A.CR_TEAM in('SYSCB','SYSED');                                                           
              EXCEPTION                                                           
                  WHEN NO_DATA_FOUND Then                                                           
                  Wk_VerManage := 0;                                                           
             END;   
          END IF;           
                
          IF Wk_VerManage = 0 THEN        
             BEGIN                                                 
              Select  Count(*)                                                           
                Into  Wk_VerManage                                                           
                From  CMR9900 a                                                       
               Where  A.CR_AcptNo = Call_Key_AcptNo                                                    
                 AND  A.CR_LOCAT <> '00'                                                       
                 AND  A.CR_STATUS ='0';      
              EXCEPTION                                                           
                  WHEN NO_DATA_FOUND Then                                                           
                  Wk_VerManage := 0;                                                           
             END;                     
      
             IF Wk_VerManage = 1 THEN                              
                 UPDATE CMC0100                              
                   SET CC_STATUS='4'          
                      ,CC_PROCMSG='SR완료처리'           
                      ,CC_ENDDT=sysdate         
                 WHERE CC_SRID=SV_SRID;            
             END IF;      
              -- 버전관리 자원코드 SR 상태 변경 종료                   
          END IF;             
       END IF;
        
       --일괄등록의 경우 형상관리저장까지만 갈때 빌드서버체크인 건에 대한 버전 UPDATE      
       IF SUBSTR(Call_Key_AcptNo,5,2) = '16' AND SV_NxtConCD = '1' AND SV_NxtSign = 'SYSPF' THEN      
          BEGIN      
              SELECT COUNT(*)      
                INTO SV_Cnt      
                FROM CMR9900      
               WHERE CR_ACPTNO=Call_Key_AcptNo      
                 AND CR_TEAMCD='1'      
                 AND CR_LOCAT<>'00'      
                 AND CR_TEAM NOT IN ('SYSPF','SYSUP');                          
                  EXCEPTION                            
                     WHEN  NO_DATA_FOUND  Then                            
                          SV_Cnt := 0;        
          END;      
                
          IF SV_Cnt = 0 THEN      
             UPDATE CMR1010      
                SET CR_VERSION=0      
              WHERE CR_ACPTNO=Call_Key_AcptNo      
                AND CR_RSRCCD IN (SELECT CM_RSRCCD FROM CMM0036      
                                   WHERE CM_SYSCD=Sv_SysCd      
                                     AND SUBSTR(CM_INFO,25,1)='1');      
          END IF;      
       END IF; 
       
       Select  TRIM(CR_ConfUsr)                            
         Into  WKNext                            
         From  CMR9900                            
        Where  CR_AcptNo = Call_Key_AcptNo                            
          And  CR_Locat   = '00';                            
    ElsIF SV_UserID = '000000' THEN   --처음                   
       SV_Gubun := '1';                            
       WKNext   := '99';            
       SV_NxtPosition := '00';          
       SKIPSW := FALSE;    
               
       IF SUBSTR(Call_Key_AcptNo,5,2) = '04' AND Sv_PassOk = '0' THEN   
          SELECT COUNT(*)          
            INTO SV_Cnt          
            FROM CMM0030        
           WHERE CM_SYSCD=Sv_SysCd   
             AND SUBSTR(CM_SYSINFO,6,1)='1';          
                  
           IF SV_Cnt > 0 THEN     
              UPDATE CMR1000   
                 SET CR_PRCTIME=(SELECT CM_SYSTIME FROM CMM0030   
                                  WHERE CM_SYSCD=Sv_SysCd)   
              WHERE CR_ACPTNO=Call_Key_AcptNo;   
           END IF;  
       ELSIF SUBSTR(Call_Key_AcptNo,5,2) = '69' THEN 
          SELECT COUNT(*) 
            INTO SV_Cnt 
            FROM CMR9900 
           WHERE CR_ACPTNO=Call_Key_AcptNo 
             AND CR_LOCAT<>'00' 
             AND CR_CONGBN IN ('2','3'); 
          IF SV_Cnt = 0 THEN 
             UPDATE CMC0100 
                SET CC_STATUS='9' 
                   ,CC_COMPDATE=SYSDATE 
              WHERE CC_SRID=SV_SRID; 
          END IF; 
       END IF;   
        
       --결재자가 부재중이고 대결지정이 없는 경우 후결로 되도록 수정 
       UPDATE CMR9900 
          SET CR_CONGBN='5' 
        WHERE CR_ACPTNO=Call_Key_AcptNo 
          AND CR_LOCAT IN ( 
               SELECT A.CR_LOCAT 
                 FROM CMR9900 A,CMM0040 B 
                WHERE A.CR_ACPTNO=Call_Key_AcptNo 
                  AND A.CR_LOCAT<>'00' 
                  AND A.CR_TEAMCD IN ('3','6') 
                  AND A.CR_TEAM=B.CM_USERID 
                  AND NVL(B.CM_BLANKDTS,TO_CHAR(SYSDATE+1,'YYYYMMDD'))<=TO_CHAR(SYSDATE,'YYYYMMDD') 
                  AND NVL(B.CM_BLANKDTE,TO_CHAR(SYSDATE-1,'YYYYMMDD'))>=TO_CHAR(SYSDATE,'YYYYMMDD') 
                  AND B.CM_DAEGYUL IS NULL 
                  AND A.CR_CONGBN<>'5' 
                  AND A.CR_BLANK IN ('4','6')); 
                   
       For Usr3 In LOC_AUTO  Loop             
          IF Usr3.CR_TEAMCD = '3' OR Usr3.CR_TEAMCD = 'P' THEN          
             SKIPSW := TRUE;          
             IF Usr3.CR_TEAM = SV_EDITOR THEN          
                SV_Cnt := 0;          
                SELECT COUNT(*)          
                  INTO SV_Cnt          
                  FROM CMR9900          
                 WHERE CR_ACPTNO = Call_Key_AcptNo           
                   AND CR_LOCAT NOT IN ('00',Usr3.CR_LOCAT)          
                   AND CR_STATUS = '0';          
                          
                IF SV_Cnt > 0 THEN          
                    UPDate  CMR9900                            
                       Set  CR_Status = '9',                            
                            CR_ConfUsr = SV_UserID,                            
                            CR_ConMsg  = '자동결재(요청자권한)',                            
                            CR_ConfDate = SYSDATE                            
                     Where  CR_AcptNo = Call_Key_AcptNo                            
                       And  TO_NUMBER(CR_locat) = TO_NUMBER(Usr3.CR_LOCAT);            
                              
                    UPDate  CMR9900                            
                       Set  (cr_team , cr_teamcd, cr_sgngbn, cr_congbn, cr_common, cr_blank,                            
                             cr_emger, cr_holi  , cr_orgstep, cr_confusr, cr_confname, cr_prcsw,CR_QRYCD) =                            
                            (select  cr_team , cr_teamcd, cr_sgngbn, cr_congbn, cr_common, cr_blank,                            
                                     cr_emger , cr_holi   , cr_orgstep, SV_NxtPosition, cr_confname, cr_prcsw,CR_QRYCD                            
                               from  cmr9900                            
                              where  cr_acptno = Call_Key_AcptNo                            
                                and  cr_locat = Usr3.CR_LOCAT)                            
                     Where  cr_acptno = Call_Key_AcptNo                            
                       And  cr_locat  = '00';            
                 END IF;          
             ELSE          
                EXIT;          
             END IF;          
          ELSE          
             IF SKIPSW = TRUE THEN          
                EXIT;          
             END IF;          
          END IF;          
       End Loop;          
    End If;        
    
--    IF SV_SRID IS NOT NULL AND SUBSTR(Call_Key_AcptNo,5,2) = '04' THEN                              
--         -- SR상태 UPDATE                              
--         UPDATE CMC0100                              
--            SET CC_STATUS='23'                              
--          WHERE CC_SRID=SV_SRID;                              
--       END IF;                              
--    End If;            
                      
    IF (Wk_CnclSw = '3' OR Wk_CnclSw = '9') THEN               
       IF SUBSTR(Call_Key_AcptNo,5,2) < '30' AND Wk_NxtSign <> 'SYSCED'  THEN             
          UPDATE CMR1000             
             SET CR_CNCLSTEP=Wk_NxtSign,             
                 CR_CNCLLSTD=SYSDATE,             
                 CR_RETRYYN='N'             
           WHERE CR_ACPTNO=Call_Key_AcptNo;                          
       END IF;    
       IF CnclEdCnt > 0 OR  CnclRkCnt > 0 THEN --빌드 및 배포서버 원복                
                          
          IF Wk_CnclSw = '3' THEN                
             Update CMR9900                            
                Set CR_Locat=LPAD(TO_NUMBER(CR_Locat)+3,2,'0')                            
              Where Cr_AcptNo = Call_Key_AcptNo                            
                --And Cr_Status='0'                            
                And Cr_Locat>Sv_NxtPosition;                      
          ELSE                
             Update CMR9900                            
                Set CR_Locat=LPAD(TO_NUMBER(CR_Locat)+3,2,'0')                            
              Where Cr_AcptNo = Call_Key_AcptNo                            
                --And Cr_Status='0'                            
                And Cr_Locat>=Sv_NxtPosition;                 
          END IF;                
          Wk_CnclSw := '1';                
       ELSE   --원복필요없음                  
          SV_LastStatus := '3';                            
          dbms_OUTPUT.PUT_LINE('402Line SV_LastStatus ' || SV_LastStatus);                            
          UPDate  CMR9900                            
             Set  CR_Status = '3'                            
           Where  CR_AcptNo = Call_Key_AcptNo                            
             And  CR_Status = '0';                   
                               
          IF Wk_CnclSw='9' AND substr(Call_Key_AcptNo,5,2) < '30' THEN                   
             UPDate  CMR9900                            
	            Set  CR_BaseUsr = SV_UserID,                            
	                 CR_ConMsg  = SV_SGNMSG,                            
	                 CR_ConfDate = SYSDATE                            
	          Where  CR_AcptNo = Call_Key_AcptNo                            
	            And  CR_Locat = '00';                        
                                
	         Update Cmr1000                            
	            Set Cr_Cncl='1'                            
	          Where Cr_Acptno=Call_Key_AcptNo;                            
	      END IF;                   
       END IF;                  
    END IF;                  
    dbms_OUTPUT.PUT_LINE('422Line SV_LastStatus ' || SV_LastStatus);                    
    IF SV_UserID = '000000' THEN   
                 
       IF SUBSTR(Call_Key_AcptNo,5,2) = '01' OR SUBSTR(Call_Key_AcptNo,5,2) = '02' OR SUBSTR(Call_Key_AcptNo,5,2) = '11' OR        
          SUBSTR(Call_Key_AcptNo,5,2) = '03' OR SUBSTR(Call_Key_AcptNo,5,2) = '04' OR SUBSTR(Call_Key_AcptNo,5,2) = '05' OR 
          SUBSTR(Call_Key_AcptNo,5,2) = '06' OR SUBSTR(Call_Key_AcptNo,5,2) = '07' OR SUBSTR(Call_Key_AcptNo,5,2) = '16'THEN  
          UPDATE CMR9900                            
             SET CR_PrcSw='N'                            
           WHERE CR_Acptno = Call_Key_AcptNo;                            
                            
          UPDATE CMR9900                            
             SET CR_PrcSw='Y'                            
           WHERE CR_Acptno = Call_Key_AcptNo                            
             AND CR_LOCAT<>'00'                            
             AND CR_LOCAT=(SELECT MAX(CR_LOCAT) FROM CMR9900                            
                            WHERE CR_Acptno = Call_Key_AcptNo                            
                              AND CR_Locat<>'00'                            
                              AND CR_Teamcd='1'                            
                              AND CR_Team in ('SYSED','SYSRC','SYSAL','SYSANL','SYSSF'));                            
            Begin                            
              Select  Count(*)                            
                Into  SV_Cnt                            
                From  CMR9900                            
               Where  CR_AcptNo = Call_Key_AcptNo                            
                 And  CR_PrcSw = 'Y'                            
                 And  CR_Locat <> '00';                            
              EXCEPTION                            
                 WHEN  NO_DATA_FOUND  Then                            
                      SV_Cnt := 0;                            
            End;                            
                            
            IF SV_Cnt IS NULL Then                            
               SV_Cnt := 0;                            
            End If;                            
            IF SV_Cnt = 0 THEN                            
               UPDATE CMR9900                            
                  SET CR_PrcSw='Y'                            
                WHERE CR_Acptno = Call_Key_AcptNo                            
                  AND CR_LOCAT<>'00'                            
                  AND CR_LOCAT=(SELECT MAX(CR_LOCAT) FROM CMR9900                            
                                 WHERE CR_Acptno = Call_Key_AcptNo                            
                                   AND CR_Locat<>'00'                            
                                   AND CR_ConGbn='2');                            
            END IF;                         
       END IF;       
    END IF;                            
     dbms_OUTPUT.PUT_LINE('501 Line SV_LastStatus ' || SV_LastStatus);                           
    If (SV_LastStatus = '0' or (Wk_CnclSw != '3' and Wk_CnclSw != '9')) And (SV_SgnCd ='9'  Or  SV_SgnCD = '8') Then                            
       FindSw := '0';        
             
       If SV_Gubun = '9' Then                            
          Begin                            
             Select  Count(*)                            
               Into  SV_Cnt                            
               From  CMR9900                            
              Where  CR_AcptNo = Call_Key_AcptNo                            
                And  CR_Status = '0'                            
                And  CR_Locat >= SUBSTR(WKNext, 1, 2)                            
                And  CR_Locat <= SUBSTR(WKNext, LENGTH(WKNext) - 1, 2);                            
              EXCEPTION                            
                 WHEN  NO_DATA_FOUND  Then                            
                      SV_Cnt := 0;                            
          End;                            
          IF SV_Cnt IS NULL Then                            
             SV_Cnt := 0;                            
          End If;                            
          If  SV_Cnt > 0 Then                            
              ErrSw := '0';                            
          End If;                            
       End If;                            
                            
       if ErrSw IS NULL Then                            
          SV_NxtPosition := NULL;                          
                                  
          SV_Cnt := 0;                        
          WeekCd := 0;                        
          HoliSw1 := FALSE;                        
          HoliSw2 := FALSE;                        
                                  
--          SELECT COUNT(*),to_CHAR(SYSDATE,'D')                        
--            INTO SV_Cnt,WeekCd                        
--            FROM CMM0050                        
--           WHERE CM_HOLIDAY=TO_CHAR(SYSDATE,'YYYYMMDD')                        
--             AND CM_CLOSEDT IS NULL;                                  
--          IF SV_Cnt > 0 OR WeekCd = 1 OR WeekCd = 7 THEN                        
--             HoliSw1 := TRUE;                        
--          ELSE                        
--             IF WeekCd = 6 THEN                        
--                TimeCd := '02';                        
--             ELSE                        
--                TimeCd := '01';                        
--             END IF;                        
--             SELECT COUNT(*)                        
--               INTO SV_Cnt                        
--               FROM CMM0014                        
--              WHERE CM_TIMECD = TimeCd                        
--                AND TO_CHAR(SYSDATE,'HH24MI')>=CM_STTIME                        
--                AND TO_CHAR(SYSDATE,'HH24MI')<=CM_EDTIME;                        
--             IF SV_Cnt = 0 THEN                        
--                HoliSw2 := TRUE;                        
--             END IF;                        
--          END IF;                        
--                                  
--          IF HoliSw1 = FALSE AND HoliSw2 = FALSE THEN                        
--             UPDATE CMR9900                        
--                SET CR_CONGBN = CR_COMMON                        
--              WHERE CR_ACPTNO = Call_Key_AcptNo                        
--                AND CR_STATUS = '0'                        
--                AND CR_LOCAT > SUBSTR(WKNext, 1, 2)                        
--                AND CR_COMMON IN ('2','3')                        
--                AND CR_CONGBN = '4';                        
--          END IF;                        
                                  
          if WKNext = '99' Then                            
             WKNext := '00';                            
          End If;                            
          dbms_OUTPUT.PUT_LINE('WKNext : '|| WKNext);                            
                            
          For  Usr In POS  Loop                            
           dbms_OUTPUT.PUT_LINE('WKNext : ['|| WKNext || ']');                            
         dbms_OUTPUT.PUT_LINE('Usr.CR_TeamCd' || Usr.CR_TeamCd);                            
          dbms_OUTPUT.PUT_LINE('Usr.CR_Locat = ' || Usr.CR_Locat);                            
             IF FindSw = '1' AND Usr.Cr_TeamCD != '8' Then                            
                Exit;                            
             ElsIf Usr.Cr_TeamCd = '1' Or Usr.Cr_TeamCD = '2'  Or Usr.Cr_TeamCd = 'P' Then                              
                SV_NxtSign := Usr.CR_Team;                            
                SV_NxtPosition := Usr.CR_Locat || Usr.CR_Locat;                            
                FindSw := '1';                            
             ElsIf Usr.Cr_TeamCd = '4' OR Usr.Cr_TeamCd = '5'  OR Usr.Cr_TeamCd = '9' Then                            
                SV_NxtSign := Usr.CR_Team;                            
                SV_NxtPosition := Usr.CR_Locat || Usr.CR_Locat;                            
                FindSw := '1';                            
             ElsIf Usr.Cr_TeamCd = '3' Or Usr.Cr_TeamCD = '6' or Usr.Cr_TeamCD = '7' Then                            
                SV_NxtSign := Usr.CR_Team;                            
                SV_NxtPosition := Usr.CR_Locat || Usr.CR_Locat;                            
                SV_SignPos := Usr.CR_SgnGbn;                            
                FindSw := '1';                            
             ElsIf Usr.Cr_TeamCd = '8' Then                            
                IF SV_NxtPosition is NULL THEN                            
                   SV_NxtSign := Usr.CR_Team;                            
                   SV_NxtPosition := Usr.CR_Locat || Usr.CR_Locat;                            
                   FindSw := '1';                            
                ELSE                            
                   SV_NxtPosition := SUBSTR(SV_NxtPosition,1,2) || Usr.CR_Locat;                            
                END IF;                            
             Else                            
                IF FindSw = '1' THEN                            
                   SV_NxtSign := Usr.CR_Team;                            
                   SV_NxtPosition := Usr.CR_Locat || Usr.CR_Locat;                          
                END IF;                            
             End If;                            
             if FindSw = '1' And Usr.CR_Congbn = '5' Then                            
                Update cmr9900                            
                   Set cr_status='9',                            
                       cr_confusr=Usr.CR_Team,                            
                       cr_confdate=SYSDATE,                            
                       cr_conmsg='자동결재처리'                            
                 Where cr_acptno=Call_Key_AcptNo                            
                   And cr_locat=Usr.CR_Locat;
                   
                 Update cmc0300
                    set cc_status = '9',
                        cc_eddate = SYSDATE
                  where cc_acptno = Call_Key_AcptNo
                    AND 1 > (SELECT COUNT(*) FROM CMR9900 WHERE CR_ACPTNO = Call_Key_AcptNo AND CR_LOCAT<> '00' AND CR_CONFDATE IS NULL);
                   FindSw := '0';                            
             ElsIf FindSw = '1' AND Usr.Cr_TeamCD != '8' Then                            
               Exit;                            
             End If;                            
          End Loop;                            
                            
          dbms_OUTPUT.PUT_LINE('309' || FindSw);                            
          dbms_OUTPUT.PUT_LINE('SV_NxtPosition1 = ' || SV_NxtPosition);                            
          If FindSw <> '1' Then                            
             SV_LastStatus := '8';                            
             Begin                            
                Select  MIN(CR_Locat)                            
                  Into  SV_NxtPosition                            
                  From  CMR9900                            
                 Where  CR_AcptNo = Call_Key_AcptNo                            
                   And  CR_Locat != '00'                            
                   And  CR_Status = '0'                            
                   And  CR_TeamCd <> '3'                            
                   And  CR_Congbn In ('1','2','3','4','5');                            
                EXCEPTION                            
                    WHEN  NO_DATA_FOUND  THEN                            
                        SV_LastStatus := '9';                            
             End;                            
                            
             If SV_NxtPosition IS NULL Then                            
                Begin                            
                    Select  MIN(CR_Locat)                            
                      Into  SV_NxtPosition                            
                      From  CMR9900                            
                     Where  CR_AcptNo = Call_Key_AcptNo                            
                       And  CR_Locat != '00'                            
                       And  CR_Status = '0'                            
                       And  CR_TeamCd = '3'                            
                       And  CR_Congbn In ('1','2','3','4','5');                            
                    EXCEPTION                            
                        WHEN  NO_DATA_FOUND  THEN                            
                            SV_LastStatus := '9';                            
                 End;                            
             END IF;                            
             if SV_LastStatus != '9' Then                            
                If SV_NxtPosition IS NULL Then                            
                   SV_LastStatus := '9';                            
                Else                            
                   FindSw := '1';                            
                End If;                            
             End If;                            
             if FindSw = '1' Then                            
                SV_NxtPosition := SUBSTR(SV_NxtPosition, 1, 2) || SUBSTR(SV_NxtPosition, 1, 2);                            
             End If;                            
          End If;                            
          If FindSw = '1' Then                            
             dbms_OUTPUT.PUT_LINE('SV_NxtPosition : ' || SV_NxtPosition);                            
             If LENGTH(SV_NxtPosition) = 2 Then                            
                SV_NxtPosition := SV_NxtPosition || SV_NxtPosition;                            
             End If;                            
             UPDate  CMR9900                            
                Set  (cr_team , cr_teamcd, cr_sgngbn, cr_congbn, cr_common, cr_blank,                            
                      cr_emger, cr_holi  , cr_orgstep, cr_confusr, cr_confname, cr_prcsw,cr_qrycd) =                            
                     (select  cr_team , cr_teamcd, cr_sgngbn, cr_congbn, cr_common, cr_blank,                            
                              cr_emger , cr_holi   , cr_orgstep, SV_NxtPosition, cr_confname, cr_prcsw,cr_qrycd                            
                        from  cmr9900                            
                       where  cr_acptno = Call_Key_AcptNo                            
                         and  cr_locat = SUBSTR(Sv_NxtPosition, 1, 2))                            
              Where  cr_acptno = Call_Key_AcptNo                            
                And  cr_locat  = '00';                            
          Elsif SV_LastStatus = '9' Then                            
             UPDate  CMR9900                            
                Set  cr_status = '9'                            
              Where  cr_acptno = Call_Key_AcptNo                            
                And  cr_Status = '0';                            
          End If;                            
       End If;                            
    End If;                            
    Sv_ListSw := NULL;                  
    dbms_OUTPUT.PUT_LINE('687Line SV_LastStatus ' || SV_LastStatus);                    
    If ErrSw IS NULL And SV_PrcSw = 'Y' AND Sv_LastStatus = '0' Then                            
       Sv_LastStatus := '8';                            
       Sv_ListSw := '1';                            
    ELSIF ErrSw IS NULL AND  Sv_LastStatus = '9' AND substr(Call_Key_AcptNo,5,2) < '30' THEN                            
       Begin                            
         Select  Count(*)                            
           Into  SV_Cnt                            
           From  CMR1000                            
          Where  CR_AcptNo = Call_Key_AcptNo                            
            And  CR_PrcDate is null;                            
          EXCEPTION                            
             WHEN  NO_DATA_FOUND  Then                            
                  SV_Cnt := 0;                            
       End;                            
       IF SV_Cnt > 0 THEN                            
          Sv_ListSw := '1';                            
       END IF;                          
    End If;                            
                            
    IF Sv_ListSw = '1' THEN                            
       IF Substr(Call_Key_AcptNo,5,2) < '30' THEN                            
          Update  cmr1010                            
             set  cr_status  = Sv_LastStatus,                            
                  cr_prcdate = SYSDATE                            
           where  cr_acptno = Call_Key_AcptNo                            
             And  cr_prcdate is null;                            
       END IF; 
    END IF;                            
                            
    If ErrSw IS NULL And Sv_LastStatus = '0' AND (Wk_CnclSw = '3' OR Wk_CnclSw = '9') THEN 
       IF Substr(Call_Key_AcptNo,5,2) < '30' Then                                                           
            Update  cmr1010                                                           
              set  cr_status  = '3',                                                           
                   cr_prcdate = SYSDATE                                                            
            where  cr_acptno = Call_Key_AcptNo                                                           
              And  cr_status = '0';                               
       END IF;  
    END IF;                            
                                
    If ErrSw IS NULL And Sv_LastStatus != '0' Then  
        If Sv_LastStatus = '9' Then
            Update  cmr1000                                                           
               set  cr_status  = Sv_LastStatus,                                                           
                    cr_prcdate = SYSDATE      ,                                                           
                    cr_eddate=SYSDATE                                                           
             where  cr_acptno = Call_Key_AcptNo                                                           
               And  cr_prcdate is null;                                                           
                                                           
            Update  cmr1000                                                           
               set  cr_status  = Sv_LastStatus,                                                           
                    cr_eddate=SYSDATE                                                           
             where  cr_acptno = Call_Key_AcptNo                                                           
               And  cr_eddate is null;      
    		
        ElsIf Sv_LastStatus = '8' And Substr(Call_Key_AcptNo,5,2) <> '06' Then      -- 롤백신청시 자꾸 상태를 8로 만들어서 롤백신청시에만 막음                       
           Update  cmr1000                            
              set  cr_status  = Sv_LastStatus,                            
                   cr_prcdate = SYSDATE                            
            where  cr_acptno = Call_Key_AcptNo                            
              And  cr_prcdate is null;                            
                             
           Update  cmr1000                            
              set  cr_status  = Sv_LastStatus                            
            where  cr_acptno = Call_Key_AcptNo                            
              And  cr_status != Sv_LastStatus;                            
        ElsIf Sv_LastStatus = '3' Then                            
           Update  cmr1000                            
              set  cr_status  = Sv_LastStatus,                            
                   cr_prcdate = SYSDATE,                                  
                   cr_eddate  = SYSDATE                            
            where  cr_acptno = Call_Key_AcptNo;                            
        End If;                            
        IF Sv_LastStatus = '3' And Substr(Call_Key_AcptNo,5,2) < '30' Then                            
            Update Cmr1010                            
               Set cr_confno=''                            
             Where cr_confno=Call_Key_AcptNo                            
               and cr_itemid in (select cr_itemid from cmr1010                            
                                  where cr_acptno=Call_Key_AcptNo                            
                                    and cr_status='3');                         
        END IF;  
    ELSE 
        IF Sv_LastStatus = '3' Then 
            UPDATE CMC0300  
               SET CC_STATUS='3' 
                  ,CC_EDDATE=SYSDATE 
             WHERE CC_ACPTNO=Call_Key_AcptNo; 
        ELSE 
            UPDATE CMC0300 
               SET CC_STATUS='9' 
                  ,CC_EDDATE=SYSDATE 
             WHERE CC_ACPTNO=Call_Key_AcptNo
               AND 1 > (SELECT COUNT(*) FROM CMR9900 WHERE CR_ACPTNO = Call_Key_AcptNo AND CR_LOCAT<> '00' AND CR_CONFDATE IS NULL AND CR_CONGBN <> '4'); 
        END IF; 
    END IF; 
        -- 완료/또는 반려 건이면서 SR-ID가 존재하는 경우의 처리 
    IF SV_SRID IS NOT NULL THEN 
       --반려건인 경우 처리 
       IF Sv_LastStatus = '3' THEN 
           IF Substr(Call_Key_AcptNo,5,2) = '04' THEN 
              UPDATE CMC0110 
                 SET CC_CNCLDATE=SYSDATE 
               WHERE CC_SRID=SV_SRID 
                 AND CC_USERID=SV_EDITOR; 
           ELSIF Substr(Call_Key_AcptNo,5,2) = '41' THEN 
              UPDATE CMC0100 
                 SET CC_STATUS='3' 
               WHERE CC_SRID=SV_SRID; 
               
               SELECT COUNT(*)
                 INTO SV_Cnt
                 FROM CMC0100
                WHERE CC_SRID = SV_SRID
                  AND CC_IFISYN = 'Y';
--                IF SV_Cnt > 0 THEN
--                    UPDATE IFIS.TCMIFISREQM
--                       SET RSP_CNTN = SV_SGNMSG
--                     WHERE BASE_NO = SV_SRID;
--                END IF;
           ELSIF Substr(Call_Key_AcptNo,5,2) = '69' THEN 
              UPDATE CMC0100 
                 SET CC_STATUS='D' 
               WHERE CC_SRID=SV_SRID; 
           END IF; 
       ELSE 
          IF Substr(Call_Key_AcptNo,5,2) = '01' OR Substr(Call_Key_AcptNo,5,2) = '02' OR 
             Substr(Call_Key_AcptNo,5,2) = '07' OR Substr(Call_Key_AcptNo,5,2) = '11' THEN 
          --체크아웃,이전버전체크아웃,체크인,체크아웃취소 
             IF Substr(Call_Key_AcptNo,5,2) <> '11' THEN 
                UPDATE CMR0020 
                   SET CR_ISRID=SV_SRID 
                 WHERE CR_ITEMID IN (SELECT CR_ITEMID FROM CMR1010 
                                      WHERE CR_ACPTNO=Call_Key_AcptNo 
                                        AND CR_STATUS<>'3' 
                                        AND CR_ITEMID=CR_BASEITEM) 
                   AND NVL(CR_ISRID,'NULL')<>SV_SRID; 
             ELSE 
                UPDATE CMR0020 
                   SET CR_ISRID='' 
                 WHERE CR_ITEMID IN (SELECT CR_ITEMID FROM CMR1010 
                                      WHERE CR_ACPTNO=Call_Key_AcptNo 
                                        AND CR_STATUS<>'3' 
                                        AND CR_ITEMID=CR_BASEITEM) 
                   AND CR_ISRID IS NOT NULL 
                   AND CR_ISRID=SV_SRID; 
             END IF; 
             UPDATE CMC0110 
                SET CC_STATUS='C' 
              WHERE CC_SRID=SV_SRID 
                AND CC_USERID=SV_EDITOR 
                AND CC_STATUS not in ('2','9');
--              
--              -- 체크아웃, 체크인 완료 시 IFIS 상태값 업데이트(2:검토, 11개발완료)
--            SELECT COUNT(*)
--             INTO SV_Cnt
--             FROM CMC0100
--            WHERE CC_SRID = SV_SRID
--              AND CC_IFISYN = 'Y';
--             IF SV_Cnt > 0 THEN
--                  IF Substr(Call_Key_AcptNo,5,2) = '01' OR Substr(Call_Key_AcptNo,5,2) = '02' THEN
--                        UPDATE IFIS.TCMIFISREQM 
--                           SET STATE = '2' 
--                         WHERE BASE_NO=SV_SRID
--                           AND 1 > (SELECT COUNT(*) FROM CMR9900 WHERE CR_ACPTNO = Call_Key_AcptNo AND CR_LOCAT<> '00' AND CR_CONFDATE IS NULL AND CR_CONGBN <> '4');
--                  ELSIF Substr(Call_Key_AcptNo,5,2) = '07' THEN
--                        UPDATE IFIS.TCMIFISREQM 
--                           SET STATE = '11' 
--                         WHERE BASE_NO=SV_SRID
--                           AND 1 > (SELECT COUNT(*) FROM CMR9900 WHERE CR_ACPTNO = Call_Key_AcptNo AND CR_LOCAT<> '00' AND CR_CONFDATE IS NULL AND CR_CONGBN <> '4');
--                  END IF;
--             END IF;
--          ELSIF Substr(Call_Key_AcptNo,5,2) = '03' THEN
             -- IFIS 연계이며 테스트적용일시 IFIS 테이블 상태값 Update
--               SELECT COUNT(*)
--                 INTO SV_Cnt
--                 FROM CMC0100
--                WHERE CC_SRID = SV_SRID
--                  AND CC_IFISYN = 'Y';
--                IF SV_Cnt > 0 THEN
--                    UPDATE IFIS.TCMIFISREQM
--                       SET STATE = '12'
--                     WHERE BASE_NO = SV_SRID
--                       AND 1 > (SELECT COUNT(*) FROM CMR9900 WHERE CR_ACPTNO = Call_Key_AcptNo AND CR_LOCAT<> '00' AND CR_CONFDATE IS NULL AND CR_CONGBN <> '4');
--                END IF;
          ELSIF Substr(Call_Key_AcptNo,5,2) = '04' THEN 
          -- 운영적용의 경우  
               SELECT COUNT(*) 
                 INTO SV_Cnt 
                 FROM CMR0020 
                WHERE CR_ISRID=SV_SRID 
                  AND CR_LSTUSR=SV_EDITOR 
                  AND CR_STATUS<>'0'; 
               IF SV_Cnt = 0 THEN 
                   Begin                            
                      Select  CC_SRNO
                        Into  SV_SRNO
                        From  CMC0100
                       Where  CC_SRID = SV_SRID
                         AND  CC_createuser=SV_EDITOR;
                   EXCEPTION                            
                        WHEN  NO_DATA_FOUND  Then                            
                              SV_SRNO := '0';                         
                   End;
    
                   UPDATE CMC0110 
                      SET CC_STATUS='9' 
--                          SET CC_STATUS='6' 
                    WHERE CC_SRID=SV_SRID 
                      AND CC_USERID=SV_EDITOR; 
                   
                   -- cmc0100 완료상태 update 추가
--                   UPDATE CMC0100 
--                      SET CC_STATUS='9' 
--                    WHERE CC_SRID=SV_SRID 
--                      AND CC_createuser=SV_EDITOR; 
                   
                  -- IFIS 연계이며 운영적용일시 IFIS 테이블 운영적용인, 날짜, 상태값 UPDATE
--                   SELECT COUNT(*)
--                     INTO SV_Cnt
--                     FROM CMC0100
--                    WHERE CC_SRID = SV_SRID
--                      AND CC_IFISYN = 'Y';
--                    IF SV_Cnt > 0 THEN
--                        UPDATE IFIS.TCMIFISREQM
--                           SET RFLC_EMNO = SV_EDITOR,
--                               RFLC_REG_DTTM = SYSDATE,
--                               STATE = '13'
--                         WHERE BASE_NO = SV_SRID
--                           AND 1 > (SELECT COUNT(*) FROM CMR9900 WHERE CR_ACPTNO = Call_Key_AcptNo AND CR_LOCAT<> '00' AND CR_CONFDATE IS NULL AND CR_CONGBN <> '4');
--                    END IF;
               END IF; 
          ELSIF Substr(Call_Key_AcptNo,5,2) = '41' THEN 
             UPDATE CMC0100 
                SET CC_STATUS='4' 
              WHERE CC_SRID=SV_SRID 
                AND CC_STATUS='1'
                AND 1 > (SELECT COUNT(*) FROM CMR9900 WHERE CR_ACPTNO = Call_Key_AcptNo AND CR_LOCAT<> '00' AND CR_CONFDATE IS NULL AND CR_CONGBN <> '4');
              
             UPDATE CMC0110 
                SET CC_STATUS='C' 
              WHERE CC_SRID=SV_SRID 
                AND CC_STATUS='0'
                AND 1 > (SELECT COUNT(*) FROM CMR9900 WHERE CR_ACPTNO = Call_Key_AcptNo AND CR_LOCAT<> '00' AND CR_CONFDATE IS NULL AND CR_CONGBN <> '4');
             
             -- SR등록 완료 시 IFIS 상태값 업데이트(1:검토)
--             SELECT COUNT(*)
--                 INTO SV_Cnt
--                 FROM CMC0100
--                WHERE CC_SRID = SV_SRID
--                  AND CC_IFISYN = 'Y';
--             IF SV_Cnt > 0 THEN
--                UPDATE IFIS.TCMIFISREQM 
--                   SET STATE = '1' 
--                 WHERE BASE_NO=SV_SRID
--                   AND 1 > (SELECT COUNT(*) FROM CMR9900 WHERE CR_ACPTNO = Call_Key_AcptNo AND CR_LOCAT<> '00' AND CR_CONFDATE IS NULL AND CR_CONGBN <> '4');
--             END IF;
          ELSIF Substr(Call_Key_AcptNo,5,2) = '69' THEN 
             UPDATE CMC0100 
                SET CC_STATUS='9' 
                   ,CC_COMPDATE=SYSDATE 
              WHERE CC_SRID=SV_SRID; 
          END IF; 
       END IF; 
    END IF;            
End CMR9900_STR;