-- GENERATED BY QueryOne AT 2021-03-04 14:21:14
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

DROP TABLE ECAMS.CMR1000 CASCADE CONSTRAINTS PURGE;

CREATE TABLE ECAMS.CMR1000
(
    CR_ACPTNO CHAR(12) NOT NULL,
    CR_SYSCD CHAR(5) NULL,
    CR_SYSGB CHAR(1) NULL,
    CR_ACPTDATE DATE DEFAULT SYSDATE NULL,
    CR_STATUS CHAR(1) DEFAULT ('0') NULL,
    CR_TEAMCD VARCHAR2(15) NULL,
    CR_QRYCD CHAR(2) NULL,
    CR_PASSOK CHAR(1) DEFAULT ('0') NULL,
    CR_PASSCD VARCHAR2(500) NULL,
    CR_NOAUTO CHAR(1) DEFAULT ('0') NULL,
    CR_PRCREQ CHAR(14) NULL,
    CR_EDDATE DATE NULL,
    CR_PRCDATE DATE NULL,
    CR_EDITOR VARCHAR2(10) NULL,
    CR_GYULJAE CHAR(1) DEFAULT ('0') NULL,
    CR_BEFJOB CHAR(1) DEFAULT ('0') NULL,
    CR_SAYU VARCHAR2(2000) NULL,
    CR_ITSMID VARCHAR2(20) NULL,
    CR_CNCL CHAR(1) NULL,
    CR_SAYUCD CHAR(1) NULL,
    CR_GYULTIME DATE NULL,
    CR_GYULUSER VARCHAR2(10) NULL,
    CR_EDCNT NUMBER(4) DEFAULT 0 NULL,
    CR_RELATNO VARCHAR2(12) NULL,
    CR_NOTIFY CHAR(1) NULL,
    CR_PASSSUB CHAR(1) NULL,
    CR_JOBCD VARCHAR2(6) NULL,
    CR_PID NUMBER NULL,
    CR_BASEUP CHAR(1) DEFAULT 'Y' NULL,
    CR_EMGCD VARCHAR2(2) NULL,
    CR_LASTDATE DATE DEFAULT SYSDATE NULL,
    CR_CNCLSTEP VARCHAR2(10) NULL,
    CR_CNCLLSTD DATE NULL,
    CR_RETRYYN VARCHAR2(1) NULL,
    CR_SVRCD VARCHAR2(2) NULL,
    CR_SVRSEQ NUMBER NULL,
    CR_ITSMTITLE VARCHAR2(500) DEFAULT 0 NULL,
    CR_SYSSTEP NUMBER DEFAULT 0 NULL,
    CR_DEPT VARCHAR2(40) NULL,
    CR_REQDATE VARCHAR2(8) NULL,
    CR_REQDOC VARCHAR2(20) NULL,
    CR_ETC VARCHAR2(500) NULL,
    CR_REQTITLE VARCHAR2(300) NULL,
    CR_EMRGB VARCHAR2(1) DEFAULT '0' NULL,
    CR_EMRCD VARCHAR2(2) NULL,
    CR_EMRMSG VARCHAR2(100) NULL,
    CR_PRCTIME VARCHAR2(4) NULL,
    CR_OLDTIME VARCHAR2(4) NULL,
    CR_ECLIPSE VARCHAR2(1) DEFAULT 'R' NULL,
    CR_SVRYN VARCHAR2(1) DEFAULT 'Y' NULL,
    CR_CLOSEYN CHAR(1) DEFAULT 'N' NULL,
    CR_VERSION CHAR(1) DEFAULT 'Y' NULL,
    CR_SRID VARCHAR2(12) NULL,
    CR_PLANDATE VARCHAR2(8) NULL,
    CR_SPARROW CHAR(1) NULL,
    CR_SPARROWSAYU VARCHAR2(2000) NULL
)
SEGMENT CREATION IMMEDIATE
STORAGE
(
    INITIAL 512K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01;

CREATE INDEX ECAMS.CMR1000_IDX1
ON ECAMS.CMR1000
(
    CR_QRYCD ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1000_IDX2
ON ECAMS.CMR1000
(
    CR_SYSCD ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1000_IDX3
ON ECAMS.CMR1000
(
    CR_TEAMCD ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1000_IDX4
ON ECAMS.CMR1000
(
    CR_ACPTDATE ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1000_IDX5
ON ECAMS.CMR1000
(
    CR_EDITOR ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE UNIQUE INDEX ECAMS.CMR1000_PK
ON ECAMS.CMR1000
(
    CR_ACPTNO ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

ALTER TABLE ECAMS.CMR1000
ADD CONSTRAINT CMR1000_PK PRIMARY KEY(CR_ACPTNO)
     USING INDEX ECAMS.CMR1000_PK;

CREATE OR REPLACE TRIGGER "ECAMS"."CMR1000_TRG" 
BEFORE DELETE OR UPDATE ON CMR1000 
FOR EACH ROW
Declare    
	V_String      Varchar2(50);    
	V_ConfUsr     Varchar2(10);    
	V_UserName    Varchar2(20);    
	V_Cnt         NUMBER;    
	V_Pgm         Varchar2(500);    
	V_LinkUrl     Varchar2(200);    
    V_MSGACPT     VARCHAR2(50);  
    V_SUM1        NUMBER;                                    
	V_SUM2        NUMBER;                                    
	V_SUM3        NUMBER;         
    V_SUM4        NUMBER;
    V_PlugYN      Varchar2(2);       
    V_ConMsg      Varchar2(500);                               
	V_ReqNm       Varchar2(100); 
    
    
	CURSOR  MSG    IS    
		Select  a.cr_rsrcname    
		From  CMR1010 a,cmr0020 b    
		Where  a.CR_acptno = :NEW.cr_acptno    
		and  a.cr_status<>'3'    
		and  a.cr_qrycd<>'11'    
		and  a.cr_itemid=b.cr_itemid    
		and  nvl(b.cr_pgmtype,'0')='1'    
		and  a.cr_itemid=a.cr_baseitem    
		group  by a.cr_rsrcname;    
    
Begin
 
  
   
    SELECT CM_URL   
     INTO V_LinkUrl   
     FROM CMM0010   
    WHERE CM_STNO='ECAMS';   
       
    V_LinkUrl := V_LinkUrl || 'ecams_win_flex/';    
      
    IF :NEW.CR_ITSMID IS NULL THEN  
       V_MSGACPT := '신청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7,6);  
    ELSE  
       V_MSGACPT := 'SR-ID:' || :NEW.CR_ITSMID;  
    END IF;  
      
    IF :NEW.cr_qrycd = '01' or :NEW.cr_qrycd = '02' or :NEW.cr_qrycd = '11' or :NEW.cr_qrycd = '12' THEN    
        V_LinkUrl := V_LinkUrl || 'eCmr0150.jsp?ReqNo=' || :NEW.CR_ACPTNO;    
    ELSIF :NEW.cr_qrycd = '03' or :NEW.cr_qrycd = '04' or :NEW.cr_qrycd = '05' or :NEW.cr_qrycd = '06' or :NEW.cr_qrycd = '07' or :NEW.cr_qrycd = '16' THEN    
        V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;     
    ELSIF :NEW.cr_qrycd = '31' THEN    
        V_LinkUrl := V_LinkUrl || 'eCmr0750.jsp?ReqNo=' || :NEW.CR_ACPTNO;   
    ELSE  
        V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;   
    END IF;  
    
	IF (:NEW.cr_status = '9' and :OLD.cr_status <> '9') OR    
	(:NEW.cr_status = '8' and :OLD.cr_status <> '8') OR    
	(:NEW.cr_status = '3' and :OLD.cr_status <> '3') THEN    
		IF :NEW.cr_status <> '8' THEN    
			BEGIN    
				UPDATE CMR9900    
				SET    cr_status=:NEW.cr_status,    
				cr_confdate=SYSDATE    
				WHERE  cr_acptno=:NEW.cr_acptno    
				AND  cr_status='0';    
			END;    
		END IF;    
		IF :NEW.cr_qrycd < '20' THEN    
			IF :NEW.cr_status <> '3' THEN    
				BEGIN    
					UPDATE CMR1010    
					SET cr_status=:NEW.cr_status    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_status<>'3';    
				END;    
				    
				BEGIN    
					UPDATE CMR1010    
					SET cr_prcdate=SYSDATE    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_prcdate is null;    
				END;                
			ELSE
                IF :NEW.CR_QRYCD = '04' AND :NEW.CR_SRID IS NOT NULL THEN                           
                       UPDATE CMC0100                           
                          SET CC_STATUS='13'   --개발완료                                
                        WHERE CC_SRID =:NEW.CR_SRID;                            
                END IF; 
                
				BEGIN    
					UPDATE CMR1010    
					SET cr_status=:NEW.cr_status    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_status='0';    
				END;    
				    
				BEGIN    
					UPDATE CMR1010    
					SET cr_prcdate=SYSDATE    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_prcdate is null;    
				END;    
			END IF;   
        ELSIF :NEW.cr_qrycd = '31' THEN    
			IF :NEW.cr_status <> '3' THEN    
				BEGIN    
					UPDATE CMR1300    
					SET cr_status=:NEW.cr_status    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_status<>'3';    
				END;    
				    
				BEGIN    
					UPDATE CMR1300    
					SET cr_prcdate=SYSDATE    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_prcdate is null;    
				END;    
			ELSE    
				BEGIN    
					UPDATE CMR1300    
					SET cr_status=:NEW.cr_status    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_status='0';    
				END;    
				    
				BEGIN    
					UPDATE CMR1300    
					SET cr_prcdate=SYSDATE    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_prcdate is null;    
				END;    
			END IF;   
		END IF;  
    END IF;  
    
    IF :NEW.CR_PRCDATE IS NOT NULL AND :OLD.CR_PRCDATE IS NULL AND :NEW.Cr_Status <> '3' THEN
        BEGIN                              
			SELECT COUNT(*)                              
			INTO V_Cnt                              
			FROM CMR9910                              
			WHERE CR_CONUSR=:NEW.CR_EDITOR                              
			AND CR_SENDDATE=SYSDATE;                              
			EXCEPTION                              
			WHEN  NO_DATA_FOUND  Then                              
			V_Cnt := 0;                              
		END;                              
		                          
		IF V_Cnt = 0 THEN                        
           V_CNT    := 0;                  
                                       
           INSERT INTO CMR9910                              
              (cr_conusr, cr_senddate, cr_status, cr_acptno, cr_sendusr,cr_sgnmsg,cr_title,cr_linkurl,cr_noticd,CR_NOTIGBN,CR_SMSMSG) 
              (SELECT :NEW.cr_editor, SYSDATE,'0',:NEW.cr_acptno, :NEW.cr_editor,                              
                      '1. 요청일 : ' || to_char(:NEW.cr_acptdate,'yyyy/mm/dd') || chr(13) ||  
                      '2. 신청번호: ' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7) || chr(13) ||  
                      '3. ' || CM_CODENAME || '이 처리완료 되었습니다.' || Chr(13) ||    
                      '      형상관리시스템(eCAMS)에 접속하여 확인하여 주시기 바랍니다.'                             
                     ,'형상관리시스템 ' || CM_CODENAME || ' 요청건 완료 알림'-- || '[' || :NEW.cr_srid || ']'      
                     ,V_LinkUrl,'SMS','ED'                                                      
                     ,'[형상관리 ' || CM_CODENAME || ' 완료알림]' || CHR(10) ||               
                      '요청일:' || to_char(:NEW.cr_acptdate,'yyyy/mm/dd') || chr(10) ||                 
                      '요청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7)
                 FROM CMM0020
                WHERE CM_MACODE='REQUEST'
                  AND CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));                     
		END IF;                         
	END IF;                               
             
    IF :NEW.Cr_Status = '3' AND :OLD.Cr_Status = '0' THEN 
        V_ConMsg := '';
        V_ConfUsr := '';
        BEGIN     
            SELECT CR_CONMSG,CR_CONFUSR      
            INTO V_ConMsg,V_ConfUsr         
            FROM CMR9900             
            WHERE CR_ACPTNO = :NEW.CR_ACPTNO       
            AND CR_STATUS ='3'      
            AND CR_TEAMCD <> '1'      
            AND CR_CONFUSR IS NOT NULL      
            AND CR_LOCAT <> '00';                        
            EXCEPTION                              
            WHEN  NO_DATA_FOUND  Then                     
            V_ConMsg := NULL;                
        END;     
      
        IF V_ConMsg IS NULL THEN  
            BEGIN   
                SELECT CR_CONMSG,CR_BaseUsr      
                INTO V_ConMsg,V_ConfUsr         
                FROM CMR9900             
                WHERE CR_ACPTNO = :NEW.CR_ACPTNO       
                AND CR_STATUS ='3'      
                AND CR_TEAMCD <> '1'      
                AND CR_LOCAT = '00';                        
                EXCEPTION                              
                WHEN  NO_DATA_FOUND  Then                     
                V_ConMsg := '';              
            END;     
        END IF;  
        
        IF V_ConfUsr IS NULL OR V_ConfUsr = '' THEN
           V_ConfUsr := :NEW.CR_EDITOR;
        END IF;
        
        INSERT INTO CMR9910                              
            (cr_conusr, cr_senddate, cr_status, cr_acptno, cr_sendusr,cr_sgnmsg,cr_title,cr_linkurl,cr_noticd,CR_NOTIGBN,CR_SMSMSG) 
            (SELECT :NEW.cr_editor, SYSDATE,'0',:NEW.cr_acptno, V_ConfUsr,                              
                    '1. 요청일 : ' || TO_CHAR(:NEW.CR_ACPTDATE,'YYYY/MM/DD') || chr(13) ||  
                    '2. 신청번호: ' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7) || chr(13) ||  
                    '3. ' || CM_CODENAME || '이 반려처리 되었습니다.' || Chr(13) ||             
                    '4. 반려사유 : ' || V_ConMsg || Chr(13) || Chr(13) ||                                          
                    '형상관리시스템(eCAMS)에 접속하여 확인하여 주시기 바랍니다.'                             
                   ,'형상관리시스템 요청건 반송 알림 [' || :NEW.cr_srid || ']'                               
                   ,V_LinkUrl,'SMS','CN'                                                     
                     ,'[형상관리 ' || CM_CODENAME || ' 반려알림]' || CHR(10) ||               
                      '요청일:' || to_char(:NEW.cr_acptdate,'yyyy/mm/dd') || chr(10) ||                 
                      '요청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7)
               FROM CMM0020
              WHERE CM_MACODE='REQUEST'
                AND CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));      
	END IF;   
      
End CMR1000_Trg;
/

COMMENT ON TABLE ECAMS.CMR1000 IS '변경신청기본';

COMMENT ON COLUMN ECAMS.CMR1000.CR_REQDOC IS '문서번호';

COMMENT ON COLUMN ECAMS.CMR1000.CR_ETC IS '변경내용';

COMMENT ON COLUMN ECAMS.CMR1000.CR_REQTITLE IS '문서제목';

COMMENT ON COLUMN ECAMS.CMR1000.CR_EMRGB IS '긴급변경여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_EMRCD IS '긴급구분';

COMMENT ON COLUMN ECAMS.CMR1000.CR_EMRMSG IS '긴급사유';

COMMENT ON COLUMN ECAMS.CMR1000.CR_PRCTIME IS '정기배포시간';

COMMENT ON COLUMN ECAMS.CMR1000.CR_OLDTIME IS '직전정기배포시간';

COMMENT ON COLUMN ECAMS.CMR1000.CR_ECLIPSE IS '요청매체(L:Local,R:Remote,E:eclipse)';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SVRYN IS '체크인시배포여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_CLOSEYN IS '폐기신청여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_VERSION IS '체크인시버전업여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_PLANDATE IS '운영배포요청일';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SPARROW IS '신청서별 취약점확인 코드 (0:배대상 1:통과 2:미달(스패로우 OFF일때))';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SPARROWSAYU IS '취약점 예외처리에 대한 사';

COMMENT ON COLUMN ECAMS.CMR1000.CR_ACPTNO IS '신청번호';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SYSCD IS '시스템코드';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SYSGB IS '시스템구분';

COMMENT ON COLUMN ECAMS.CMR1000.CR_ACPTDATE IS '신청일시';

COMMENT ON COLUMN ECAMS.CMR1000.CR_STATUS IS '진행상태';

COMMENT ON COLUMN ECAMS.CMR1000.CR_TEAMCD IS '업무그룹';

COMMENT ON COLUMN ECAMS.CMR1000.CR_QRYCD IS '신청구분';

COMMENT ON COLUMN ECAMS.CMR1000.CR_PASSOK IS '처리구분 0:일반적용, 2:긴급, 4:특정일시적용';

COMMENT ON COLUMN ECAMS.CMR1000.CR_PASSCD IS '변경제목';

COMMENT ON COLUMN ECAMS.CMR1000.CR_NOAUTO IS '수기처리여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_PRCREQ IS '처리희망일시';

COMMENT ON COLUMN ECAMS.CMR1000.CR_EDDATE IS '최종완료일시';

COMMENT ON COLUMN ECAMS.CMR1000.CR_PRCDATE IS '처리완료일시';

COMMENT ON COLUMN ECAMS.CMR1000.CR_EDITOR IS '작성자사번';

COMMENT ON COLUMN ECAMS.CMR1000.CR_GYULJAE IS '결재구분';

COMMENT ON COLUMN ECAMS.CMR1000.CR_BEFJOB IS '선행작업유무';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SAYU IS '변경사유';

COMMENT ON COLUMN ECAMS.CMR1000.CR_ITSMID IS 'ITSM ID';

COMMENT ON COLUMN ECAMS.CMR1000.CR_CNCL IS '취소여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SAYUCD IS '변경신청사유코드';

COMMENT ON COLUMN ECAMS.CMR1000.CR_GYULTIME IS '적용대기일시';

COMMENT ON COLUMN ECAMS.CMR1000.CR_GYULUSER IS '적용대기자사번';

COMMENT ON COLUMN ECAMS.CMR1000.CR_EDCNT IS '처리총건수';

COMMENT ON COLUMN ECAMS.CMR1000.CR_RELATNO IS '관련신청번호';

COMMENT ON COLUMN ECAMS.CMR1000.CR_NOTIFY IS '알림여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_PASSSUB IS '업무후긴급여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_JOBCD IS '업무';

COMMENT ON COLUMN ECAMS.CMR1000.CR_PID IS '프로세스 ID';

COMMENT ON COLUMN ECAMS.CMR1000.CR_BASEUP IS '서버재기동여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_EMGCD IS '변경구분(REQCD)';

COMMENT ON COLUMN ECAMS.CMR1000.CR_LASTDATE IS '최종수정일';

COMMENT ON COLUMN ECAMS.CMR1000.CR_CNCLSTEP IS '반려단계';

COMMENT ON COLUMN ECAMS.CMR1000.CR_CNCLLSTD IS '반려일시';

COMMENT ON COLUMN ECAMS.CMR1000.CR_RETRYYN IS '재처리여부';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SVRCD IS '일괄등록기준서버구분';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SVRSEQ IS '일괄등록기준서버일련번호';

COMMENT ON COLUMN ECAMS.CMR1000.CR_ITSMTITLE IS 'ITSM 제목';

COMMENT ON COLUMN ECAMS.CMR1000.CR_SYSSTEP IS '처리STEP';

COMMENT ON COLUMN ECAMS.CMR1000.CR_DEPT IS '요청부서';

COMMENT ON COLUMN ECAMS.CMR1000.CR_REQDATE IS '요청일자';