-- GENERATED BY QueryOne AT 2021-03-04 14:18:52
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.NEXTTIME_UPDATE 
 IS        
 WKSYSTIME          VARCHAR2 (50);
 PERTIME            VARCHAR2 (4);
 WKSYSCD            VARCHAR2 (5);
 
CURSOR  SYSLIST  IS            
     Select CM_SYSCD, CM_SYSTIME            
       From CMM0030            
      Where CM_CLOSEDT IS NULL            
        And SUBSTR(CM_SYSINFO,6,1)='1';
CURSOR SYSTIME IS
     SELECT substr(wdata,
                  instr(wdata, ',', 1, LEVEL) + 1,
                  instr(wdata, ',', 1, LEVEL + 1) - instr(wdata, ',', 1, LEVEL) - 1) NAME
        FROM (
               SELECT ',' || CM_RELTIME || ',' wdata
               FROM CMM0030          
              Where CM_CLOSEDT IS NULL
                AND CM_SYSCD=WKSYSCD
                And SUBSTR(CM_SYSINFO,6,1)='1'           
              )
        CONNECT BY LEVEL <= length(wdata) - length(REPLACE(wdata, ',')) - 1;
        
Begin    
                                         
   For List1 In SYSLIST  Loop 
       WKSYSCD := List1.CM_SYSCD;
       PERTIME := NULL;
       For List2 In SYSTIME LOOP
           IF List2.NAME >= TO_CHAR(SYSDATE-1/(48),'HH24MI') AND
              List2.NAME >= TO_CHAR(SYSDATE,'HH24MI') THEN
              PERTIME := List2.NAME;
              EXIT;
           END IF;
       END LOOP;
       
       IF PERTIME IS NOT NULL THEN
           IF PERTIME <> List1.CM_SYSTIME THEN
              UPDATE CMM0030
                 SET CM_SYSTIME=PERTIME
               WHERE CM_SYSCD=List1.CM_SYSCD;
           END IF;
       END IF;
   End Loop; 
     
End NEXTTIME_UPDATE;