-- GENERATED BY QueryOne AT 2021-03-04 14:17:01
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE TRIGGER "ECAMS"."CMR1000_TRG" 
BEFORE DELETE OR UPDATE ON CMR1000 
FOR EACH ROW
Declare    
	V_String      Varchar2(50);    
	V_ConfUsr     Varchar2(10);    
	V_UserName    Varchar2(20);    
	V_Cnt         NUMBER;    
	V_Pgm         Varchar2(500);    
	V_LinkUrl     Varchar2(200);    
    V_MSGACPT     VARCHAR2(50);  
    V_SUM1        NUMBER;                                    
	V_SUM2        NUMBER;                                    
	V_SUM3        NUMBER;         
    V_SUM4        NUMBER;
    V_PlugYN      Varchar2(2);       
    V_ConMsg      Varchar2(500);                               
	V_ReqNm       Varchar2(100); 
    
    
	CURSOR  MSG    IS    
		Select  a.cr_rsrcname    
		From  CMR1010 a,cmr0020 b    
		Where  a.CR_acptno = :NEW.cr_acptno    
		and  a.cr_status<>'3'    
		and  a.cr_qrycd<>'11'    
		and  a.cr_itemid=b.cr_itemid    
		and  nvl(b.cr_pgmtype,'0')='1'    
		and  a.cr_itemid=a.cr_baseitem    
		group  by a.cr_rsrcname;    
    
Begin
 
  
   
    SELECT CM_URL   
     INTO V_LinkUrl   
     FROM CMM0010   
    WHERE CM_STNO='ECAMS';   
       
    V_LinkUrl := V_LinkUrl || 'ecams_win_flex/';    
      
    IF :NEW.CR_ITSMID IS NULL THEN  
       V_MSGACPT := '신청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7,6);  
    ELSE  
       V_MSGACPT := 'SR-ID:' || :NEW.CR_ITSMID;  
    END IF;  
      
    IF :NEW.cr_qrycd = '01' or :NEW.cr_qrycd = '02' or :NEW.cr_qrycd = '11' or :NEW.cr_qrycd = '12' THEN    
        V_LinkUrl := V_LinkUrl || 'eCmr0150.jsp?ReqNo=' || :NEW.CR_ACPTNO;    
    ELSIF :NEW.cr_qrycd = '03' or :NEW.cr_qrycd = '04' or :NEW.cr_qrycd = '05' or :NEW.cr_qrycd = '06' or :NEW.cr_qrycd = '07' or :NEW.cr_qrycd = '16' THEN    
        V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;     
    ELSIF :NEW.cr_qrycd = '31' THEN    
        V_LinkUrl := V_LinkUrl || 'eCmr0750.jsp?ReqNo=' || :NEW.CR_ACPTNO;   
    ELSE  
        V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;   
    END IF;  
    
	IF (:NEW.cr_status = '9' and :OLD.cr_status <> '9') OR    
	(:NEW.cr_status = '8' and :OLD.cr_status <> '8') OR    
	(:NEW.cr_status = '3' and :OLD.cr_status <> '3') THEN    
		IF :NEW.cr_status <> '8' THEN    
			BEGIN    
				UPDATE CMR9900    
				SET    cr_status=:NEW.cr_status,    
				cr_confdate=SYSDATE    
				WHERE  cr_acptno=:NEW.cr_acptno    
				AND  cr_status='0';    
			END;    
		END IF;    
		IF :NEW.cr_qrycd < '20' THEN    
			IF :NEW.cr_status <> '3' THEN    
				BEGIN    
					UPDATE CMR1010    
					SET cr_status=:NEW.cr_status    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_status<>'3';    
				END;    
				    
				BEGIN    
					UPDATE CMR1010    
					SET cr_prcdate=SYSDATE    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_prcdate is null;    
				END;                
			ELSE
                IF :NEW.CR_QRYCD = '04' AND :NEW.CR_SRID IS NOT NULL THEN                           
                       UPDATE CMC0100                           
                          SET CC_STATUS='13'   --개발완료                                
                        WHERE CC_SRID =:NEW.CR_SRID;                            
                END IF; 
                
				BEGIN    
					UPDATE CMR1010    
					SET cr_status=:NEW.cr_status    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_status='0';    
				END;    
				    
				BEGIN    
					UPDATE CMR1010    
					SET cr_prcdate=SYSDATE    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_prcdate is null;    
				END;    
			END IF;   
        ELSIF :NEW.cr_qrycd = '31' THEN    
			IF :NEW.cr_status <> '3' THEN    
				BEGIN    
					UPDATE CMR1300    
					SET cr_status=:NEW.cr_status    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_status<>'3';    
				END;    
				    
				BEGIN    
					UPDATE CMR1300    
					SET cr_prcdate=SYSDATE    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_prcdate is null;    
				END;    
			ELSE    
				BEGIN    
					UPDATE CMR1300    
					SET cr_status=:NEW.cr_status    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_status='0';    
				END;    
				    
				BEGIN    
					UPDATE CMR1300    
					SET cr_prcdate=SYSDATE    
					WHERE cr_acptno=:NEW.cr_acptno    
					And cr_prcdate is null;    
				END;    
			END IF;   
		END IF;  
    END IF;  
    
    IF :NEW.CR_PRCDATE IS NOT NULL AND :OLD.CR_PRCDATE IS NULL AND :NEW.Cr_Status <> '3' THEN
        BEGIN                              
			SELECT COUNT(*)                              
			INTO V_Cnt                              
			FROM CMR9910                              
			WHERE CR_CONUSR=:NEW.CR_EDITOR                              
			AND CR_SENDDATE=SYSDATE;                              
			EXCEPTION                              
			WHEN  NO_DATA_FOUND  Then                              
			V_Cnt := 0;                              
		END;                              
		                          
		IF V_Cnt = 0 THEN                        
           V_CNT    := 0;                  
                                       
           INSERT INTO CMR9910                              
              (cr_conusr, cr_senddate, cr_status, cr_acptno, cr_sendusr,cr_sgnmsg,cr_title,cr_linkurl,cr_noticd,CR_NOTIGBN,CR_SMSMSG) 
              (SELECT :NEW.cr_editor, SYSDATE,'0',:NEW.cr_acptno, :NEW.cr_editor,                              
                      '1. 요청일 : ' || to_char(:NEW.cr_acptdate,'yyyy/mm/dd') || chr(13) ||  
                      '2. 신청번호: ' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7) || chr(13) ||  
                      '3. ' || CM_CODENAME || '이 처리완료 되었습니다.' || Chr(13) ||    
                      '      형상관리시스템(eCAMS)에 접속하여 확인하여 주시기 바랍니다.'                             
                     ,'형상관리시스템 ' || CM_CODENAME || ' 요청건 완료 알림'-- || '[' || :NEW.cr_srid || ']'      
                     ,V_LinkUrl,'SMS','ED'                                                      
                     ,'[형상관리 ' || CM_CODENAME || ' 완료알림]' || CHR(10) ||               
                      '요청일:' || to_char(:NEW.cr_acptdate,'yyyy/mm/dd') || chr(10) ||                 
                      '요청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7)
                 FROM CMM0020
                WHERE CM_MACODE='REQUEST'
                  AND CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));                     
		END IF;                         
	END IF;                               
             
    IF :NEW.Cr_Status = '3' AND :OLD.Cr_Status = '0' THEN 
        V_ConMsg := '';
        V_ConfUsr := '';
        BEGIN     
            SELECT CR_CONMSG,CR_CONFUSR      
            INTO V_ConMsg,V_ConfUsr         
            FROM CMR9900             
            WHERE CR_ACPTNO = :NEW.CR_ACPTNO       
            AND CR_STATUS ='3'      
            AND CR_TEAMCD <> '1'      
            AND CR_CONFUSR IS NOT NULL      
            AND CR_LOCAT <> '00';                        
            EXCEPTION                              
            WHEN  NO_DATA_FOUND  Then                     
            V_ConMsg := NULL;                
        END;     
      
        IF V_ConMsg IS NULL THEN  
            BEGIN   
                SELECT CR_CONMSG,CR_BaseUsr      
                INTO V_ConMsg,V_ConfUsr         
                FROM CMR9900             
                WHERE CR_ACPTNO = :NEW.CR_ACPTNO       
                AND CR_STATUS ='3'      
                AND CR_TEAMCD <> '1'      
                AND CR_LOCAT = '00';                        
                EXCEPTION                              
                WHEN  NO_DATA_FOUND  Then                     
                V_ConMsg := '';              
            END;     
        END IF;  
        
        IF V_ConfUsr IS NULL OR V_ConfUsr = '' THEN
           V_ConfUsr := :NEW.CR_EDITOR;
        END IF;
        
        INSERT INTO CMR9910                              
            (cr_conusr, cr_senddate, cr_status, cr_acptno, cr_sendusr,cr_sgnmsg,cr_title,cr_linkurl,cr_noticd,CR_NOTIGBN,CR_SMSMSG) 
            (SELECT :NEW.cr_editor, SYSDATE,'0',:NEW.cr_acptno, V_ConfUsr,                              
                    '1. 요청일 : ' || TO_CHAR(:NEW.CR_ACPTDATE,'YYYY/MM/DD') || chr(13) ||  
                    '2. 신청번호: ' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7) || chr(13) ||  
                    '3. ' || CM_CODENAME || '이 반려처리 되었습니다.' || Chr(13) ||             
                    '4. 반려사유 : ' || V_ConMsg || Chr(13) || Chr(13) ||                                          
                    '형상관리시스템(eCAMS)에 접속하여 확인하여 주시기 바랍니다.'                             
                   ,'형상관리시스템 요청건 반송 알림 [' || :NEW.cr_srid || ']'                               
                   ,V_LinkUrl,'SMS','CN'                                                     
                     ,'[형상관리 ' || CM_CODENAME || ' 반려알림]' || CHR(10) ||               
                      '요청일:' || to_char(:NEW.cr_acptdate,'yyyy/mm/dd') || chr(10) ||                 
                      '요청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7)
               FROM CMM0020
              WHERE CM_MACODE='REQUEST'
                AND CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));      
	END IF;   
      
End CMR1000_Trg;