-- GENERATED BY QueryOne AT 2021-03-04 14:18:52
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.MAKE_PGMLIST     
(SYSCD                 IN   VARCHAR2)            
 IS        
 JOBCD              VARCHAR2 (05);      
 RSRCCD             VARCHAR2 (100);      
       
CURSOR  PGMLIST  IS                        
 Select CM_RSRCNAME, CM_DIRPATH      
   From CMM1600;      
          
BEGIN      
    For PGM In PGMLIST  Loop      
          
        IF SYSCD = '90001' or SYSCD = '01000' THEN      
            --IF INSTR(PGM.CM_RSRCNAME,'.class',-1,1) > 0 THEN      
            IF INSTR(PGM.CM_DIRPATH,'/classes') > 0 or PGM.CM_RSRCNAME = 'WINK.tar' THEN    
                DELETE FROM CMM1600 WHERE CM_RSRCNAME = PGM.CM_RSRCNAME AND CM_DIRPATH = PGM.CM_DIRPATH;      
            ELSE      
                JOBCD := 'ADMIN';      
                  
                IF INSTR(PGM.CM_DIRPATH,'/com/shc/wink/cc/bv') > 0 THEN      
                    JOBCD := 'BV';      
                ELSIF INSTR(PGM.CM_DIRPATH,'/com/shc/wink/cc/ch') > 0 THEN      
                    JOBCD := 'CH';      
                ELSIF INSTR(PGM.CM_DIRPATH,'/com/shc/wink/cc') > 0 THEN      
                    JOBCD := 'CC';      
                ELSIF INSTR(PGM.CM_DIRPATH,'/com/shc/wink') > 0 THEN      
                    BEGIN      
                        SELECT NVL(SUBSTR(CM_DIRPATH, INSTR(CM_DIRPATH,'/com/shc/wink')+LENGTH('/com/shc/wink')+4,2),'ADMIN')      
                        INTO   JOBCD      
                        FROM   CMM1600      
                        where  CM_RSRCNAME = PGM.CM_RSRCNAME      
                          AND  CM_DIRPATH = PGM.CM_DIRPATH;      
                    END;      
                ELSIF INSTR(PGM.CM_DIRPATH,'/scripts') > 0 AND INSTR(PGM.CM_RSRCNAME,'BizCommon') > 0 THEN      
                    IF PGM.CM_RSRCNAME != 'BizCommon.js' THEN      
                        JOBCD := SUBSTR(PGM.CM_RSRCNAME, INSTR(PGM.CM_RSRCNAME,'BizCommon')+LENGTH('BizCommon'),2);      
                    END IF;      
                END IF;      
                      
                RSRCCD := 'WEB파일';      
                  
                IF  INSTR(PGM.CM_DIRPATH,'src-com')>0 OR INSTR(PGM.CM_DIRPATH,'src-biz')>0 OR  
				    INSTR(PGM.CM_DIRPATH,'src-bat')>0 OR INSTR(PGM.CM_DIRPATH,'WebContent/system')>0 OR  
					INSTR(PGM.CM_DIRPATH,'src-db')>0  OR INSTR(PGM.CM_DIRPATH,'.istudiometa')>0 OR  
					INSTR(PGM.CM_DIRPATH,'WebContent/form')>0 OR INSTR(PGM.CM_DIRPATH,'WebContent/WEB-INF/lib')>0 OR  
					INSTR(PGM.CM_DIRPATH,'WebContent/edm')>0  OR INSTR(PGM.CM_DIRPATH,'WebContent/jsp')>0 OR  
					INSTR(PGM.CM_DIRPATH,'WebContent/html')>0 OR INSTR(PGM.CM_DIRPATH,'WebContent/resources')>0 THEN  
                      
                    IF INSTR(PGM.CM_DIRPATH,'WebContent/system/custom/js')>0 AND PGM.CM_RSRCNAME='encrypt.js' THEN  
                        RSRCCD := '버전관리';  
                    ELSE  
                        IF INSTR(PGM.CM_DIRPATH,'/.istudiometa') > 0 THEN      
                            RSRCCD := '메타_iStudio';  
                        ELSIF INSTR(PGM.CM_DIRPATH,'/src-db') > 0 THEN      
                            RSRCCD := '메타_PL/SQL';  
                        ELSIF INSTR(PGM.CM_RSRCNAME,'.java',-1,1) > 0 THEN      
                            RSRCCD := 'JAVA';  
                        ELSIF INSTR(PGM.CM_RSRCNAME,'.jar',-1,1) > 0 THEN      
                            RSRCCD := '라이브러리';  
                        ELSIF (INSTR(PGM.CM_DIRPATH,'/src-com') > 0 and INSTR(PGM.CM_RSRCNAME,'.xml',-1,1) > 0) or      
                              (INSTR(PGM.CM_RSRCNAME,'.drl',-1,1) > 0 or INSTR(PGM.CM_RSRCNAME,'.rf',-1,1) > 0) THEN  
                            RSRCCD := '설정파일';  
                        ELSIF INSTR(PGM.CM_RSRCNAME,'.xsl',-1,1) > 0 or INSTR(PGM.CM_RSRCNAME,'.xhtml',-1,1) > 0 or      
                              INSTR(PGM.CM_RSRCNAME,'.xml',-1,1) > 0 or INSTR(PGM.CM_RSRCNAME,'.jsp',-1,1) > 0 THEN  
                            RSRCCD := '화면파일';  
                        ELSIF INSTR(PGM.CM_RSRCNAME,'.rep',-1,1) > 0 THEN  
                            RSRCCD := '리포트파일';  
                        ELSIF INSTR(PGM.CM_RSRCNAME,'.doc',-1,1) > 0 or INSTR(PGM.CM_RSRCNAME,'.docx',-1,1) > 0 or      
                              INSTR(PGM.CM_RSRCNAME,'.ppt',-1,1) > 0 or INSTR(PGM.CM_RSRCNAME,'.pptx',-1,1) > 0 OR       
                              INSTR(PGM.CM_RSRCNAME,'.xls',-1,1) > 0 or INSTR(PGM.CM_RSRCNAME,'.xlsx',-1,1) > 0 THEN      
                            RSRCCD := '문서';  
                        END IF;  
                    END IF;  
                ELSIF PGM.CM_DIRPATH = '/shcsw/swdpt/ecams/agentd/upload/WebContent' THEN  
                    IF INSTR(PGM.CM_RSRCNAME,'.html',-1,1) > 0 THEN  
                        RSRCCD := 'WEB파일';  
                    ELSE  
                        RSRCCD := '버전관리';  
                    END IF;  
                ELSE  
                    RSRCCD := '버전관리';  
                END IF;  
                      
                      
                UPDATE CMM1600 SET CM_SYSCD = SYSCD,       
                                   CM_JOBCD = UPPER(JOBCD),       
                                   CM_EDITOR = 'MASTER',      
                                   CM_STORY = PGM.CM_RSRCNAME,       
                                   CM_RSRCCD = RSRCCD      
                 WHERE CM_RSRCNAME = PGM.CM_RSRCNAME      
                   AND CM_DIRPATH  = PGM.CM_DIRPATH;      
            END IF;      
        END IF;      
    End Loop;      
          
End MAKE_PGMLIST;