-- GENERATED BY QueryOne AT 2021-03-04 14:18:00
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.SVRCD_SEL2        
(ACPTNO IN VARCHAR2,PRCSYS IN VARCHAR2,CMINFO IN VARCHAR2)                           
                                                                                     
RETURN VARCHAR2                                                                        
IS                                                                                   
    CNTVAL NUMBER := 0;     
    RETVAL VARCHAR2(30);   
CURSOR REQ_CUR IS     
    SELECT A.CR_TEAM    
      FROM CMR9900 A    
     WHERE A.CR_ACPTNO=ACPTNO    
       AND A.CR_LOCAT<>'00'    
       AND A.CR_TEAMCD='1'    
       AND A.CR_TEAM IN ('SYSDGB','SYSTGB','SYSGB') 
       AND A.CR_STATUS<>'0' 
       AND A.CR_CONFDATE IS NOT NULL 
     ORDER BY A.CR_CONFDATE DESC;                                                                                        
-- 리턴값 0:처리 1:미처리                                                            
BEGIN     
    RETVAL := NULL;   
    IF SUBSTR(CMINFO,8,1) = '1' THEN 
       RETVAL := '01'; 
    END IF; 
    IF SUBSTR(CMINFO,7,1) = '1' THEN 
        FOR REQ_FET IN REQ_CUR LOOP    
            IF REQ_FET.CR_TEAM = 'SYSDGB' THEN  
               RETVAL := '23'; 
            ELSIF REQ_FET.CR_TEAM = 'SYSTGB' THEN  
               RETVAL := '13'; 
            ELSIF REQ_FET.CR_TEAM = 'SYSGB' THEN  
               RETVAL := '03'; 
            END IF; 
            EXIT;
        END LOOP; 
    END IF; 
     
    IF RETVAL IS NULL THEN 
       RETVAL := 'NO'; 
    END IF;                                                                       
   RETURN RETVAL;                                                                                  
END;