-- GENERATED BY QueryOne AT 2021-03-04 14:18:00
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.SVRCD_SEL3          
(SYSCD IN VARCHAR2,SVRCD IN VARCHAR2,SEQNO IN INTEGER,JOBCD IN VARCHAR2)          
                                                                                       
                                                                                       
RETURN INTEGER                                                                          
IS                                                                                     
    CNTVAL INTEGER := 0;     
    CNCLSTEP VARCHAR2(10);   
    VCNT   INTEGER := 0;   
        
-- 리턴값 0:처리 1:미처리                                                              
BEGIN   
    CNTVAL := 1;   
   BEGIN  
       SELECT COUNT(*) 
         INTO VCNT   
         FROM CMM0030   
        WHERE CM_SYSCD=SYSCD   
          AND SUBSTR(CM_SYSINFO,9,1)='1';   
       EXCEPTION                                          
         WHEN  NO_DATA_FOUND  Then                                          
              VCNT := 0;     
    END;     
    IF VCNT = 0 THEN 
       RETURN 0; 
    END IF; 
    BEGIN  
        SELECT COUNT(*) 
          INTO VCNT 
          FROM CMM0035 
         WHERE CM_SYSCD=SYSCD 
           AND CM_SVRCD=SVRCD 
           AND CM_SEQNO=SEQNO 
           AND CM_JOBCD=JOBCD;  
       EXCEPTION                                          
         WHEN  NO_DATA_FOUND  Then                                          
              VCNT := 0;     
    END;     
    IF VCNT = 0 THEN 
       RETURN 1; 
    ELSE 
       RETURN 0; 
    END IF;                                                                             
END;