-- GENERATED BY QueryOne AT 2021-03-04 14:18:52
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.GYUL_UPDT
(
 Call_Key_AcptNo       IN   Varchar2,
 CONFTEAM              IN   Varchar2)
 IS
 ErrSw              Varchar2 (01);
 Sv_NxtSign         Varchar2 (10);
 DELSYS             Varchar2 (20);
 Sv_NxtConCd        Varchar2 (1);
 CNT                INTEGER;
Begin
    Sv_NxtSign     := '';
    Sv_NxtConCd    := '';
    DELSYS         := '';

    -- SV_NxtConCD Setting
    -- CR_TeamCD  결재구분
    --    1:자동처리,2:본인확인,3:팀내책임자,4:특정팀,5:처리팀,6:팀내책임자2
    --    7:관리자,8:관련팀참조,9:관련팀승인

    Begin
      Select  a.CR_TeamCD,a.CR_TEAM
        Into  SV_NxtConCD,Sv_NxtSign
        From  CMR9900 a,CMR1000 b
       Where  a.CR_AcptNo = Call_Key_AcptNo
         And  a.CR_LOCAT='00'
         And  a.CR_AcptNo = b.CR_AcptNo;
      EXCEPTION
          WHEN NO_DATA_FOUND Then
         Raise_Application_Error (-20021,'결재정보가 없습니다.');         -- 결재 정보가 없을때...
    End;

    IF Sv_NxtSign = CONFTEAM THEN
       DELSYS := CONFTEAM;
    ELSE
        DELSYS := Sv_NxtSign || ',' || CONFTEAM;
        IF Sv_NxtSign = 'SYSRC' AND CONFTEAM <> 'SYSED' THEN
           IF CONFTEAM = 'SYSUA' THEN
              DELSYS := DELSYS || ',SYSUA,SYSGB';
           END IF;
        ELSIF Sv_NxtSign = 'SYSED' AND CONFTEAM = 'SYSUA' THEN
           DELSYS := DELSYS || ',SYSGB';
        END IF;
    END IF;

    dbms_OUTPUT.PUT_LINE('46 Line DELSYS=' || DELSYS);

    DELETE CMR1011
     WHERE CR_ACPTNO=Call_Key_AcptNo
       AND INSTR(DELSYS,CR_PRCSYS)>0;

    UPDATE CMR9900
       SET (CR_TEAM,CR_TEAMCD,CR_CONFNAME,CR_SGNGBN,CR_CONFUSR)
        =
           (SELECT CR_TEAM,CR_TEAMCD,CR_CONFNAME,CR_SGNGBN,CR_LOCAT || CR_LOCAT
              FROM CMR9900
             WHERE CR_ACPTNO=Call_Key_AcptNo
               AND CR_LOCAT<>'00'
               AND CR_TEAM=CONFTEAM)
    WHERE CR_ACPTNO=Call_Key_AcptNo
      AND CR_LOCAT='00';

    UPDATE CMR9900
       SET CR_STATUS='0',
           CR_CONMSG='',
           CR_CONFDATE='',
           CR_CONFUSR=''
     WHERE CR_ACPTNO=Call_Key_AcptNo
       AND CR_LOCAT<>'00'
       AND INSTR(DELSYS,CR_TEAM)>0;

End GYUL_UPDT;