-- GENERATED BY QueryOne AT 2021-03-04 14:18:50
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.CMM0070_UPDATE
(       
 SYSCD               IN   VARCHAR2,
 DIRPATH             IN   VARCHAR2
 )
 IS        
 VDSNCD             VARCHAR2(100);
 VCNT               INTEGER;    
 ROWCNT             INTEGER;    
     
Begin      
    Begin        
        Select  MIN(CM_DSNCD)     
          Into  VDSNCD       
          From  CMM0070  
         Where  CM_SYSCD = SYSCD
           AND  CM_DIRPATH = TRIM(DIRPATH)
           AND  CM_CLSDT IS NULL;
        EXCEPTION        
           WHEN  NO_DATA_FOUND  Then        
              Raise_Application_Error (-20001,'디렉토리 정보 오류.');        
    End;        

    UPDATE  CMR0020
       SET  CR_DSNCD = VDSNCD
      WHERE CR_SYSCD = SYSCD
        AND CR_DSNCD IN (SELECT CM_DSNCD
                           FROM CMM0070
                          WHERE CM_SYSCD = SYSCD
                            AND CM_DIRPATH = TRIM(DIRPATH)
                            AND CM_CLSDT IS NULL
                        );
                           

End CMM0070_UPDATE;