-- GENERATED BY QueryOne AT 2021-03-04 14:18:51
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.ERRDAYCNT
(
 szDiffDT             IN   Varchar2,
 szDiffBefDT          IN   Varchar2)
 IS
 nHoliSW        number;
 nWeekCD        number;
 nCnt           number;

Begin

        nHoliSW := 0;

        nWeekCD := TO_CHAR(TO_DATE(szDiffDT, 'yyyymmdd'), 'D');
        if nWeekCD = 6 then
        --if nWeekCD = 6 or nWeekCD = 7 then
            nHoliSW := 1;
        Elsif nWeekCD = 1 then
            nHoliSW := 0;
        else
            begin
                SELECT COUNT(*)
                  INTO nCnt
                  FROM CMM0050
                 WHERE CM_HOLIDAY = szDiffDT;
                exception
                    when no_data_found then
                        nCnt := 0;
            end;

            if nCnt > 0 then
                nHoliSW := 1;
            end if;
        end if;


        UPDATE  CMD0029 A
           SET  CD_ERRDAYCNT = DECODE(nHoliSW, 0, NVL( (SELECT  NVL(CD_ERRDAYCNT, 0)
                                                          FROM  CMD0029
                                                         WHERE  CD_DIFFDT   = szDiffBefDT
                                                           AND  CD_SVRIP    = A.CD_SVRIP
                                                           AND  CD_PORTNO   = A.CD_PORTNO
                                                           AND  CD_SYSCD    = A.CD_SYSCD
                                                           AND  CD_DIRPATH  = A.CD_DIRPATH
                                                           AND  CD_SVRCD    = A.CD_SVRCD
                                                           AND  CD_RSRCNAME = A.CD_RSRCNAME
                                                           AND  CD_ERRCLSDT IS NULL
                                                        ), 0
                                                      ) + 1
                                                 , NVL( (SELECT  NVL(CD_ERRDAYCNT, 0)
                                                          FROM  CMD0029
                                                         WHERE  CD_DIFFDT   = szDiffBefDT
                                                           AND  CD_SVRIP    = A.CD_SVRIP
                                                           AND  CD_PORTNO   = A.CD_PORTNO
                                                           AND  CD_SYSCD    = A.CD_SYSCD
                                                           AND  CD_DIRPATH  = A.CD_DIRPATH
                                                           AND  CD_SVRCD    = A.CD_SVRCD
                                                           AND  CD_RSRCNAME = A.CD_RSRCNAME
                                                           AND  CD_ERRCLSDT IS NULL
                                                        ), 0
                                                      )
                                      )
          WHERE  CD_DIFFDT = szDiffDT;

END ;