-- GENERATED BY QueryOne AT 2021-03-04 14:17:57
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.PROGEDIT_YN
(ISRID IN VARCHAR2)
RETURN VARCHAR2
IS
   VCNT INT := 0;
 --- 프로그램없이 프로세스만 진행하는 유형여부
BEGIN
        select count(*) cnt
          into VCNT
          from CMM0120 B,CMC0100 A
         where A.CC_SRID=ISRID
           AND A.CC_CATTYPE=B.CM_CATTYPE
           AND B.CM_QRYCD='07'
           AND B.CM_USEYN='N';
         IF VCNT = 0 THEN
            RETURN 'Y';
         ELSE
            --RETURN 'N';
            RETURN 'Y';
         END IF;

end;