-- GENERATED BY QueryOne AT 2021-03-04 14:18:52
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.HISTORY_DELETE
(
 fromSYSCD       IN   Varchar2,
 toSYSCD         IN   Varchar2,
 gbnCD           IN   Varchar2)
 IS
 ErrSw              Varchar2 (01);
Begin
    ErrSw          := NULL;

    delete cmr9920 where cr_acptno in (select cr_acptno from cmr1000
                                        where cr_syscd>=fromSYSCD
                                          and cr_syscd<=toSYSCD);
    delete cmr9910 where cr_acptno in  (select cr_acptno from cmr1000
                                        where cr_syscd>=fromSYSCD
                                          and cr_syscd<=toSYSCD);
    delete cmr9900 where cr_acptno in  (select cr_acptno from cmr1000
                                        where cr_syscd>=fromSYSCD
                                          and cr_syscd<=toSYSCD);
    delete cmr1011 where cr_acptno in  (select cr_acptno from cmr1000
                                        where cr_syscd>=fromSYSCD
                                          and cr_syscd<=toSYSCD);
    delete cmr1030 where cr_acptno in  (select cr_acptno from cmr1000
                                        where cr_syscd>=fromSYSCD
                                          and cr_syscd<=toSYSCD);
    delete cmr1010 where cr_syscd>=fromSYSCD and cr_syscd<=toSYSCD;
    delete cmr0025 where cr_itemid in (select cr_itemid from cmr0020
                                        where cr_syscd>=fromSYSCD
                                          and cr_syscd<=toSYSCD);
    delete cmr0021 where cr_itemid in (select cr_itemid from cmr0020
                                        where cr_syscd>=fromSYSCD
                                          and cr_syscd<=toSYSCD);
    delete cmr0027 where cr_itemid in (select cr_itemid from cmr0020
                                        where cr_syscd>=fromSYSCD
                                          and cr_syscd<=toSYSCD);
                                          
    delete cmm0073 where cm_syscd>=fromSYSCD and cm_syscd<=toSYSCD;
    delete cmm0072 where cm_syscd>=fromSYSCD and cm_syscd<=toSYSCD;
    delete cmm0070 where cm_syscd>=fromSYSCD and cm_syscd<=toSYSCD;
                                      
    delete cmr1000 where cr_syscd>=fromSYSCD
                     and cr_syscd<=toSYSCD;
    IF gbnCD = 'DEL' THEN
       delete cmr0020 where cr_syscd>=fromSYSCD
                        and cr_syscd<=toSYSCD;
    ELSE
       update cmr0020 set cr_lstver=0,cr_status='3'
        where cr_syscd>=fromSYSCD
          and cr_syscd<=toSYSCD;
    END IF;


End HISTORY_DELETE;