-- GENERATED BY QueryOne AT 2021-03-04 14:21:15
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

DROP TABLE ECAMS.CMR1010 CASCADE CONSTRAINTS PURGE;

CREATE TABLE ECAMS.CMR1010
(
    CR_ACPTNO CHAR(12) NOT NULL,
    CR_SERNO NUMBER(5) NOT NULL,
    CR_SYSCD CHAR(5) NULL,
    CR_SYSGB CHAR(1) NULL,
    CR_JOBCD VARCHAR2(5) NULL,
    CR_PRCDATE DATE NULL,
    CR_STATUS CHAR(1) NULL,
    CR_QRYCD CHAR(2) NULL,
    CR_RSRCCD CHAR(2) NULL,
    CR_DSNCD CHAR(7) NULL,
    CR_DSNCD2 VARCHAR2(200) NULL,
    CR_RSRCNAME VARCHAR2(200) NULL,
    CR_RSRCNAM2 VARCHAR2(200) NULL,
    CR_PID NUMBER NULL,
    CR_CHGCD CHAR(1) NULL,
    CR_TSTCHG CHAR(1) NULL,
    CR_SRCCHG CHAR(1) NULL,
    CR_VERSION NUMBER(5) NULL,
    CR_PRIORITY NUMBER NULL,
    CR_APLYDATE VARCHAR2(14) NULL,
    CR_EDITCON VARCHAR2(500) NULL,
    CR_CONFNO CHAR(12) NULL,
    CR_EDITOR VARCHAR2(10) NULL,
    CR_PUTCODE VARCHAR2(5) NULL,
    CR_CNCLYN CHAR(1) NULL,
    CR_SYSSTEP NUMBER NULL,
    CR_OPEN CHAR(1) NULL,
    CR_TMPDELYN CHAR(1) DEFAULT 'Y' NULL,
    CR_BASENO VARCHAR2(12) NULL,
    CR_COACPT VARCHAR2(12) NULL,
    CR_BASEPGM VARCHAR2(3000) NULL,
    CR_BASEDSN CHAR(7) NULL,
    CR_BASEITEM CHAR(12) NULL,
    CR_BEFVER NUMBER(5) NULL,
    CR_ITEMID CHAR(12) NULL,
    CR_LANGCD CHAR(2) NULL,
    CR_PRCSTEP VARCHAR2(50) NULL,
    CR_SRCCMP CHAR(1) NULL,
    CR_CNCLSTEP VARCHAR2(10) NULL,
    CR_ANALYN VARCHAR2(1) NULL,
    CR_PGMTYPE VARCHAR2(2) NULL,
    CR_SUBSYS CHAR(5) NULL,
    CR_SUBDSN CHAR(5) NULL,
    CR_EDITDATE DATE NULL,
    CR_RUNGBN CHAR(1) DEFAULT 'B' NULL,
    CR_VERACPT CHAR(12) NULL,
    CR_SVRYN CHAR(1) DEFAULT 'Y' NULL,
    CR_VERYN CHAR(1) DEFAULT 'Y' NULL,
    CR_REALBEFVER NUMBER(5) DEFAULT 0 NULL,
    CR_MD5SUM VARCHAR2(32) NULL,
    CR_STORY VARCHAR2(1000) NULL,
    CR_FILESIZE NUMBER NULL,
    CR_REALVER NUMBER NULL,
    CR_DOTVER NUMBER NULL,
    CR_DEVVER NUMBER DEFAULT 0 NULL,
    CR_DEVENDDT DATE NULL,
    CR_SECUSTOP CHAR(1) NULL,
    CR_SECURST CHAR(1) NULL,
    CR_PARM VARCHAR2(100) NULL,
    CR_SPARROWCODE CHAR(1) NULL,
    CR_SPARROWURL VARCHAR2(1000) NULL,
    CR_SCRIPTRST VARCHAR2(100) NULL
)
SEGMENT CREATION IMMEDIATE
STORAGE
(
    INITIAL 22M
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01;

CREATE INDEX ECAMS.CMR1010_IDX
ON ECAMS.CMR1010
(
    CR_BASEITEM ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1010_IDX1
ON ECAMS.CMR1010
(
    CR_ITEMID ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1010_IDX2
ON ECAMS.CMR1010
(
    "CR_CONFNO" DESC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1010_IDX3
ON ECAMS.CMR1010
(
    CR_SYSCD ASC,
    CR_DSNCD ASC,
    CR_RSRCNAME ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1010_IDX4
ON ECAMS.CMR1010
(
    CR_BASENO ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1010_IDX5
ON ECAMS.CMR1010
(
    CR_JOBCD ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1010_IDX6
ON ECAMS.CMR1010
(
    CR_QRYCD ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE INDEX ECAMS.CMR1010_IDX7
ON ECAMS.CMR1010
(
    CR_SYSCD ASC,
    CR_DSNCD ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

CREATE UNIQUE INDEX ECAMS.CMR1010_PK
ON ECAMS.CMR1010
(
    CR_ACPTNO ASC,
    CR_SERNO ASC
)
INITRANS 2
STORAGE
(
    INITIAL 128K
    MAXEXTENTS 2147483645
)
TABLESPACE TS_CAM_01
NOCOMPRESS;

ALTER TABLE ECAMS.CMR1010
ADD CONSTRAINT CMR1010_FK01 FOREIGN KEY(CR_ACPTNO)
    REFERENCES ECAMS.CMR1000(CR_ACPTNO);

ALTER TABLE ECAMS.CMR1010
ADD CONSTRAINT CMR1010_PK PRIMARY KEY(CR_ACPTNO,CR_SERNO)
     USING INDEX ECAMS.CMR1010_PK;

CREATE OR REPLACE TRIGGER "ECAMS"."CMR1010_TRG" 
               
BEFORE UPDATE  ON ECAMS.CMR1010                                 
FOR EACH ROW
Declare                          
    V_Ver        CMR0020.cr_lstver%Type;                          
    V_VerBase    CMM0036.CM_VERCNT%Type;                          
    V_TstVer     CMR0020.cr_tstver%Type;                          
    VAcptNo      CMR1010.cr_acptno%Type;                            
    VNOTIFY      CMR1000.cr_NOTIFY%Type; 
    VRETRYYN     CMR1000.CR_RETRYYN%TYPE;
    V_AcptDate   CMR1000.cr_ACPTDATE%Type;                  
    V_MD5SUM     CMR0020.CR_MD5SUM%TYPE;               
    V_FILESIZE   CMR0020.CR_FILESIZE%TYPE;               
    V_FILEDATE   CMR0020.CR_FILEDATE%TYPE;               
                   
    VCnt          Integer;                          
    VSta          Char(1);                          
    VTeam         Varchar2 (10);                  
    SCRSW         CHAR(1);               
    V_LinkUrl     Varchar2(200);                
    V_SRYN        CHAR(1);               
    V_VERCNT      INTEGER;               
    V_REALVER     INTEGER;               
    V_ITSMID      VARCHAR2(50);               
    V_MSGACPT     VARCHAR2(50);               
    V_DOTVER      VARCHAR2(50);      
    V_NEXTREQ     VARCHAR2(50);
                              
 Begin
 
                  
 -- 자원처리완료시 처리                          
   IF (:OLD.CR_PUTCODE IS NULL OR :OLD.CR_PUTCODE = '0000') AND                           
      (:NEW.CR_PUTCODE IS NOT NULL AND :NEW.CR_PUTCODE <> '0000') THEN                          
      BEGIN                          
         SELECT NVL(CR_NOTIFY,'N'),CR_ACPTDATE,CR_ITSMID,NVL(CR_RETRYYN,'Y')                          
           INTO VNOTIFY, V_AcptDate,V_ITSMID,VRETRYYN                          
           FROM CMR1000                          
          WHERE CR_ACPTNO=:NEW.CR_ACPTNO;                          
            EXCEPTION                          
                 WHEN NO_DATA_FOUND THEN                          
                      VNOTIFY := 'N';                          
      END;          
       
      V_MSGACPT := '요청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7,6);                 
--      IF V_ITSMID IS NULL THEN               
--         V_MSGACPT := '신청번호: ' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7,6);               
--      ELSE               
--         V_MSGACPT := 'SR-ID: ' || V_ITSMID;               
--      END IF;           
                     
      IF VNOTIFY = 'N' OR VRETRYYN = 'Y' THEN                          
         SELECT CM_URL                 
         INTO V_LinkUrl                 
         FROM CMM0010                 
        WHERE CM_STNO='ECAMS';                 
                         
         V_LinkUrl := V_LinkUrl || 'ecams_win_flex/';                  
         IF substr(:NEW.cr_acptno,5,2) = '01' or substr(:NEW.cr_acptno,5,2) = '02' or substr(:NEW.cr_acptno,5,2) = '11' or substr(:NEW.cr_acptno,5,2) = '12' THEN                  
            V_LinkUrl := V_LinkUrl || 'eCmr0150.jsp?ReqNo=' || :NEW.CR_ACPTNO;                  
         ELSIF substr(:NEW.cr_acptno,5,2) = '03' or substr(:NEW.cr_acptno,5,2) = '04' or substr(:NEW.cr_acptno,5,2) = '05' or substr(:NEW.cr_acptno,5,2) = '06' or substr(:NEW.cr_acptno,5,2) = '07' or substr(:NEW.cr_acptno,5,2) = '16' THEN                  
            V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;                 
         END IF;                   
         
         IF :OLD.CR_SCRIPTRST IS NOT NULL OR :NEW.CR_SCRIPTRST IS NOT NULL THEN
             INSERT INTO CMR9910                           
                (CR_CONUSR,CR_SENDDATE,CR_STATUS,CR_SENDUSR,CR_SGNMSG,CR_ACPTNO,CR_TITLE,CR_LINKURL,CR_NOTIGBN,CR_NOTICD,CR_SMSMSG)                          
                (SELECT DISTINCT CM_USERID,SYSDATE,'0',:NEW.CR_EDITOR,                          
                    '[중요 : 오류발생]' || chr(13) ||                           
                    '1. 요청일 : ' || to_char(V_AcptDate,'yyyy/mm/dd') || chr(13) ||                          
                    '2. ' || V_MSGACPT || Chr(13) ||                          
                    '   eCAMS처리 중 오류가 발생하였습니다. eCAMS접속하여 처리결과를 확인 후' || chr(13) ||                          
                    '   조치하시기 바랍니다.',:NEW.CR_ACPTNO,                         
                    '형상관리시스템 요청건 처리 중 오류발생 알림',                        
                    V_LinkUrl,'ER','SMS',                                      
                    '[형상관리오류발생]' || CHR(10) ||               
                    '요청일:' || to_char(V_AcptDate,'yyyy/mm/dd') || chr(10) ||                 
                    V_MSGACPT || chr(10) ||  
                    '오류코드:' || :NEW.CR_SCRIPTRST
                  FROM CMM0040 A,CMM0020 B                          
                 WHERE A.CM_USERID = :NEW.CR_EDITOR               
                   AND B.CM_MACODE='REQUEST'               
                   AND B.CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));   
         ELSE
             INSERT INTO CMR9910                           
                (CR_CONUSR,CR_SENDDATE,CR_STATUS,CR_SENDUSR,CR_SGNMSG,CR_ACPTNO,CR_TITLE,CR_LINKURL,CR_NOTIGBN,CR_NOTICD,CR_SMSMSG)                          
                (SELECT DISTINCT CM_USERID,SYSDATE,'0',:NEW.CR_EDITOR,                          
                    '[중요 : 오류발생]' || chr(13) ||                           
                    '1. 요청일 : ' || to_char(V_AcptDate,'yyyy/mm/dd') || chr(13) ||                          
                    '2. ' || V_MSGACPT || Chr(13) ||                          
                    '   eCAMS처리 중 오류가 발생하였습니다. eCAMS접속하여 처리결과를 확인 후' || chr(13) ||                          
                    '   조치하시기 바랍니다.',:NEW.CR_ACPTNO,                         
                    '형상관리시스템 요청건 처리 중 오류발생 알림',                        
                    V_LinkUrl,'ER','SMS',                                      
                    '[형상관리 ' || B.CM_CODENAME || ' 오류발생]' || CHR(10) ||               
                    '1.요청일:' || to_char(V_AcptDate,'yyyy/mm/dd') || chr(10) ||                 
                    '2.' || V_MSGACPT
                  FROM CMM0040 A,CMM0020 B                          
                 WHERE A.CM_USERID = :NEW.CR_EDITOR               
                   AND B.CM_MACODE='REQUEST'               
                   AND B.CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));   
         END IF;
                                       
         UPDATE CMR1000                          
            SET CR_NOTIFY='Y',CR_RETRYYN='N'                          
          WHERE CR_ACPTNO=:NEW.CR_ACPTNO;                                                      
      END IF;                                 
   END IF;                          
   IF :NEW.cr_prcdate is not null and :OLD.cr_prcdate is null and :NEW.cr_status <> '3' and :NEW.cr_itemid is not null then   
      IF (substr(:NEW.cr_acptno,5,2)='04' or    -- 운영적용요청
          substr(:NEW.cr_acptno,5,2)='06' or    -- Roll-Back                          
          substr(:NEW.cr_acptno,5,2)='16')      -- 일괄등록                          
         AND :NEW.cr_srcchg='1' AND :NEW.cr_qrycd<>'09' AND :NEW.CR_QRYCD<>'05' THEN             
         Begin    
             SELECT    A.cr_LstVer,SUBSTR(B.CM_SYSINFO,10,1),C.CM_VERCNT,NVL(A.CR_REALVER,0)                       
                INTO    V_Ver,V_SRYN,V_VERCNT,V_REALVER                         
                FROM    CMR0020 A,CMM0030 B,CMM0036 C                          
                WHERE   A.CR_ITEMID=:NEW.cr_ITEMID               
                  AND   A.CR_SYSCD=B.CM_SYSCD               
                  AND   A.CR_SYSCD=C.CM_SYSCD               
                  AND   A.CR_RSRCCD=C.CM_RSRCCD;                          
                EXCEPTION                          
                   WHEN NO_DATA_FOUND THEN                          
                        V_Ver := 1;                          
         END;          
            
         IF V_Ver >= V_VERCNT THEN               
            V_Ver := 1;               
         ELSE               
            V_Ver := V_Ver + 1;               
         END IF; 
         
         IF substr(:NEW.cr_acptno,5,2)='16' THEN
            IF :NEW.cr_version = 0 THEN                          
               VSta := '3';  
               V_Ver := 0;
            ELSE                   
               VSta := '0';  
               V_Ver := 1;
            END IF;
         ELSE                          
            VSta := '0';                          
         END IF;      
                            
        UpDate  CMR0020                          
           Set  cr_status=DECODE(V_Ver,0,'3','0'),                          
                cr_lastdate=SYSDATE,
                CR_LSTVER=V_Ver,
                CR_LSTUSR=:NEW.CR_EDITOR,
                CR_LSTDAT=SYSDATE,
                CR_ACPTNO=:NEW.CR_ACPTNO,
                CR_REALACPT=:NEW.CR_ACPTNO,               
                CR_REALUSR=:NEW.CR_EDITOR,               
                CR_REALDATE=SYSDATE,               
                CR_REALDEP=V_Ver,               
                CR_REALVER=V_Ver              
         Where  CR_ITEMID=:NEW.cr_ITEMID;           
                                            
        BEGIN                          
          SELECT COUNT(*)                          
            INTO Vcnt                          
            FROM CMM0036                          
           WHERE Cm_Syscd = :NEW.cr_syscd                          
             AND CM_Rsrccd = :NEW.cr_rsrccd                          
             AND SUBSTR(Cm_info,12,1)='1';                          
          EXCEPTION                          
               WHEN NO_DATA_FOUND THEN                          
                    Vcnt := 1;                          
        END; 
        
        IF substr(:NEW.cr_acptno,5,2)='16' THEN                          
            BEGIN                                
                DELETE CMR0025                          
                 WHERE CR_ITEMID = :NEW.cr_ITEMID;                            
            END;  
        ELSE                           
            BEGIN                                            
                DELETE CMR0025                                        
                 WHERE CR_ITEMID = :NEW.cr_ITEMID                          
                   AND CR_VER    = V_Ver;                          
            END;          
        END IF;                 
                      
        IF Vcnt > 0 AND V_Ver > 0 THEN                
           V_MD5SUM := NULL;               
               
           BEGIN               
               SELECT CR_MD5SUM, CR_FILESIZE, CR_FILEDATE               
                 INTO V_MD5SUM,  V_FILESIZE,  V_FILEDATE               
                 FROM CMR0027                          
                WHERE CR_ACPTNO = :NEW.cr_acptno               
                  AND CR_ITEMID = :NEW.cr_ITEMID;                                     
               EXCEPTION                          
                   WHEN NO_DATA_FOUND THEN                          
                        Raise_Application_Error (-20020,'[CMR0027] 원장생성오류.');                        
           END; 
           
           BEGIN
              UPDATE CMR0020               
                 SET CR_MD5SUM=V_MD5SUM,               
                     CR_FILESIZE=V_FILESIZE,               
                     CR_FILEDATE=V_FILEDATE,               
                     CR_REALMD5=V_MD5SUM,               
                     CR_REALSIZE=V_FILESIZE               
                WHERE CR_ITEMID=:NEW.CR_ITEMID;                    
                                   
               Insert into CMR0025
                    (CR_VER , CR_ITEMID,CR_ACPTNO, CR_FILE,CR_MD5SUM, CR_FILESIZE,CR_FILEDATE,CR_PRCDATE)                              
                    (SELECT V_Ver,  :NEW.CR_ITEMID , :NEW.cr_acptno, CR_FILE, CR_MD5SUM, CR_FILESIZE, CR_FILEDATE, SYSDATE                
                       FROM CMR0027                          
                      WHERE CR_ACPTNO = :NEW.cr_acptno               
                        AND CR_ITEMID = :NEW.cr_ITEMID);  
           End;                   
                               
            SELECT COUNT(*)                  
              INTO VCNT                  
              FROM CMR0025                  
             WHERE CR_ACPTNO=:NEW.cr_acptno                    
               AND CR_ITEMID=:NEW.cr_ITEMID;                  
            IF VCNT = 0 THEN                  
               Raise_Application_Error (-20021,'원장생성이 정확하게 되지 않았습니다.');                        
            END IF;                  
                           
            SELECT COUNT(*)                  
              INTO VCNT                  
              FROM CMR0025                  
             WHERE CR_ACPTNO=:NEW.cr_acptno                    
               AND CR_ITEMID=:NEW.cr_ITEMID                  
               AND CR_FILE IS NULL;                  
            IF VCNT > 0 THEN                  
               Raise_Application_Error (-20022,'원장생성이 정확하게 되지 않았습니다.');                        
            END IF;
            
            BEGIN                          
               Delete CMR0027                           
                WHERE CR_ITEMID = :NEW.cr_ITEMID                 
                  AND CR_ACPTNO = :NEW.cr_acptno;                          
            End;        
         END IF;                          
                                   
         IF substr(:NEW.cr_acptno,5,2)='16' THEN                          
            BEGIN                                
                DELETE CMR0021                          
                 WHERE CR_ITEMID = :NEW.cr_ITEMID;                            
            END;     
         ELSE                         
            BEGIN                                
                DELETE CMR0021                          
                 WHERE CR_ITEMID = :NEW.cr_ITEMID
                   AND CR_ACPTNO = :NEW.CR_ACPTNO;                            
            END;
         END IF;                          
         
         IF V_Ver > 0 THEN                      
            BEGIN                               
                INSERT INTO CMR0021                          
                      (CR_ITEMID,   cr_AcptNo, cr_VER, cr_qrycd, cr_acptdate, cr_editor,cr_prcdate,         
                       cr_realver,cr_dotver)                          
                VALUES                          
                      (:NEW.CR_ITEMID,  :NEW.cr_AcptNo, V_Ver, substr(:NEW.cr_acptno,5,2), SYSDATE, :NEW.cr_editor,SYSDATE,        
                       V_Ver,V_Ver);                          
            END;                          
         END IF;                          
      END IF;                        
      IF substr(:NEW.cr_acptno,5,2) = '01' OR substr(:NEW.cr_acptno,5,2) = '02' THEN                          
            BEGIN      -- 체크아웃(Down-Load), 이전버전체크아웃                          
               UpDate  CMR0020                          
                  Set  cr_status='5',                          
                       cr_clsdate='',                      
                       cr_lastdate=SYSDATE,                         
                       cr_editor=:NEW.cr_editor,               
                       cr_ckoutacpt=:NEW.cr_acptno,               
                       cr_ckoutuser=:NEW.cr_editor               
               Where   CR_ITEMID = :NEW.cr_ITEMID;                          
            END;                          
      END IF;                  
      IF substr(:NEW.cr_acptno,5,2) = '03' THEN     --테스트배포                             
         BEGIN                                 
            UpDate  CMR0020                          
               Set  CR_STATUS='G',               
                    cr_testdate=SYSDATE,                          
                    cr_testusr=:NEW.cr_editor,               
                    cr_testacpt=:NEW.cr_acptno,            
                    CR_TESTMD5=:NEW.CR_MD5SUM,               
                    CR_TESTSIZE=:NEW.CR_FILESIZE               
            Where   CR_ITEMID = :NEW.cr_ITEMID; 
         END; 
      END IF;                         
      IF substr(:NEW.cr_acptno,5,2) = '04' THEN      --운영배포    
         IF :NEW.CR_QRYCD = '09' THEN                --무수정
            BEGIN                                 
                UpDate  CMR0020                          
                Set     cr_NOMODIFY='0', 
                        CR_LASTDATE = SYSDATE
                Where   CR_ITEMID = :NEW.cr_ITEMID;                          
             END; 
         END IF; 
      END IF;                           
      IF substr(:NEW.cr_acptno,5,2) = '05' THEN      --폐기  
        BEGIN                                 
            UpDate  CMR0020                          
            Set     cr_STATUS='9', 
                    CR_CLSDATE = SYSDATE
            Where   CR_ITEMID = :NEW.cr_ITEMID;                          
         END;  
         BEGIN                               
            INSERT INTO CMR0021                          
                  (CR_ITEMID,   cr_AcptNo, cr_VER, cr_qrycd, cr_acptdate, cr_editor,cr_prcdate,         
                   cr_realver,cr_dotver)                          
            VALUES                          
                  (:NEW.CR_ITEMID,  :NEW.cr_AcptNo, :NEW.cr_version, substr(:NEW.cr_acptno,5,2), SYSDATE, :NEW.cr_editor,SYSDATE,        
                   :NEW.cr_version,:NEW.cr_version);                          
        END;  
      END IF;                     
      IF substr(:NEW.cr_acptno,5,2) = '11' THEN   -- 체크아웃취소                         
         BEGIN
            UpDate  CMR0020                          
               Set  cr_status=DECODE(CR_LSTVER,0,'3','0'),       
                    cr_lastdate=SYSDATE,                         
                    cr_editor=:NEW.cr_editor,
                    cr_isrid=''
            Where   CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                           
      END IF;                          
      IF substr(:NEW.cr_acptno,5,2) = '12' THEN   --테스트적용취소                          
         DELETE CMR0027                          
          WHERE CR_ITEMID = :NEW.cr_ITEMID                 
            AND CR_ACPTNO = :NEW.cr_confno;                          
                                    
         BEGIN                          
            UpDate  CMR0020                          
            Set     cr_status=DECODE(CR_LSTVER,0,'3','5'),                    
                    cr_lastdate=SYSDATE,                           
                    cr_editor=:NEW.cr_editor                          
            Where   CR_ITEMID = :NEW.cr_ITEMID;                          
         END;               
      END IF;                          
   End if;                          
   -- 자원처리반송시 처리                          
   IF :NEW.cr_status = '3' and :OLD.cr_status <> '3' and :NEW.cr_itemid is not null then                          
      -- 체크아웃(DOWN),이전버전체크아웃                          
      IF substr(:NEW.cr_acptno,5,2) = '01' or substr(:NEW.cr_acptno,5,2) = '02'  then                          
         BEGIN                          
           UPDATE CMR0020                          
              SET cr_status='0', 
                  cr_isrid='',
                  cr_lastdate=SYSDATE                           
            WHERE CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                          
      END IF;                      
      -- 테스트적용요청                         
      IF substr(:NEW.cr_acptno,5,2) = '03' THEN                               
         BEGIN               
            UpDate CMR0020                          
               Set CR_STATUS=DECODE(CR_LSTVER,0,'3','5')                
             Where CR_ITEMID = :NEW.cr_ITEMID;  
             
             DELETE CMR0027
              WHERE CR_ACPTNO=:NEW.CR_ACPTNO
                AND CR_ITEMID=:NEW.CR_ITEMID;
         END;                   
      END IF;                              
      IF substr(:NEW.cr_acptno,5,2) = '04' THEN
         IF :NEW.CR_QRYCD = '09' THEN                       
             BEGIN                  
                UpDate  CMR0020                          
                   Set  CR_NOMODIFY='0'               
                 Where  CR_ITEMID = :NEW.cr_ITEMID;                      
             END;                 
         ELSE                       
             BEGIN                  
                UpDate  CMR0020                          
                   Set  CR_STATUS=CR_SAVESTA               
                 Where  CR_ITEMID = :NEW.cr_ITEMID;  
             
                 DELETE CMR0027
                  WHERE CR_ACPTNO=:NEW.CR_ACPTNO
                    AND CR_ITEMID=:NEW.CR_ITEMID;                    
             END;                 
         END IF;           
      END IF;                             
      IF substr(:NEW.cr_acptno,5,2) = '05' THEN
          BEGIN                  
             UpDate  CMR0020                          
               Set  CR_STATUS='0'               
             Where  CR_ITEMID = :NEW.cr_ITEMID;                
          END;  
      END IF;      
      IF substr(:NEW.cr_acptno,5,2) = '16' THEN                          
         BEGIN                        
            Delete From CMR0027                           
             WHERE CR_ITEMID = :NEW.cr_ITEMID                 
               AND CR_ACPTNO = :NEW.cr_acptno; 
                                  
              UPDATE CMR0020                          
                 SET cr_status=DECODE(CR_LSTVER,0,'3','0')        
               WHERE CR_ITEMID = :NEW.cr_ITEMID;         
         END;                          
      END IF;                          
      IF substr(:NEW.cr_acptno,5,2) = '11' then                          
         BEGIN                          
           UPDATE CMR0020                          
              SET cr_status=CR_SAVESTA,               
                  cr_lastdate=SYSDATE                           
            WHERE CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                                     
      END IF;                          
      IF substr(:NEW.cr_acptno,5,2) = '06' then                          
         BEGIN                          
           UPDATE CMR0020                          
              SET cr_status='0',                          
                  cr_nomodify='0'                        
            WHERE CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                      
                          
         Delete From CMR0027                           
             WHERE CR_ITEMID = :NEW.cr_ITEMID                 
               AND CR_ACPTNO = :NEW.cr_acptno;                    
      END IF;                          
      IF substr(:NEW.cr_acptno,5,2) = '12' then 
         BEGIN                          
           UPDATE CMR0020                          
              SET cr_status=DECODE(CR_LSTVER,'3','5'),                          
                  cr_nomodify='0',                    
                  cr_lastdate=SYSDATE                          
            WHERE CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                          
      END IF;                          
   END IF;                          
End CMR1010_Trg;
/

COMMENT ON TABLE ECAMS.CMR1010 IS '프로그램 변경신청 내역';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SCRIPTRST IS '스크립트실행결과';

COMMENT ON COLUMN ECAMS.CMR1010.CR_ACPTNO IS '신청번호';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SERNO IS 'SERNO';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SYSCD IS '시스템코드';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SYSGB IS '시스템구분';

COMMENT ON COLUMN ECAMS.CMR1010.CR_JOBCD IS '업무영역';

COMMENT ON COLUMN ECAMS.CMR1010.CR_PRCDATE IS '처리완료일시';

COMMENT ON COLUMN ECAMS.CMR1010.CR_STATUS IS '상태 (0:신청중,3:반송,8:처리완료,9:완전종료)';

COMMENT ON COLUMN ECAMS.CMR1010.CR_QRYCD IS '신청구분';

COMMENT ON COLUMN ECAMS.CMR1010.CR_RSRCCD IS '자원구분(CMM0020.CM_MACODE=JAWON+SYSGB)';

COMMENT ON COLUMN ECAMS.CMR1010.CR_DSNCD IS '디렉토리코드';

COMMENT ON COLUMN ECAMS.CMR1010.CR_DSNCD2 IS '디렉토리코드(PC)';

COMMENT ON COLUMN ECAMS.CMR1010.CR_RSRCNAME IS '파일명';

COMMENT ON COLUMN ECAMS.CMR1010.CR_RSRCNAM2 IS '파일명';

COMMENT ON COLUMN ECAMS.CMR1010.CR_PID IS '처리 Process ID';

COMMENT ON COLUMN ECAMS.CMR1010.CR_CHGCD IS 'REAL과비교후처리(1:비교,8:상이,9:버전업)';

COMMENT ON COLUMN ECAMS.CMR1010.CR_TSTCHG IS 'TEST과비교후처리(1:비교,2:상이,7:DOWN NO)';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SRCCHG IS '소스변경여부';

COMMENT ON COLUMN ECAMS.CMR1010.CR_VERSION IS '버전 (이전버전 CO시)';

COMMENT ON COLUMN ECAMS.CMR1010.CR_PRIORITY IS '우선순위';

COMMENT ON COLUMN ECAMS.CMR1010.CR_APLYDATE IS '적용지정일시';

COMMENT ON COLUMN ECAMS.CMR1010.CR_EDITCON IS '수정내용';

COMMENT ON COLUMN ECAMS.CMR1010.CR_CONFNO IS '신청번호2';

COMMENT ON COLUMN ECAMS.CMR1010.CR_EDITOR IS '요청자';

COMMENT ON COLUMN ECAMS.CMR1010.CR_PUTCODE IS '파일Copy결과';

COMMENT ON COLUMN ECAMS.CMR1010.CR_CNCLYN IS '취소여부';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SYSSTEP IS '시스템처리단계별Step';

COMMENT ON COLUMN ECAMS.CMR1010.CR_OPEN IS '신규여부';

COMMENT ON COLUMN ECAMS.CMR1010.CR_TMPDELYN IS '빌드처리용 TEMPORARY파일 삭제여부';

COMMENT ON COLUMN ECAMS.CMR1010.CR_BASENO IS '기준신청번호';

COMMENT ON COLUMN ECAMS.CMR1010.CR_COACPT IS '체크아웃번호';

COMMENT ON COLUMN ECAMS.CMR1010.CR_BASEPGM IS '기준프로그램';

COMMENT ON COLUMN ECAMS.CMR1010.CR_BASEDSN IS '기준프로그램디렉토리';

COMMENT ON COLUMN ECAMS.CMR1010.CR_BASEITEM IS '기준프로그램ID';

COMMENT ON COLUMN ECAMS.CMR1010.CR_BEFVER IS '현재버전';

COMMENT ON COLUMN ECAMS.CMR1010.CR_ITEMID IS '프로그램ID';

COMMENT ON COLUMN ECAMS.CMR1010.CR_LANGCD IS '언어코드';

COMMENT ON COLUMN ECAMS.CMR1010.CR_PRCSTEP IS '처리단계';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SRCCMP IS '처리대상여부';

COMMENT ON COLUMN ECAMS.CMR1010.CR_CNCLSTEP IS '반려단계';

COMMENT ON COLUMN ECAMS.CMR1010.CR_ANALYN IS '영향분석툴';

COMMENT ON COLUMN ECAMS.CMR1010.CR_PGMTYPE IS '프로그램유형';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SUBSYS IS '서브시스템';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SUBDSN IS '서브디렉토리코드';

COMMENT ON COLUMN ECAMS.CMR1010.CR_EDITDATE IS '프로그램정보수정일시';

COMMENT ON COLUMN ECAMS.CMR1010.CR_RUNGBN IS '스크립트실행시점구분';

COMMENT ON COLUMN ECAMS.CMR1010.CR_VERACPT IS '배포버전신청번호';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SVRYN IS '서버적용여부';

COMMENT ON COLUMN ECAMS.CMR1010.CR_VERYN IS '버전업여부';

COMMENT ON COLUMN ECAMS.CMR1010.CR_REALBEFVER IS '운영직전버전';

COMMENT ON COLUMN ECAMS.CMR1010.CR_MD5SUM IS 'md5sum';

COMMENT ON COLUMN ECAMS.CMR1010.CR_STORY IS '프로그램설명';

COMMENT ON COLUMN ECAMS.CMR1010.CR_FILESIZE IS '파일SIZE';

COMMENT ON COLUMN ECAMS.CMR1010.CR_REALVER IS '신청REALVER';

COMMENT ON COLUMN ECAMS.CMR1010.CR_DOTVER IS '신청DOTVER';

COMMENT ON COLUMN ECAMS.CMR1010.CR_DEVENDDT IS '개발완료일시';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SECUSTOP IS '취약점STOP';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SECURST IS '취약점결';

COMMENT ON COLUMN ECAMS.CMR1010.CR_PARM IS '파라미터';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SPARROWCODE IS '프로그램별 취약점 코드 확인 (0:미달 1:정상 2:대상아님 9:수행정지))';

COMMENT ON COLUMN ECAMS.CMR1010.CR_SPARROWURL IS '취약점 분석 결과확인 링트 URL';