-- GENERATED BY QueryOne AT 2021-03-04 14:18:50
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.CMM0060_STR
(
 ACPTNO                IN   VARCHAR2)
 IS
 ErrSw              Varchar2 (01);
 SV_RSRCCD          Varchar2 (100);
 SV_CHKYN           VARCHAR2 (1);
 SV_SGNGBN          VARCHAR2 (1);
 SV_SYSCD           VARCHAR2 (5);
 SV_REQCD           VARCHAR2 (2);
 SV_EDITOR          VARCHAR2 (10);
 WK_RSRCCD          VARCHAR2 (2);
 SV_CLOSEYN         VARCHAR2 (1);
 VCNT               INTEGER;
 ROWCNT             INTEGER;

CURSOR  REQLIST  IS
     Select CR_RSRCCD RSRCCD,CR_QRYCD
       From CMR1010
      Where CR_ACPTNO=ACPTNO
        And CR_PRCDATE IS NULL
      UNION
     SELECT C.CM_SAMERSRC RSRCCD,A.CR_QRYCD
       FROM CMR1010 A,CMM0036 B,CMM0037 C
      WHERE A.CR_ACPTNO=ACPTNO
        AND A.CR_PRCDATE IS NULL
        AND A.CR_SYSCD=B.CM_SYSCD
        AND A.CR_RSRCCD=B.CM_RSRCCD
        AND SUBSTR(B.CM_INFO,4,1)='1'
        AND B.CM_SYSCD=C.CM_SYSCD
        AND B.CM_RSRCCD=C.CM_RSRCCD
        AND C.CM_FACTCD='04'
      UNION
     SELECT C.CM_SAMERSRC RSRCCD,A.CR_QRYCD
       FROM CMR1010 A,CMM0036 B,CMM0037 C
      WHERE A.CR_ACPTNO=ACPTNO
        AND A.CR_PRCDATE IS NULL
        AND A.CR_SYSCD=B.CM_SYSCD
        AND A.CR_RSRCCD=B.CM_RSRCCD
        AND SUBSTR(B.CM_INFO,9,1)='1'
        AND B.CM_SYSCD=C.CM_SYSCD
        AND B.CM_RSRCCD=C.CM_RSRCCD
        AND C.CM_FACTCD='09';

CURSOR  CONFLIST  IS
     Select A.CM_GUBUN,A.CM_RSRCCD,A.CM_MANID,A.CM_SEQNO,A.CM_JOBCD
       From CMM0060 A,CMM0040 B
      Where A.CM_SYSCD=SV_SYSCD
        AND A.CM_REQCD=SV_REQCD
        AND B.CM_USERID=SV_EDITOR
        AND A.CM_MANID=decode(B.CM_MANID,'N','2','1')
--        AND A.CM_JOBCD=DECODE(SV_CLOSEYN,'Y','SYSCL',A.CM_JOBCD)
      ORDER BY CM_SEQNO;

Begin
    SV_CHKYN := 'N';
    Begin
        Select  CR_SYSCD,CR_QRYCD,CR_EDITOR,NVL(CR_CLOSEYN,'N')
          Into  SV_SYSCD,SV_REQCD,SV_EDITOR,SV_CLOSEYN
          From  CMR1000
         Where  CR_ACPTNO=ACPTNO;
        EXCEPTION
           WHEN  NO_DATA_FOUND  Then
              Raise_Application_Error (-20001,'신청정보가 없습니다.');
    End;

    For LIST1 In REQLIST  Loop
        IF SV_RSRCCD IS NOT NULL THEN
           IF INSTR(SV_RSRCCD,LIST1.RSRCCD)=0 THEN
              SV_RSRCCD := SV_RSRCCD || ',' || LIST1.RSRCCD;
           END IF;
        ELSE
           SV_RSRCCD := LIST1.RSRCCD;
        END IF;
    End Loop;

    ROWCNT := 0;
    For CONF1 In CONFLIST  Loop
        SV_CHKYN := 'Y';

        IF SV_CLOSEYN = 'N' AND CONF1.CM_GUBUN = '1' AND CONF1.CM_JOBCD = 'SYSCL' THEN
           SV_CHKYN := 'N';
        END IF;

        IF SV_CHKYN = 'Y' THEN
            IF CONF1.CM_RSRCCD IS NOT NULL THEN
                dbms_OUTPUT.PUT_LINE('64 Line' || CONF1.CM_RSRCCD || chr(13));
               SELECT SUM(CNT)
                 INTO VCNT
                 FROM (
                   Select COUNT(*) CNT
                       From CMR1010
                      Where CR_ACPTNO=ACPTNO
                        And CR_PRCDATE IS NULL
                        AND INSTR(CONF1.CM_RSRCCD,CR_RSRCCD)>0
                      UNION ALL
                     SELECT COUNT(*) CNT
                       FROM CMR1010 A,CMM0036 B,CMM0037 C
                      WHERE A.CR_ACPTNO=ACPTNO
                        AND A.CR_PRCDATE IS NULL
                        AND A.CR_SYSCD=B.CM_SYSCD
                        AND A.CR_RSRCCD=B.CM_RSRCCD
                        AND SUBSTR(B.CM_INFO,4,1)='1'
                        AND B.CM_SYSCD=C.CM_SYSCD
                        AND B.CM_RSRCCD=C.CM_RSRCCD
                        AND INSTR(CONF1.CM_RSRCCD,C.CM_SAMERSRC)>0);
               IF VCNT = 0 THEN
                  SV_CHKYN := 'N';
               END IF;
            END IF;
        END IF;
        IF SV_CHKYN = 'Y' THEN
           IF CONF1.CM_GUBUN = '1' THEN
              IF CONF1.CM_JOBCD = 'SYSPF' THEN
                 SELECT COUNT(*)
                   INTO VCNT
                   FROM CMM0036
                  WHERE CM_SYSCD=SV_SYSCD
                    AND CM_CLOSEDT IS NULL
                    AND INSTR(SV_RSRCCD,CM_RSRCCD)>0
                    AND (substr(cm_info,27,1)='1' or
                         substr(cm_info,4,1)='1' or
                         (substr(cm_info,9,1)='1' and substr(cm_info,36,1)='0'));
              ELSIF CONF1.CM_JOBCD = 'SYSCB' THEN
                 SELECT COUNT(*)
                   INTO VCNT
                   FROM CMM0036
                  WHERE CM_SYSCD=SV_SYSCD
                    AND CM_CLOSEDT IS NULL
                    AND INSTR(SV_RSRCCD,CM_RSRCCD)>0
                    AND (substr(cm_info,DECODE(SV_REQCD,'04',1,39),1)='1' or substr(cm_info,DECODE(SV_REQCD,'04',13,42),1)='1');
              ELSIF CONF1.CM_JOBCD = 'SYSGB' THEN
                 SELECT COUNT(*)
                   INTO VCNT
                   FROM CMM0036
                  WHERE CM_SYSCD=SV_SYSCD
                    AND CM_CLOSEDT IS NULL
                    AND INSTR(SV_RSRCCD,CM_RSRCCD)>0
                    AND substr(cm_info,25,1)='1';
              ELSIF CONF1.CM_JOBCD = 'SYSED' THEN
                 SELECT COUNT(*)
                   INTO VCNT
                   FROM CMM0036
                  WHERE CM_SYSCD=SV_SYSCD
                    AND CM_CLOSEDT IS NULL
                    AND INSTR(SV_RSRCCD,CM_RSRCCD)>0
                    AND (substr(cm_info,DECODE(SV_REQCD,'04',11,49),1)='1' or substr(cm_info,DECODE(SV_REQCD,'04',21,51),1)='1');
              ELSIF CONF1.CM_JOBCD = 'ANALCHK' THEN
                 VCNT := 0;
              ELSE
                 VCNT := 1;
              END IF;
           ELSE
              VCNT := 1;
           END IF;
           IF VCNT > 0 THEN
              ROWCNT := ROWCNT + 1;
              dbms_OUTPUT.PUT_LINE('126 Line' || ROWCNT || ', ' || SV_SYSCD || ', ' || SV_REQCD || ', ' || CONF1.CM_MANID ||  ', ' || CONF1.CM_SEQNO || chr(13));
              INSERT INTO CMR9900
                     (CR_ACPTNO,CR_SEQNO,CR_LOCAT,CR_CONFNAME,CR_TEAM,CR_TEAMCD,CR_STATUS,CR_CONGBN,
                      CR_COMMON, CR_BLANK,CR_EMGER,CR_HOLI,CR_SGNGBN,CR_ORGSTEP,CR_BASEUSR, CR_PRCSW)
                     (SELECT ACPTNO,1,lpad(ROWCNT,2,'0'),a.CM_NAME, NVL(a.CM_JOBCD,a.CM_POSITION),a.CM_GUBUN,
                             '0',a.CM_COMMON,a.CM_COMMON,a.CM_BLANK,a.CM_EMG,a.CM_HOLIDAY,
                             a.CM_POSITION,a.CM_ORGSTEP,NVL(a.CM_JOBCD,a.CM_POSITION),a.CM_PRCSW
                        FROM CMm0060 a
                       WHERE a.CM_SYSCD=SV_SYSCD
                         AND a.CM_REQCD=SV_REQCD
                         AND a.CM_MANID=CONF1.CM_MANID
                         AND a.CM_SEQNO=CONF1.CM_SEQNO);
           END IF;
        END IF;
    End Loop;

    IF ROWCNT > 0 THEN
       INSERT INTO CMR9900
          (CR_ACPTNO,CR_SEQNO,CR_LOCAT,CR_STATUS,CR_CONFUSR)
        VALUES
          (ACPTNO,'1', '00', '0', '9999' );
    END IF;

End CMM0060_STR;