-- GENERATED BY QueryOne AT 2021-03-04 14:18:02
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.SYSGBYN            
(AcptNo IN VARCHAR2,PrcSys IN VARCHAR2)        
                                                                                     
                                                                                     
RETURN NUMBER                                                                        
IS                                                                                   
    CNTVAL NUMBER := 0;                                                              
                                                                                     
-- 리턴값 0:프로세스체크안함 1:프로세스체크                                          
BEGIN                                                                                
                                                                                     
    IF substr(AcptNo,5,2) not in ('04','16') THEN                                    
        return 0;                                                                    
    END IF;                                                                          
                                                                                     
    IF PrcSys not in ('SYSDCB','SYSTCB','SYSCB') THEN                          
        return 0;                                                                    
    END IF;                                                                         
                                                                                     
                                                                                     
    SELECT COUNT(*)                                                                  
      INTO CNTVAL                                                                    
      FROM CMR1010 A, CMM0036 C,CMR9900 B                                                      
     WHERE A.CR_ACPTNO = AcptNo                                                      
       AND A.CR_PRCDATE IS NULL                                                      
       AND A.CR_SYSCD  = C.CM_SYSCD                                                  
       AND A.CR_RSRCCD = C.CM_RSRCCD                                                 
       AND SUBSTR(C.CM_INFO,19,1) = '1' 
       AND A.CR_ACPTNO=B.CR_ACPTNO 
       AND B.CR_TEAMCD='1' 
       AND B.CR_TEAM=DECODE(PrcSys,'SYSDCB','SYSDGB','SYSTCB','SYSTGB','SYSGB');                  
                                                                                     
                                                                                     
    IF CNTVAL = 0 THEN                                                               
        return 0;                                                                    
    ELSE                                                                             
        return 1;                                                                    
    END IF;                                                                          
                                                                                     
end;