-- GENERATED BY QueryOne AT 2021-03-04 14:17:57
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.REQEXIST_YN
(SYSCD IN VARCHAR2,REQCD IN VARCHAR2)
RETURN VARCHAR2
IS
    VCNT INT :=0;

BEGIN
    IF REQCD ='06' THEN
        RETURN 'NO';
    ELSIF REQCD = '16' THEN
        RETURN 'NO';
    ELSIF REQCD = '07' THEN
        select count(*) cnt
          into VCNT
          from CMM0031
         where cm_syscd = SYSCD
           and cm_svrcd in ('13','15','03','05')
           and cm_closedt is null;
        if VCNT = 0 THEN
            RETURN 'NO';
        ELSE 
            RETURN 'OK';
        END IF;
    ELSIF REQCD = '03' THEN
        select count(*) cnt
          into VCNT
          from cmm0031
         where cm_syscd = SYSCD
           and cm_svrcd in ('03','05')
           and cm_closedt is null;
        if VCNT = 0 THEN
          return 'NO';
        else
          return 'OK';
        END IF;
    ELSE
        RETURN 'NO';
    END IF;
end;