-- GENERATED BY QueryOne AT 2021-03-04 14:18:51
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.CONFNO_MAKE
(
 SYSCD                 IN   Varchar2,
 RSRCCD                IN   Varchar2)
 IS
 ErrSw              Varchar2 (01);
 CNT                INTEGER;
 VACPTNO            VARCHAR2(12);
CURSOR  MASLIST  IS
     Select CR_ITEMID,CR_STATUS
       From CMR0020
      Where CR_SYSCD=SYSCD
        AND CR_RSRCCD=RSRCCD
        AND CR_STATUS IN ('5','B','A');
Begin
    ErrSw          := NULL;
    CNT            := 0;

   For Usr2 In MASLIST  Loop
       SELECT NVL(MAX(A.CR_ACPTNO),'NONE')
         INTO VACPTNO
         FROM CMR1010 B,CMR1000 A
        WHERE B.CR_ITEMID=Usr2.CR_ITEMID
          AND B.CR_STATUS <>'3'
          AND B.CR_ACPTNO=A.CR_ACPTNO
          AND A.CR_QRYCD=DECODE(Usr2.CR_STATUS,'5','01','03');


        IF VACPTNO <> 'NONE' THEN
           UPDATE CMR1010
              SET CR_CONFNO=CR_ACPTNO
            WHERE CR_ITEMID=Usr2.CR_ITEMID
              AND CR_STATUS<>'3'
              AND CR_CONFNO IS NULL
              AND SUBSTR(CR_ACPTNO,5,2) IN ('01','02','03')
              AND CR_ACPTNO<>VACPTNO;

           UPDATE CMR1010
              SET CR_CONFNO=''
            WHERE CR_ITEMID=Usr2.CR_ITEMID
              AND CR_ACPTNO=VACPTNO
              AND CR_CONFNO IS NOT NULL;
        ELSE
           UPDATE CMR0020
              SET CR_STATUS=DECODE(CR_LSTVER,0,'3','0')
            WHERE CR_ITEMID=Usr2.CR_ITEMID;
        END IF;

   End Loop;

End CONFNO_MAKE;