-- GENERATED BY QueryOne AT 2021-03-04 14:17:55
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.ING_CHECK
(ITEMID IN VARCHAR2,STATUS IN VARCHAR2)
RETURN VARCHAR2
IS
    acptno  VARCHAR2(12);
    teamcd  VARCHAR2(1);
    confname  VARCHAR2(50);
    qrycd   VARCHAR2(2);
    KCNT INT := 0;
BEGIN

    IF STATUS = '7' THEN
        qrycd :='04';
    ELSIF status = '4' THEN
        qrycd:='01,02';
    ELSIF status = 'A' THEN
        qrycd:='03';
    END IF;

    BEGIN
        select max(a.cr_acptno)
        INTO  acptno
        from cmr1010 b, cmr1000 a
        where b.cr_itemid=ITEMID
        and b.cr_prcdate is null
        and b.cr_acptno=a.cr_acptno
        and instr(qrycd,a.cr_qrycd)>0
        and a.cr_status='0';
    END;

    BEGIN
        select cr_teamcd, cr_confname
        INTO  teamcd, confname
        from cmr9900
        where cr_acptno=acptno
        and cr_locat='00';
    END;

    IF teamcd = '1' THEN
       select count(*) cnt
       INTO  KCNT
       from cmr1010
       where cr_acptno=acptno
       and cr_itemid=ITEMID
       and nvl(cr_putcode,'0000') <> '0000';
       IF KCNT > 0 THEN
          RETURN confname || '_오류발생';
       ELSE
          RETURN confname;
       END IF;
    ELSE
       RETURN confname;
    END IF;
END;