-- GENERATED BY QueryOne AT 2021-03-04 14:18:03
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.TIMECHECK
(PrcSys IN VARCHAR2,PASSOK IN CHAR,ACPTNO IN VARCHAR2, APLYDATE IN varchar2, CMTIME IN CHAR , GYULJAE IN CHAR,SYSCD IN CHAR,SYSINFO IN VARCHAR2)

RETURN NUMBER
-- 0: 처리될 되상 1:스킵

IS
  ACPTDATE  VARCHAR2(12);
  VCNT      INTEGER := 0;
  CONFTIME  VARCHAR2(12);
BEGIN
    IF SUBSTR(ACPTNO,5,2) NOT IN ('04','05','16') THEN --체크인(운영),폐기,일괄등록이 아니면 SKIP
       RETURN 0;
    END IF;

    IF PrcSys not in ('SYSCB','SYSGB','SYSED','SYSRC','SYSSF','SYSCL') THEN --빌드,빌드후바이너리수신,배포,적용후처리,소스보관,폐기 아니면 SKIP
        return 0;
    END IF;

    IF PASSOK = '2' THEN  --긴급배포가 아니면 SKIP
        return 0;
    ELSIF PASSOK = '6' THEN  --사용자배포가 아니면 SKIP
       RETURN 1;
    END IF;


    IF GYULJAE = '1' THEN  --우선적용이 아니면 SKIP
        return 0;
    END IF;

    IF APLYDATE IS NULL THEN
        IF SUBSTR(SYSINFO,6,1) = '0' THEN
           RETURN 0;
        END IF;
        IF CMTIME IS NULL or CMTIME = '9999' THEN
            return 0;
        ELSE
           CONFTIME := TO_CHAR(SYSDATE,'YYYYMMDD') || CMTIME;
           IF CONFTIME > TO_CHAR(SYSDATE,'YYYYMMDDHH24MI') THEN
              RETURN 1;
           END IF;

           SELECT TO_CHAR(NVL(MAX(CR_CONFDATE),SYSDATE),'YYYYMMDDHH24MI')
             INTO ACPTDATE
             FROM CMR9900
            WHERE CR_ACPTNO=ACPTNO
              AND CR_LOCAT<>'00'
              AND CR_TEAM NOT IN ('SYSPC','SYSUA','SYSGB','SYSED','SYSRC');

            IF TO_NUMBER(CONFTIME) > TO_NUMBER(ACPTDATE) THEN
                IF PrcSys = 'SYSRC' THEN
                   SELECT COUNT(*)
                     INTO VCNT
                     FROM CMR9900 A,CMR1000 B
                    WHERE B.CR_SYSCD=SYSCD
                      AND B.CR_QRYCD='04'
                      AND B.CR_STATUS='0'
                      AND B.CR_PASSOK='0'
                      AND B.CR_PRCREQ IS NULL
                      AND B.CR_PRCTIME IS NOT NULL
                      AND B.CR_ACPTNO=A.CR_ACPTNO
                      AND A.CR_LOCAT='00'
                      AND A.CR_TEAMCD='1'
                      --AND B.CR_PRCTIME=CMTIME
                      AND 1=(SELECT COUNT(*)
                               FROM CMR9900
                              WHERE CR_ACPTNO=A.CR_ACPTNO
                                AND CR_LOCAT<>'00'
                                AND CR_TEAMCD='1'
                                AND CR_TEAM='SYSRC')
                      AND CONFTIME>(SELECT TO_CHAR(NVL(MAX(CR_CONFDATE),SYSDATE),'YYYYMMDDHH24MI')
                                      FROM CMR9900
                                     WHERE CR_ACPTNO=A.CR_ACPTNO
                                       AND CR_LOCAT<>'00'
                                       AND CR_TEAM NOT IN ('SYSPC','SYSUA','SYSGB','SYSED','SYSRC'))
                      AND A.CR_TEAM IN ('SYSUA','SYSGB','SYSED','SYSPC')
				      AND  NOT EXISTS (SELECT  'X'
                                        FROM CMR1010
                                       WHERE CR_ACPTNO = A.CR_ACPTNO
                                         AND NVL(CR_PUTCODE, '0000') != '0000');
                   IF VCNT > 0 THEN
                      RETURN 1;
                   ELSE
                      RETURN 0;
                   END IF;
                ELSE
                   RETURN 0;
                END IF;
            ELSE
               RETURN 1;
            END IF;
        END IF;
    ELSE
        IF LENGTH(APLYDATE) > 12 THEN
            IF APLYDATE  < to_char(sysdate,'yyyymmddhh24miss') THEN
                return 0;
            ELSE
               RETURN 1;
            END IF;
        ELSE
            IF APLYDATE  < to_char(sysdate,'yyyymmddhh24mi') THEN
                return 0;
            ELSE
               RETURN 1;
            END IF;
        END IF;
    END IF;

    return 1;
end;