-- GENERATED BY QueryOne AT 2021-03-04 14:17:54
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.GET_DIFFYN
(SYSCD varchar2,
 DSNCD varchar2)
return VARCHAR2
IS
   V_MSG       VARCHAR2(10);
   V_DIRPATH   CMM0070.CM_DIRPATH%TYPE;
   VCNT        NUMBER;


BEGIN
      V_MSG := 'N';

      BEGIN
          SELECT /*+ RULE */
                 COUNT(*)
            INTO VCNT
            FROM CMM0029
           WHERE CM_STNO='ECAMS'
             AND CM_GBNCD='01'
             AND CM_SYSCD=SYSCD
             AND CM_DSNCD=DSNCD;
          EXCEPTION
             WHEN  NO_DATA_FOUND  Then
                  VCNT := 0;
      END;

      IF VCNT > 0 THEN
         V_MSG := 'Y';
      END IF;

      IF V_MSG = 'N' THEN
          BEGIN
              SELECT  /*+ RULE */
                      CM_DIRPATH
                INTO  V_DIRPATH
                FROM  CMM0070
               WHERE  CM_SYSCD = SYSCD
                 AND  CM_DSNCD = DSNCD;
          EXCEPTION
             WHEN  NO_DATA_FOUND  Then
                  V_MSG := 'Y';
          END;
      END IF;

      IF V_MSG = 'N' THEN
          BEGIN
              SELECT  /*+ RULE */
                      COUNT(*)
                INTO  VCNT
                FROM  CMM0070 A
                    , CMM0029 B
               WHERE B.CM_STNO='ECAMS'
                 AND B.CM_GBNCD='01'
                 AND B.CM_SYSCD = A.CM_SYSCD
                 AND B.CM_DSNCD = A.CM_DSNCD
                 AND A.CM_SYSCD = SYSCD
                 AND INSTR(V_DIRPATH, TRIM(A.CM_DIRPATH) || '/') = 1;
              EXCEPTION
                 WHEN  NO_DATA_FOUND  Then
                      VCNT := 0;
           END;
      END IF;

      IF VCNT > 0 THEN
         V_MSG := 'Y';
      END IF;

      IF V_MSG = 'N' THEN
          BEGIN
              SELECT  /*+ RULE */
                      COUNT(*)
                INTO  VCNT
                FROM  CMM0070 A
                    , CMM0029 B
               WHERE B.CM_STNO='ECAMS'
                 AND B.CM_GBNCD='01'
                 AND B.CM_SYSCD = A.CM_SYSCD
                 AND B.CM_DSNCD = A.CM_DSNCD
                 AND A.CM_SYSCD = SYSCD
                 AND INSTR(V_DIRPATH, TRIM(A.CM_DIRPATH) || '\') = 1;
              EXCEPTION
                 WHEN  NO_DATA_FOUND  Then
                      VCNT := 0;
          END;
      END IF;

      IF VCNT > 0 THEN
         V_MSG := 'Y';
      END IF;

     return V_MSG;

END ;