-- GENERATED BY QueryOne AT 2021-03-04 14:17:52
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.CHECKINYN
(SCMUSER IN VARCHAR2,ISRID IN VARCHAR2,REQCD IN VARCHAR2,USERID IN VARCHAR2,STATUS IN VARCHAR2)
RETURN VARCHAR2
IS
   VCNT  INT := 0;

--변경관리 권한 체크
BEGIN
    IF REQCD = '41' THEN    --SR등록
       IF STATUS<>'0' AND STATUS<>'1' AND STATUS<>'2' AND STATUS<>'A' AND STATUS<>'C' THEN
          RETURN 'NO';
       END IF;
       
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020 A
        WHERE A.CR_ISRID=ISRID
          AND NVL(A.CR_CKOUTUSER,A.CR_EDITOR)=SCMUSER
          AND A.CR_STATUS<>'0';
       IF VCNT > 0 THEN
          RETURN 'NO4101';
       ELSE
          RETURN 'OK';
       END IF;
--    ELSIF REQCD = '43' THEN  --단위테스트
--       IF SCMUSER <> USERID THEN
--          RETURN 'NO4301';
--       END IF;
--       --개발자상태가 2:개발진행중 또는 A:개발검수반려 또는 C:운영적용반려가 아니면 오류 리턴
--       IF STATUS<>'2' AND STATUS<>'A' AND STATUS<>'C' THEN
--          RETURN 'NO4302';
--       END IF;
--
----       SELECT COUNT(*)
----         INTO VCNT
----         FROM CMM0120 A,CMC0100 B
----        WHERE B.CC_SRID=ISRID
----          AND B.CC_CATTYPE=A.CM_CATTYPE
----          AND A.CM_QRYCD='07'
----          AND A.CM_USEYN='Y';
----       IF VCNT = 0 THEN
----          RETURN 'OK';
----       END IF;
--
--       --프로그램에 대한 관리 있는 프로세스
--       --1건이상 프로그램을 체크인 또는 개발적용 또는 테스트적용
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMR1010 B,CMR1000 A,CMR0020 C
--        WHERE C.CR_ISRID=ISRID
--          AND C.CR_STATUS IN ('A','B','D','E','F','G')
--          AND C.CR_LSTUSR=SCMUSER
--          AND C.CR_ISRID=A.CR_ITSMID
--          AND A.CR_EDITOR=SCMUSER
--          AND A.CR_QRYCD=DECODE(TESTSVR_YN(A.CR_SYSCD,'03'),'OK','03',DECODE(TESTSVR_YN(A.CR_SYSCD,'03'),'OK','08','07'))
--          AND A.CR_STATUS<>'3'
--          AND A.CR_PRCDATE IS NOT NULL
--          AND A.CR_VERSION='Y'
--          AND A.CR_ACPTNO=B.CR_ACPTNO
--          AND C.CR_ITEMID=B.CR_ITEMID
--          AND B.CR_ITEMID=B.CR_BASEITEM
--          AND B.CR_STATUS<>'3';
--       IF VCNT = 0 THEN
--          RETURN 'NO4303';
--       END IF;
--    ELSIF REQCD = '4302' THEN --개발검수요청
--       --단위테스트시나리오가 있어야 함
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMC0200
--        WHERE CC_SRID=ISRID
--          AND CC_SCMUSER=SCMUSER
--          AND CC_STATUS<>'3';
--       IF VCNT = 0 THEN
--          RETURN 'NO5402';
--       END IF;
--
--       -- 단위테스트결과등록이 완료되어야 함
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMC0200 A
--        WHERE A.CC_SRID=ISRID
--          AND A.CC_SCMUSER=SCMUSER
--          AND A.CC_STATUS NOT IN ('3','9');
--       IF VCNT > 0 THEN
--          RETURN 'NO5403';
--       END IF;
--
----       SELECT COUNT(*)
----         INTO VCNT
----         FROM CMM0120 A,CMC0100 B
----        WHERE B.CC_SRID=ISRID
----          AND B.CC_CATTYPE=A.CM_CATTYPE
----          AND A.CM_QRYCD='07'
----          AND A.CM_USEYN='Y';
----       IF VCNT = 0 THEN
----          RETURN 'OK';
----       END IF;
--
--       --프로그램에 대한 관리 있는 프로세스
--       -- 대상프로그램이 모두 개발완료상태이어야 함
--       --모든프로그램들이  모두 7상태 이면 , SR 안보이도록 리턴
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMR0020
--        WHERE CR_ISRID=ISRID
--          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
--          AND CR_STATUS not in ('0','7');
--       IF VCNT = 0 THEN
--          RETURN 'NO5408';
--       END IF;
--
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMR0020
--        WHERE CR_ISRID=ISRID
--          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
--          AND CR_STATUS not in ('0','7')
--          --테스트있는 시스템은 프로그램상태값 'G' , 테스트없으면 'B'
--          --AND CR_STATUS<>DECODE(TESTSVR_YN(CR_SYSCD,'03'),'OK','G',DECODE(TESTSVR_YN(CR_SYSCD,'08'),'OK','E','B'));
--          AND CR_STATUS<>DECODE(TESTSVR_YN(CR_SYSCD,'03'),'OK','G', 'B' );
--       IF VCNT > 0 THEN
--          RETURN 'NO5406';
--       END IF;
--
--       -- 해당SR로 프로그램이 존재해야 함
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMR0020
--        WHERE CR_ISRID=ISRID
--          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER;
--       IF VCNT = 0 THEN
--          RETURN 'NO5407';
--       END IF;
--
--       --개발검수대상 시스템이어야 함
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMM0030 B,CMR0020 A
--        WHERE A.CR_ISRID=ISRID
--          AND NVL(A.CR_CKOUTUSER,A.CR_EDITOR)=SCMUSER
--          AND A.CR_SYSCD=B.CM_SYSCD
--          AND SUBSTR(B.CM_SYSINFO,12,1)='1';
--       IF VCNT = 0 THEN
--          RETURN 'OKNO';
--       ELSE
--          RETURN 'OK';
--       END IF;

    ELSIF REQCD = '07' OR REQCD = '11' THEN
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020
        WHERE CR_ISRID=ISRID
          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
          AND CR_STATUS IN ('3','5','B','E','G');
       IF VCNT > 0 THEN
          RETURN 'OK';
       ELSE
          RETURN 'NO00';
       END IF;
    ELSIF REQCD = '08' THEN
       -- 개발서버존재여부 CHECK
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020 A
        WHERE CR_ISRID=ISRID
          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
          AND TESTSVR_YN(A.CR_SYSCD,REQCD)='OK';
       IF VCNT = 0 THEN
          RETURN 'NO00';
       END IF;

       --테스트서버가 존재하지 않으면 체크인완료 또는 개발적용완료
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020 A
        WHERE CR_ISRID=ISRID
          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
          AND TESTSVR_YN(A.CR_SYSCD,'03')<>'OK'
          AND CR_STATUS IN ('B','E');
       IF VCNT > 0 THEN
          RETURN 'OK';
       END IF;

       --테스트서버가 존재하면 체크인완료,개발적용완료,테스트적용완료
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020 A
        WHERE CR_ISRID=ISRID
          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
          AND TESTSVR_YN(A.CR_SYSCD,'03')='OK'
          AND CR_STATUS IN ('B','E','G');
       IF VCNT > 0 THEN
          RETURN 'OK';
       END IF;

       RETURN 'NO01';

    ELSIF REQCD = '03' THEN
       -- 테스트서버존재여부 CHECK
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020 A
        WHERE CR_ISRID=ISRID
          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
          AND TESTSVR_YN(A.CR_SYSCD,REQCD)='OK';
       IF VCNT = 0 THEN
          RETURN 'NO00';
       ELSE RETURN 'OK';
       END IF;

       -- 개발서버존재하면 개발적용완료 또는 테스트적용완료인 경우
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020 A
        WHERE CR_ISRID=ISRID
          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
          AND TESTSVR_YN(A.CR_SYSCD,'08')='OK'
          AND CR_STATUS IN ('E','G');
       IF VCNT > 0 THEN
          RETURN 'OK';
       END IF;

       -- 개발서버미존재하면 체크인완료 또는 테스트적용완료인 경우
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020 A
        WHERE CR_ISRID=ISRID
          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
          AND TESTSVR_YN(A.CR_SYSCD,'08')='OK'
          AND CR_STATUS IN ('B','G');
       IF VCNT > 0 THEN
          RETURN 'OK';
       END IF;

       RETURN 'NO01';

    ELSIF REQCD = '04' THEN
       --프로그램이 존재하는지 조회
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020
        WHERE CR_ISRID = ISRID
          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
          AND CR_STATUS not in ('0','9');
          
       IF VCNT > 0 THEN
            --테스트요청이 존재하는지 조회
           SELECT COUNT(*)
             INTO VCNT
             FROM CMR0020 A
            WHERE CR_ISRID=ISRID
              AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
              AND TESTSVR_YN(A.CR_SYSCD,'03')='OK';

           IF VCNT > 0 THEN
              SELECT COUNT(*)
                INTO VCNT
                FROM CMR0020
               WHERE CR_ISRID=ISRID
                 AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
                 --AND CR_STATUS not in ('G','0','9');
                 AND CR_STATUS in ('3','5','B');
           ELSE
               SELECT COUNT(*)
                 INTO VCNT
                 FROM CMR0020
                WHERE CR_ISRID=ISRID
                  AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
                  --AND CR_STATUS not in ('B','0','9');
                  AND CR_STATUS in ('3','5');
           END IF;
           
           IF VCNT > 0 THEN
              RETURN 'OK';
           ELSE
              RETURN 'NOST';
           END IF;
       ELSE
          RETURN 'NO';
       END IF;
       
       

    ELSIF REQCD = '69' THEN    --SR중단
       IF STATUS<>'0' AND STATUS<>'1' AND STATUS<>'2' AND STATUS<>'A' AND STATUS<>'C' THEN
          RETURN 'NO';
       END IF;
       SELECT COUNT(*)
         INTO VCNT
         FROM CMR0020 A
        WHERE A.CR_ISRID=ISRID
          AND NVL(CR_CKOUTUSER,CR_EDITOR)=SCMUSER
          AND A.CR_STATUS<>'0';
       IF VCNT > 0 THEN
          RETURN 'NO4101';
       ELSE
          RETURN 'OK';
       END IF;
    END IF;
    RETURN 'OK';
end;