-- GENERATED BY QueryOne AT 2021-03-04 14:17:02
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE TRIGGER "ECAMS"."CMR1010_TRG" 
               
BEFORE UPDATE  ON ECAMS.CMR1010                                 
FOR EACH ROW
Declare                          
    V_Ver        CMR0020.cr_lstver%Type;                          
    V_VerBase    CMM0036.CM_VERCNT%Type;                          
    V_TstVer     CMR0020.cr_tstver%Type;                          
    VAcptNo      CMR1010.cr_acptno%Type;                            
    VNOTIFY      CMR1000.cr_NOTIFY%Type; 
    VRETRYYN     CMR1000.CR_RETRYYN%TYPE;
    V_AcptDate   CMR1000.cr_ACPTDATE%Type;                  
    V_MD5SUM     CMR0020.CR_MD5SUM%TYPE;               
    V_FILESIZE   CMR0020.CR_FILESIZE%TYPE;               
    V_FILEDATE   CMR0020.CR_FILEDATE%TYPE;               
                   
    VCnt          Integer;                          
    VSta          Char(1);                          
    VTeam         Varchar2 (10);                  
    SCRSW         CHAR(1);               
    V_LinkUrl     Varchar2(200);                
    V_SRYN        CHAR(1);               
    V_VERCNT      INTEGER;               
    V_REALVER     INTEGER;               
    V_ITSMID      VARCHAR2(50);               
    V_MSGACPT     VARCHAR2(50);               
    V_DOTVER      VARCHAR2(50);      
    V_NEXTREQ     VARCHAR2(50);
                              
 Begin
 
                  
 -- 자원처리완료시 처리                          
   IF (:OLD.CR_PUTCODE IS NULL OR :OLD.CR_PUTCODE = '0000') AND                           
      (:NEW.CR_PUTCODE IS NOT NULL AND :NEW.CR_PUTCODE <> '0000') THEN                          
      BEGIN                          
         SELECT NVL(CR_NOTIFY,'N'),CR_ACPTDATE,CR_ITSMID,NVL(CR_RETRYYN,'Y')                          
           INTO VNOTIFY, V_AcptDate,V_ITSMID,VRETRYYN                          
           FROM CMR1000                          
          WHERE CR_ACPTNO=:NEW.CR_ACPTNO;                          
            EXCEPTION                          
                 WHEN NO_DATA_FOUND THEN                          
                      VNOTIFY := 'N';                          
      END;          
       
      V_MSGACPT := '요청번호:' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7,6);                 
--      IF V_ITSMID IS NULL THEN               
--         V_MSGACPT := '신청번호: ' || substr(:NEW.cr_acptno,1,4) || '-' || substr(:NEW.cr_acptno,5,2) || '-' || substr(:NEW.cr_acptno,7,6);               
--      ELSE               
--         V_MSGACPT := 'SR-ID: ' || V_ITSMID;               
--      END IF;           
                     
      IF VNOTIFY = 'N' OR VRETRYYN = 'Y' THEN                          
         SELECT CM_URL                 
         INTO V_LinkUrl                 
         FROM CMM0010                 
        WHERE CM_STNO='ECAMS';                 
                         
         V_LinkUrl := V_LinkUrl || 'ecams_win_flex/';                  
         IF substr(:NEW.cr_acptno,5,2) = '01' or substr(:NEW.cr_acptno,5,2) = '02' or substr(:NEW.cr_acptno,5,2) = '11' or substr(:NEW.cr_acptno,5,2) = '12' THEN                  
            V_LinkUrl := V_LinkUrl || 'eCmr0150.jsp?ReqNo=' || :NEW.CR_ACPTNO;                  
         ELSIF substr(:NEW.cr_acptno,5,2) = '03' or substr(:NEW.cr_acptno,5,2) = '04' or substr(:NEW.cr_acptno,5,2) = '05' or substr(:NEW.cr_acptno,5,2) = '06' or substr(:NEW.cr_acptno,5,2) = '07' or substr(:NEW.cr_acptno,5,2) = '16' THEN                  
            V_LinkUrl := V_LinkUrl || 'eCmr0250.jsp?ReqNo=' || :NEW.CR_ACPTNO;                 
         END IF;                   
         
         IF :OLD.CR_SCRIPTRST IS NOT NULL OR :NEW.CR_SCRIPTRST IS NOT NULL THEN
             INSERT INTO CMR9910                           
                (CR_CONUSR,CR_SENDDATE,CR_STATUS,CR_SENDUSR,CR_SGNMSG,CR_ACPTNO,CR_TITLE,CR_LINKURL,CR_NOTIGBN,CR_NOTICD,CR_SMSMSG)                          
                (SELECT DISTINCT CM_USERID,SYSDATE,'0',:NEW.CR_EDITOR,                          
                    '[중요 : 오류발생]' || chr(13) ||                           
                    '1. 요청일 : ' || to_char(V_AcptDate,'yyyy/mm/dd') || chr(13) ||                          
                    '2. ' || V_MSGACPT || Chr(13) ||                          
                    '   eCAMS처리 중 오류가 발생하였습니다. eCAMS접속하여 처리결과를 확인 후' || chr(13) ||                          
                    '   조치하시기 바랍니다.',:NEW.CR_ACPTNO,                         
                    '형상관리시스템 요청건 처리 중 오류발생 알림',                        
                    V_LinkUrl,'ER','SMS',                                      
                    '[형상관리오류발생]' || CHR(10) ||               
                    '요청일:' || to_char(V_AcptDate,'yyyy/mm/dd') || chr(10) ||                 
                    V_MSGACPT || chr(10) ||  
                    '오류코드:' || :NEW.CR_SCRIPTRST
                  FROM CMM0040 A,CMM0020 B                          
                 WHERE A.CM_USERID = :NEW.CR_EDITOR               
                   AND B.CM_MACODE='REQUEST'               
                   AND B.CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));   
         ELSE
             INSERT INTO CMR9910                           
                (CR_CONUSR,CR_SENDDATE,CR_STATUS,CR_SENDUSR,CR_SGNMSG,CR_ACPTNO,CR_TITLE,CR_LINKURL,CR_NOTIGBN,CR_NOTICD,CR_SMSMSG)                          
                (SELECT DISTINCT CM_USERID,SYSDATE,'0',:NEW.CR_EDITOR,                          
                    '[중요 : 오류발생]' || chr(13) ||                           
                    '1. 요청일 : ' || to_char(V_AcptDate,'yyyy/mm/dd') || chr(13) ||                          
                    '2. ' || V_MSGACPT || Chr(13) ||                          
                    '   eCAMS처리 중 오류가 발생하였습니다. eCAMS접속하여 처리결과를 확인 후' || chr(13) ||                          
                    '   조치하시기 바랍니다.',:NEW.CR_ACPTNO,                         
                    '형상관리시스템 요청건 처리 중 오류발생 알림',                        
                    V_LinkUrl,'ER','SMS',                                      
                    '[형상관리 ' || B.CM_CODENAME || ' 오류발생]' || CHR(10) ||               
                    '1.요청일:' || to_char(V_AcptDate,'yyyy/mm/dd') || chr(10) ||                 
                    '2.' || V_MSGACPT
                  FROM CMM0040 A,CMM0020 B                          
                 WHERE A.CM_USERID = :NEW.CR_EDITOR               
                   AND B.CM_MACODE='REQUEST'               
                   AND B.CM_MICODE=SUBSTR(:NEW.CR_ACPTNO,5,2));   
         END IF;
                                       
         UPDATE CMR1000                          
            SET CR_NOTIFY='Y',CR_RETRYYN='N'                          
          WHERE CR_ACPTNO=:NEW.CR_ACPTNO;                                                      
      END IF;                                 
   END IF;                          
   IF :NEW.cr_prcdate is not null and :OLD.cr_prcdate is null and :NEW.cr_status <> '3' and :NEW.cr_itemid is not null then   
      IF (substr(:NEW.cr_acptno,5,2)='04' or    -- 운영적용요청
          substr(:NEW.cr_acptno,5,2)='06' or    -- Roll-Back                          
          substr(:NEW.cr_acptno,5,2)='16')      -- 일괄등록                          
         AND :NEW.cr_srcchg='1' AND :NEW.cr_qrycd<>'09' AND :NEW.CR_QRYCD<>'05' THEN             
         Begin    
             SELECT    A.cr_LstVer,SUBSTR(B.CM_SYSINFO,10,1),C.CM_VERCNT,NVL(A.CR_REALVER,0)                       
                INTO    V_Ver,V_SRYN,V_VERCNT,V_REALVER                         
                FROM    CMR0020 A,CMM0030 B,CMM0036 C                          
                WHERE   A.CR_ITEMID=:NEW.cr_ITEMID               
                  AND   A.CR_SYSCD=B.CM_SYSCD               
                  AND   A.CR_SYSCD=C.CM_SYSCD               
                  AND   A.CR_RSRCCD=C.CM_RSRCCD;                          
                EXCEPTION                          
                   WHEN NO_DATA_FOUND THEN                          
                        V_Ver := 1;                          
         END;          
            
         IF V_Ver >= V_VERCNT THEN               
            V_Ver := 1;               
         ELSE               
            V_Ver := V_Ver + 1;               
         END IF; 
         
         IF substr(:NEW.cr_acptno,5,2)='16' THEN
            IF :NEW.cr_version = 0 THEN                          
               VSta := '3';  
               V_Ver := 0;
            ELSE                   
               VSta := '0';  
               V_Ver := 1;
            END IF;
         ELSE                          
            VSta := '0';                          
         END IF;      
                            
        UpDate  CMR0020                          
           Set  cr_status=DECODE(V_Ver,0,'3','0'),                          
                cr_lastdate=SYSDATE,
                CR_LSTVER=V_Ver,
                CR_LSTUSR=:NEW.CR_EDITOR,
                CR_LSTDAT=SYSDATE,
                CR_ACPTNO=:NEW.CR_ACPTNO,
                CR_REALACPT=:NEW.CR_ACPTNO,               
                CR_REALUSR=:NEW.CR_EDITOR,               
                CR_REALDATE=SYSDATE,               
                CR_REALDEP=V_Ver,               
                CR_REALVER=V_Ver              
         Where  CR_ITEMID=:NEW.cr_ITEMID;           
                                            
        BEGIN                          
          SELECT COUNT(*)                          
            INTO Vcnt                          
            FROM CMM0036                          
           WHERE Cm_Syscd = :NEW.cr_syscd                          
             AND CM_Rsrccd = :NEW.cr_rsrccd                          
             AND SUBSTR(Cm_info,12,1)='1';                          
          EXCEPTION                          
               WHEN NO_DATA_FOUND THEN                          
                    Vcnt := 1;                          
        END; 
        
        IF substr(:NEW.cr_acptno,5,2)='16' THEN                          
            BEGIN                                
                DELETE CMR0025                          
                 WHERE CR_ITEMID = :NEW.cr_ITEMID;                            
            END;  
        ELSE                           
            BEGIN                                            
                DELETE CMR0025                                        
                 WHERE CR_ITEMID = :NEW.cr_ITEMID                          
                   AND CR_VER    = V_Ver;                          
            END;          
        END IF;                 
                      
        IF Vcnt > 0 AND V_Ver > 0 THEN                
           V_MD5SUM := NULL;               
               
           BEGIN               
               SELECT CR_MD5SUM, CR_FILESIZE, CR_FILEDATE               
                 INTO V_MD5SUM,  V_FILESIZE,  V_FILEDATE               
                 FROM CMR0027                          
                WHERE CR_ACPTNO = :NEW.cr_acptno               
                  AND CR_ITEMID = :NEW.cr_ITEMID;                                     
               EXCEPTION                          
                   WHEN NO_DATA_FOUND THEN                          
                        Raise_Application_Error (-20020,'[CMR0027] 원장생성오류.');                        
           END; 
           
           BEGIN
              UPDATE CMR0020               
                 SET CR_MD5SUM=V_MD5SUM,               
                     CR_FILESIZE=V_FILESIZE,               
                     CR_FILEDATE=V_FILEDATE,               
                     CR_REALMD5=V_MD5SUM,               
                     CR_REALSIZE=V_FILESIZE               
                WHERE CR_ITEMID=:NEW.CR_ITEMID;                    
                                   
               Insert into CMR0025
                    (CR_VER , CR_ITEMID,CR_ACPTNO, CR_FILE,CR_MD5SUM, CR_FILESIZE,CR_FILEDATE,CR_PRCDATE)                              
                    (SELECT V_Ver,  :NEW.CR_ITEMID , :NEW.cr_acptno, CR_FILE, CR_MD5SUM, CR_FILESIZE, CR_FILEDATE, SYSDATE                
                       FROM CMR0027                          
                      WHERE CR_ACPTNO = :NEW.cr_acptno               
                        AND CR_ITEMID = :NEW.cr_ITEMID);  
           End;                   
                               
            SELECT COUNT(*)                  
              INTO VCNT                  
              FROM CMR0025                  
             WHERE CR_ACPTNO=:NEW.cr_acptno                    
               AND CR_ITEMID=:NEW.cr_ITEMID;                  
            IF VCNT = 0 THEN                  
               Raise_Application_Error (-20021,'원장생성이 정확하게 되지 않았습니다.');                        
            END IF;                  
                           
            SELECT COUNT(*)                  
              INTO VCNT                  
              FROM CMR0025                  
             WHERE CR_ACPTNO=:NEW.cr_acptno                    
               AND CR_ITEMID=:NEW.cr_ITEMID                  
               AND CR_FILE IS NULL;                  
            IF VCNT > 0 THEN                  
               Raise_Application_Error (-20022,'원장생성이 정확하게 되지 않았습니다.');                        
            END IF;
            
            BEGIN                          
               Delete CMR0027                           
                WHERE CR_ITEMID = :NEW.cr_ITEMID                 
                  AND CR_ACPTNO = :NEW.cr_acptno;                          
            End;        
         END IF;                          
                                   
         IF substr(:NEW.cr_acptno,5,2)='16' THEN                          
            BEGIN                                
                DELETE CMR0021                          
                 WHERE CR_ITEMID = :NEW.cr_ITEMID;                            
            END;     
         ELSE                         
            BEGIN                                
                DELETE CMR0021                          
                 WHERE CR_ITEMID = :NEW.cr_ITEMID
                   AND CR_ACPTNO = :NEW.CR_ACPTNO;                            
            END;
         END IF;                          
         
         IF V_Ver > 0 THEN                      
            BEGIN                               
                INSERT INTO CMR0021                          
                      (CR_ITEMID,   cr_AcptNo, cr_VER, cr_qrycd, cr_acptdate, cr_editor,cr_prcdate,         
                       cr_realver,cr_dotver)                          
                VALUES                          
                      (:NEW.CR_ITEMID,  :NEW.cr_AcptNo, V_Ver, substr(:NEW.cr_acptno,5,2), SYSDATE, :NEW.cr_editor,SYSDATE,        
                       V_Ver,V_Ver);                          
            END;                          
         END IF;                          
      END IF;                        
      IF substr(:NEW.cr_acptno,5,2) = '01' OR substr(:NEW.cr_acptno,5,2) = '02' THEN                          
            BEGIN      -- 체크아웃(Down-Load), 이전버전체크아웃                          
               UpDate  CMR0020                          
                  Set  cr_status='5',                          
                       cr_clsdate='',                      
                       cr_lastdate=SYSDATE,                         
                       cr_editor=:NEW.cr_editor,               
                       cr_ckoutacpt=:NEW.cr_acptno,               
                       cr_ckoutuser=:NEW.cr_editor               
               Where   CR_ITEMID = :NEW.cr_ITEMID;                          
            END;                          
      END IF;                  
      IF substr(:NEW.cr_acptno,5,2) = '03' THEN     --테스트배포                             
         BEGIN                                 
            UpDate  CMR0020                          
               Set  CR_STATUS='G',               
                    cr_testdate=SYSDATE,                          
                    cr_testusr=:NEW.cr_editor,               
                    cr_testacpt=:NEW.cr_acptno,            
                    CR_TESTMD5=:NEW.CR_MD5SUM,               
                    CR_TESTSIZE=:NEW.CR_FILESIZE               
            Where   CR_ITEMID = :NEW.cr_ITEMID; 
         END; 
      END IF;                         
      IF substr(:NEW.cr_acptno,5,2) = '04' THEN      --운영배포    
         IF :NEW.CR_QRYCD = '09' THEN                --무수정
            BEGIN                                 
                UpDate  CMR0020                          
                Set     cr_NOMODIFY='0', 
                        CR_LASTDATE = SYSDATE
                Where   CR_ITEMID = :NEW.cr_ITEMID;                          
             END; 
         END IF; 
      END IF;                           
      IF substr(:NEW.cr_acptno,5,2) = '05' THEN      --폐기  
        BEGIN                                 
            UpDate  CMR0020                          
            Set     cr_STATUS='9', 
                    CR_CLSDATE = SYSDATE
            Where   CR_ITEMID = :NEW.cr_ITEMID;                          
         END;  
         BEGIN                               
            INSERT INTO CMR0021                          
                  (CR_ITEMID,   cr_AcptNo, cr_VER, cr_qrycd, cr_acptdate, cr_editor,cr_prcdate,         
                   cr_realver,cr_dotver)                          
            VALUES                          
                  (:NEW.CR_ITEMID,  :NEW.cr_AcptNo, :NEW.cr_version, substr(:NEW.cr_acptno,5,2), SYSDATE, :NEW.cr_editor,SYSDATE,        
                   :NEW.cr_version,:NEW.cr_version);                          
        END;  
      END IF;                     
      IF substr(:NEW.cr_acptno,5,2) = '11' THEN   -- 체크아웃취소                         
         BEGIN
            UpDate  CMR0020                          
               Set  cr_status=DECODE(CR_LSTVER,0,'3','0'),       
                    cr_lastdate=SYSDATE,                         
                    cr_editor=:NEW.cr_editor,
                    cr_isrid=''
            Where   CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                           
      END IF;                          
      IF substr(:NEW.cr_acptno,5,2) = '12' THEN   --테스트적용취소                          
         DELETE CMR0027                          
          WHERE CR_ITEMID = :NEW.cr_ITEMID                 
            AND CR_ACPTNO = :NEW.cr_confno;                          
                                    
         BEGIN                          
            UpDate  CMR0020                          
            Set     cr_status=DECODE(CR_LSTVER,0,'3','5'),                    
                    cr_lastdate=SYSDATE,                           
                    cr_editor=:NEW.cr_editor                          
            Where   CR_ITEMID = :NEW.cr_ITEMID;                          
         END;               
      END IF;                          
   End if;                          
   -- 자원처리반송시 처리                          
   IF :NEW.cr_status = '3' and :OLD.cr_status <> '3' and :NEW.cr_itemid is not null then                          
      -- 체크아웃(DOWN),이전버전체크아웃                          
      IF substr(:NEW.cr_acptno,5,2) = '01' or substr(:NEW.cr_acptno,5,2) = '02'  then                          
         BEGIN                          
           UPDATE CMR0020                          
              SET cr_status='0', 
                  cr_isrid='',
                  cr_lastdate=SYSDATE                           
            WHERE CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                          
      END IF;                      
      -- 테스트적용요청                         
      IF substr(:NEW.cr_acptno,5,2) = '03' THEN                               
         BEGIN               
            UpDate CMR0020                          
               Set CR_STATUS=DECODE(CR_LSTVER,0,'3','5')                
             Where CR_ITEMID = :NEW.cr_ITEMID;  
             
             DELETE CMR0027
              WHERE CR_ACPTNO=:NEW.CR_ACPTNO
                AND CR_ITEMID=:NEW.CR_ITEMID;
         END;                   
      END IF;                              
      IF substr(:NEW.cr_acptno,5,2) = '04' THEN
         IF :NEW.CR_QRYCD = '09' THEN                       
             BEGIN                  
                UpDate  CMR0020                          
                   Set  CR_NOMODIFY='0'               
                 Where  CR_ITEMID = :NEW.cr_ITEMID;                      
             END;                 
         ELSE                       
             BEGIN                  
                UpDate  CMR0020                          
                   Set  CR_STATUS=CR_SAVESTA               
                 Where  CR_ITEMID = :NEW.cr_ITEMID;  
             
                 DELETE CMR0027
                  WHERE CR_ACPTNO=:NEW.CR_ACPTNO
                    AND CR_ITEMID=:NEW.CR_ITEMID;                    
             END;                 
         END IF;           
      END IF;                             
      IF substr(:NEW.cr_acptno,5,2) = '05' THEN
          BEGIN                  
             UpDate  CMR0020                          
               Set  CR_STATUS='0'               
             Where  CR_ITEMID = :NEW.cr_ITEMID;                
          END;  
      END IF;      
      IF substr(:NEW.cr_acptno,5,2) = '16' THEN                          
         BEGIN                        
            Delete From CMR0027                           
             WHERE CR_ITEMID = :NEW.cr_ITEMID                 
               AND CR_ACPTNO = :NEW.cr_acptno; 
                                  
              UPDATE CMR0020                          
                 SET cr_status=DECODE(CR_LSTVER,0,'3','0')        
               WHERE CR_ITEMID = :NEW.cr_ITEMID;         
         END;                          
      END IF;                          
      IF substr(:NEW.cr_acptno,5,2) = '11' then                          
         BEGIN                          
           UPDATE CMR0020                          
              SET cr_status=CR_SAVESTA,               
                  cr_lastdate=SYSDATE                           
            WHERE CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                                     
      END IF;                          
      IF substr(:NEW.cr_acptno,5,2) = '06' then                          
         BEGIN                          
           UPDATE CMR0020                          
              SET cr_status='0',                          
                  cr_nomodify='0'                        
            WHERE CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                      
                          
         Delete From CMR0027                           
             WHERE CR_ITEMID = :NEW.cr_ITEMID                 
               AND CR_ACPTNO = :NEW.cr_acptno;                    
      END IF;                          
      IF substr(:NEW.cr_acptno,5,2) = '12' then 
         BEGIN                          
           UPDATE CMR0020                          
              SET cr_status=DECODE(CR_LSTVER,'3','5'),                          
                  cr_nomodify='0',                    
                  cr_lastdate=SYSDATE                          
            WHERE CR_ITEMID = :NEW.cr_ITEMID;                          
         END;                          
      END IF;                          
   END IF;                          
End CMR1010_Trg;