-- GENERATED BY QueryOne AT 2021-03-04 14:18:49
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.CMD0027_Insert     
( 
    szDiffDT  VARCHAR2,
    nJobSeq   NUMBER,
    nPortNo   NUMBER,
    szSvrIP   VARCHAR2,
    szDirPath VARCHAR2,
    szSysCd   VARCHAR2
 )
 IS           

Begin 
	 INSERT  INTO CMD0027                                           
	 		( CD_DIFFDT                                             
	 		, CD_JOBSEQ                                             
	 		, CD_SVRIP                                              
	 		, CD_SEQNO                                              
	 		, CD_SYSCD                                              
	 		, CD_DIRPATH                                            
	 		, CD_RSRCNAME                                           
	 		, CD_SVRCD                                              
	 		, CD_SVRNAME                                            
	 		, CD_DIFFRST                                            
	 		, CD_ECAMSSIZE                                          
	 		, CD_ECAMSDATE                                          
	 		, CD_ECAMSMD5                                           
	 		, CD_DSNCD                                              
	 		, CD_CLOSEYN                                            
	 		, CD_OPENYN                                             
	 		, CD_VERYN                                              
	 		, CD_RSRCCD                                             
	 		, CD_PORTNO                                             
	 		, CD_LSTUSR                                             
	 		)                                                       
	   SELECT  /*+LEADING(G D F E C A) USE_NL(C D E F G) USE_HASH(A)*/ 
	           DISTINCT                                                
	           szDiffDT                                               
	         , nJobSeq                                                  
	         , D.CM_SVRIP                                             
	         , (SELECT  NVL(MAX(CD_SEQNO),0)                          
	              FROM  CMD0027                                       
	             WHERE  CD_DIFFDT = szDiffDT                              
	               AND  CD_JOBSEQ = nJobSeq                              
	           ) + ROWNUM                                             
	         , A.CR_SYSCD                                             
	         , G.CM_DIRPATH                                           
	         , A.CR_RSRCNAME                                          
	         , D.CM_SVRCD                                             
	         , SVRNAME_CHECK(D.CM_SVRIP)                              
	         , 'FK'                                                   
	         , A.CR_FILESIZE                                          
	         , A.CR_FILEDATE                                          
	         , A.CR_MD5SUM                                            
	         , A.CR_DSNCD                                             
	         , DECODE(A.CR_STATUS,'9','Y','N')                        
	         , DECODE(A.CR_STATUS,'1','X','3','Y',DECODE(A.CR_LSTVER,0,'Y','N')) 
	         , DECODE(SUBSTR(E.CM_INFO,12,1),'1','Y','N')             
	         , A.CR_RSRCCD
             , nPortNo                                   
	         , A.CR_LSTUSR                                            
	     FROM  CMM0036 E                                              
	         , CMM0038 F                                              
	         , CMM0031 D                                              
	         , CMM0074 G                                              
	         ,  (SELECT  CM_SYSCD                                     
	               FROM  CMM0030                                      
	              WHERE  CM_CLOSEDT IS NULL                           
	              MINUS                                               
	             SELECT  CM_SYSCD                                     
	               FROM  CMM0026                                      
	              WHERE  CM_STNO='ECAMS'                              
	                AND  CM_RUNCD='01'                                
	                AND  CM_EXISTYN='Y'                               
	            ) C                                                   
	          , CMR0020 A                                             
	     WHERE  G.CM_SVRIP   = szSvrIP                                 
	       AND  G.CM_PORTNO  = nPortNo                                
	       AND  G.CM_DIRPATH = szDirPath                                
	       AND  G.CM_SYSCD   = szSysCd                               
	       AND  G.CM_SYSCD   = D.CM_SYSCD                             
	       AND  G.CM_SVRIP   = D.CM_SVRIP                             
	       AND  D.CM_CLOSEDT IS NULL                                  
	       AND  D.CM_SVRCD  IN ('01','03','05','13','15','23','25')     	  
	       AND  D.CM_SYSCD   = C.CM_SYSCD                             
	       AND  D.CM_SYSCD   = F.CM_SYSCD                             
	       AND  D.CM_SVRCD   = F.CM_SVRCD                             
	       AND  D.CM_SEQNO   = F.CM_SEQNO                             
	       AND  F.CM_SYSCD   = A.CR_SYSCD                             
	       AND  F.CM_RSRCCD  = A.CR_RSRCCD                            
	       AND  F.CM_SYSCD   = E.CM_SYSCD                             
	       AND  F.CM_RSRCCD  = E.CM_RSRCCD                            
	       AND  G.CM_SYSCD   = A.CR_SYSCD                             
	       AND  G.CM_DSNCD   = A.CR_DSNCD                             
	       AND  SUBSTR(E.CM_INFO,60,1) = '0'                          
	       AND  SUBSTR(E.CM_INFO,27,1) = '0';            
    
End CMD0027_Insert;