-- GENERATED BY QueryOne AT 2021-03-04 14:18:53
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE PROCEDURE ECAMS.SYSEXENAME_STR 
(SYSCD IN VARCHAR2, 
 SVRIP IN VARCHAR2) 
 IS 
 ErrSw              Varchar2 (01); 
 FINDSW             BOOLEAN; 
 VCNT               INTEGER; 
 SVSVRIP            VARCHAR2 (20); 
 
CURSOR  Conf1 IS 
    SELECT e.cm_svrip,e.cm_syscd,e.cm_svrcd 
      FROM cmm0031 e,cmm0038 f,CMM0027 D, 
           (select CM_SYSCD 
              from CMM0030 
             where CM_CLOSEDT IS NULL 
             MINUS 
            SELECT CM_SYSCD 
              FROM CMM0026 
             WHERE CM_STNO='ECAMS' 
               AND CM_RUNCD='01' 
               AND CM_EXISTYN='Y') C, 
           cmm0030 b 
     where C.CM_SYSCD=DECODE(SYSCD,'ALL',C.CM_SYSCD,SYSCD) 
       AND C.CM_SYSCD=B.CM_SYSCD 
       AND b.cm_syscd=e.cm_syscd 
       and e.cm_closedt is null 
       AND E.CM_SVRIP=DECODE(SVSVRIP,'ALL',E.CM_SVRIP,SVSVRIP) 
       and e.cm_svrcd IN ('05') 
       AND E.CM_SYSCD=D.CM_SYSCD 
       AND E.CM_SVRIP=D.CM_SVRIP 
       AND D.CM_RUNCD='01' 
       AND D.CM_EXISTYN='N' 
       and e.cm_syscd=f.cm_syscd 
       and e.cm_svrcd=f.cm_svrcd 
       and e.cm_seqno=f.cm_seqno 
     group by e.cm_svrip,e.cm_syscd, e.cm_svrcd 
     order by e.cm_svrip,e.cm_syscd, e.cm_svrcd      ; 
 
Begin 
    IF SVRIP IS NULL THEN 
       SVSVRIP := 'ALL'; 
    ELSE 
       SVSVRIP := SVRIP; 
    END IF; 
    INSERT INTO CMM0026 
      (CM_STNO,CM_RUNCD,CM_SYSCD,CM_LASTDT,CM_EXISTYN,CM_EXENAME,CM_BASEDIRCD,CM_EXECD) 
      (SELECT 'ECAMS','01',CM_SYSCD,SYSDATE,'N','','C','C' 
         FROM CMM0030 
        WHERE CM_CLOSEDT IS NULL 
        MINUS 
       SELECT 'ECAMS','01',CM_SYSCD,SYSDATE,'N','','C','C' 
         FROM CMM0026); 
 
    For Dir In Conf1  Loop 
        SELECT COUNT(*) 
          INTO VCNT 
          FROM CMM0027 
         WHERE CM_STNO='ECAMS' 
           AND CM_RUNCD='01' 
           AND CM_SYSCD=Dir.CM_SYSCD 
           AND CM_SVRIP=Dir.CM_SVRIP; 
        IF VCNT = 0 THEN 
           INSERT INTO CMM0027 
             (CM_STNO,CM_RUNCD,CM_SYSCD,CM_SVRIP,CM_LASTDT,CM_EXENAME,CM_BASEDIRCD,CM_EXECD) 
             VALUES 
             ('ECAMS','01',Dir.CM_SYSCD,Dir.CM_SVRIP,SYSDATE,'','C','C'); 
        END IF; 
 
       --dbms_OUTPUT.PUT_LINE('71 Line CM_SYSCD=' || Dir.CM_SYSCD || ', CM_SVRIP=' || Dir.CM_SVRIP || ', ' || EXENAME_FILEDIFF(Dir.CM_SYSCD,Dir.CM_SVRIP,'03','C','')); 
        UPDATE CMM0027 
           SET CM_EXENAME=EXENAME_FILEDIFF(Dir.CM_SYSCD,Dir.CM_SVRIP,Dir.CM_SVRCD,'C',CM_EXENAME) 
               ,CM_LASTDT=SYSDATE 
         WHERE CM_STNO='ECAMS' 
           AND CM_RUNCD='01' 
           AND CM_SYSCD=Dir.CM_SYSCD 
           AND CM_SVRIP=Dir.CM_SVRIP; 
   END LOOP; 
 
End SYSEXENAME_STR;