-- GENERATED BY QueryOne AT 2021-03-04 14:17:59
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.SRSTEP_SECUCHK
(USERID IN VARCHAR2,ISRID IN VARCHAR2,REQCD IN VARCHAR2,QRYGBN IN VARCHAR2)
RETURN VARCHAR2
IS
   VCNT   INTEGER        := 0;
   RETCD  VARCHAR2(10)   := 'OK';
   STATUS CHAR(1);

--변경관리 권한 체크
BEGIN
    IF REQCD = '41' THEN  --SR등록
       SELECT COUNT(*)
         INTO VCNT
         FROM CMC0100
        WHERE CC_SRID=ISRID
          AND CC_CREATEUSER=USERID;
       IF VCNT > 0 THEN
          RETCD := 'OK';
       ELSE
          RETCD := 'NO_41';
       END IF;
       IF RETCD = 'OK' AND QRYGBN = '01' THEN
          SELECT COUNT(*)
            INTO VCNT
            FROM CMC0110
           WHERE CC_SRID=ISRID
             AND CC_STATUS NOT IN ('3','8');
          IF VCNT >0 THEN
             RETCD := 'OK';
          ELSE
             RETCD := 'NOST';
          END IF;
       END IF;
--    ELSIF REQCD = '42' OR REQCD = '43' THEN  --개발계획서/단위테스트
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMC0110 A
--        WHERE A.CC_SRID=ISRID
--          AND A.CC_USERID=USERID
--          AND NVL(A.CC_STATUS,'0')<>'3';
--       IF VCNT = 0 THEN
--          RETCD := 'NO4300';
--       ELSE
--          RETCD := 'OK';
--       END IF;
--       IF RETCD = 'OK'  AND QRYGBN <> '00' THEN
--          SELECT CC_STATUS
--            INTO STATUS
--            FROM CMC0110
--           WHERE CC_SRID=ISRID
--             AND CC_USERID=USERID;
--          IF REQCD = '42' THEN --개발계획/실적
--             IF QRYGBN = '01' THEN
--                IF STATUS = '1' THEN --
--                   RETURN 'OK';
--                ELSE
--                   RETURN 'NO';
--                END IF;
--             ELSIF QRYGBN = '02' THEN
--                IF STATUS <> '0' AND STATUS <> '1' AND STATUS <> '8' AND STATUS <> '9'  THEN
--                   RETURN 'OK';
--                ELSE
--                   RETURN 'NO';
--                END IF;
--             ELSE
--                RETURN 'OK';
--             END IF;
--          ELSIF REQCD = '43' THEN --단위테스트
--             IF STATUS <> '2' AND STATUS <> 'A' AND STATUS <> 'C' THEN
--                RETURN 'NO4300';
--             END IF;
--             IF QRYGBN = '01' THEN
--                RETCD := CHECKINYN(USERID,ISRID,REQCD,USERID,STATUS);
--             ELSE
--                RETCD := CHECKINYN(USERID,ISRID,'4302',USERID,STATUS);
--             END IF;
--             IF RETCD <> 'OK' THEN
--                RETURN RETCD;
--             END IF;
--          END IF;
--       END IF;
--    ELSIF REQCD = '54' THEN     --개발검수
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMM0043
--        WHERE CM_USERID=USERID
--          AND CM_RGTCD='58';
--       IF VCNT > 0 THEN
--          RETCD := 'OK';
--       ELSE
--          RETCD := 'NO5400';
--       END IF;
--       IF RETCD = 'OK'  AND QRYGBN <> '00' THEN
--          SELECT COUNT(*)
--            INTO VCNT
--            FROM CMC0110
--           WHERE CC_SRID=ISRID
--             AND CC_STATUS IN ('4','7');
--          IF VCNT > 0 THEN
--             RETCD := 'OK';
--          ELSE
--             RETCD := 'NO5401';
--          END IF;
--       END IF;
    ELSIF REQCD = '01' OR REQCD = '02' OR REQCD = '08' THEN    
       SELECT COUNT(*)
         INTO VCNT
         FROM CMC0110 A
        WHERE A.CC_SRID=ISRID
          AND A.CC_EDITOR=USERID
          AND NVL(A.CC_STATUS,'0') IN ('2','A','C','4','5')
          and cc_srid not in (select cr_itsmid from cmr1000 where cr_status ='0' and cr_qrycd in ('04','03') and cr_srid=cc_srid);
        IF VCNT = 0 THEN
           RETCD := 'NO_010208';
        ELSIF REQCD <> '01' AND REQCD <> '02' THEN
           STATUS := '2';
           RETCD := CHECKINYN(USERID,ISRID,REQCD,USERID,STATUS);
        ELSE
           RETCD := 'OK';
        END IF;
    ELSIF REQCD = '07' OR REQCD = '11' OR REQCD = '03' THEN
       SELECT COUNT(*)
         INTO VCNT
         FROM CMC0110 A
        WHERE A.CC_SRID=ISRID
          AND A.CC_EDITOR=USERID
          AND NVL(A.CC_STATUS,'0') IN ('2','A','C','4','5','9')
          and cc_srid not in (select cr_itsmid from cmr1000 where cr_status ='0' and cr_qrycd in ('04','03') and cr_srid=cc_srid);
        IF VCNT = 0 THEN
           RETCD := 'NO0703';
        ELSIF REQCD <> '01' AND REQCD <> '02' THEN
           STATUS := '2';
           RETCD := CHECKINYN(USERID,ISRID,REQCD,USERID,STATUS);
        ELSE
           RETCD := 'OK';
        END IF;    
--    ELSIF REQCD = '03' THEN
--       SELECT COUNT(*)
--         INTO VCNT
--         FROM CMC0100 A
--        WHERE A.CC_SRID=ISRID
--          AND A.cc_owner=USERID
--          AND NVL(A.CC_STATUS,'0') IN ('2','A','C','4','5','9')
--          and cc_srid not in (select cr_itsmid from cmr1000 where cr_status ='0' and cr_qrycd in ('04','03'));
--        IF VCNT = 0 THEN
--           RETCD := 'NO0703';
----        ELSIF REQCD <> '01' AND REQCD <> '02' THEN
----           STATUS := '2';
----           RETCD := CHECKINYN(USERID,ISRID,REQCD,USERID,STATUS);
--        ELSE
--           RETCD := 'OK';
--        END IF;  
        
    ELSIF REQCD = '04' THEN     --운영적용요청
        --CC_STATUS 2:개발진행중  5:운영적용요청  B:개발검수완료  C:운영적용반려
        SELECT COUNT(*)
         INTO VCNT
         FROM CMC0100 A
        WHERE A.CC_SRID=ISRID
          AND A.CC_OWNER=USERID
          AND NVL(A.CC_STATUS,'0') IN ('2','A','C','4','9');
        IF VCNT = 0 THEN
           RETCD := 'NO04';
        ELSE
           SELECT CC_STATUS
             INTO STATUS
             FROM CMC0100
            WHERE CC_SRID=ISRID
              AND CC_OWNER=USERID;
           IF STATUS <> '2' AND STATUS <> '5' THEN
              RETCD := CHECKINYN(USERID,ISRID,'04',USERID,STATUS);
              IF RETCD = 'OK' THEN
                 RETCD := 'OK';
              ELSE
                 RETCD := 'NO04';
              END IF;
           ELSE
                --긴급SR 여부 체크 Y:긴급 N:일반
                SELECT COUNT(*)
                  INTO VCNT
                  FROM CMC0100
                 WHERE CC_SRID=ISRID
                   AND CC_CHGTYPE = '01';
                IF VCNT > 0 THEN
                    --긴급프로세스 시작
                    RETCD := CHECKINYN(USERID,ISRID,'04',USERID,STATUS);
                    IF RETCD = 'OK' THEN
                        RETCD := 'OK';
                    END IF;
                    --긴급프로세스 끝
                ELSE
                    --20140728 neo. 개발검수 완료 여부 체크 추가 시작
                    --20140728 neo. 상태2 이면 개발검수가 있는지, 있다면 검수가 완료 됐는지 체크
                    --20140728 neo. 개발검수 대상 시스템 여부 체크
                    SELECT COUNT(*)
                      INTO VCNT
                      FROM CMM0030 B,CMR0020 A
                     WHERE A.CR_ISRID=ISRID
                       AND NVL(A.CR_CKOUTUSER,CR_EDITOR)=USERID
                       AND A.CR_SYSCD=B.CM_SYSCD
                       AND A.CR_STATUS not in ('0','7')
                       AND SUBSTR(B.CM_SYSINFO,12,1)='1';
                    IF VCNT > 0 THEN
                        --20140728 neo. 개발검수 있으면 검수완료 상태[B] 이여야함.
                        RETCD := 'NO1';
                    ELSE
                        RETCD := CHECKINYN(USERID,ISRID,'04',USERID,STATUS);
                        IF RETCD = 'OK' THEN
                            RETCD := 'OK';
                        END IF;
                    END IF;
                    --변경후 끝
                    --20140728 neo. 개발검수 완료 여부 체크 추가 끝
                END IF;
            END IF;
        END IF;

    ELSIF REQCD = '63' THEN    --모니터링
       SELECT COUNT(*)
         INTO VCNT
         FROM CMC0110
        WHERE CC_SRID=ISRID
          AND CC_USERID=USERID
          AND CC_STATUS <> '3';
       IF VCNT = 0 THEN
          RETCD := 'NO6300';
       ELSE
          RETCD := 'OK';
       END IF;

       IF RETCD = 'OK'  AND QRYGBN = '01' THEN
          SELECT CC_STATUS
            INTO STATUS
            FROM CMC0110
           WHERE CC_SRID=ISRID
             AND CC_USERID=USERID;
          IF STATUS = '6' OR STATUS = 'D' THEN --
             RETURN 'OK';
          ELSE
             RETURN 'NO6301';
          END IF;
       END IF;

    ELSIF REQCD = '69' THEN   --SR완료
       SELECT COUNT(*)
         INTO VCNT
         FROM CMC0100
        WHERE CC_SRID=ISRID
          AND CC_CREATEUSER=USERID
          AND CC_STATUS IN ('3','8','9');
       IF VCNT > 0 THEN
          RETCD := 'NO02342340';
       ELSE
          IF QRYGBN = '01' THEN
             SELECT COUNT(*)
               INTO VCNT
               FROM CMC0110
              WHERE CC_SRID=ISRID
                AND CC_STATUS='9';
             IF VCNT > 0 THEN
                SELECT COUNT(*)
                  INTO VCNT
                  FROM CMC0110
                 WHERE CC_SRID=ISRID
                   AND CC_STATUS NOT IN ('3','8','9');
                IF VCNT = 0 THEN
                   RETCD := 'OK';
                ELSE
                   RETCD := 'NO02';
                END IF;
             ELSE
                RETCD := 'OK';
             END IF;
          ELSE
             SELECT COUNT(*)
               INTO VCNT
               FROM CMC0110
              WHERE CC_SRID=ISRID
                AND CC_STATUS='9';
             IF VCNT > 0 THEN
                RETCD := 'NO02';
             ELSE
                SELECT COUNT(*)
                  INTO VCNT
                  FROM CMR0020
                 WHERE CR_ISRID=ISRID
                   AND CR_STATUS NOT IN ('0','9');
                IF VCNT = 0 THEN
                   RETCD := 'OK';
                END IF;
             END IF;
          END IF;
       END IF;
    END IF;

    RETURN RETCD;
end;