-- GENERATED BY QueryOne AT 2021-03-04 14:17:53
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.EXENAME_FILEDIFF
(SYSCD varchar2,SVRIP varchar2,SVRCD varchar2,EXECD VARCHAR2,EXENAME VARCHAR2)
return VARCHAR2
IS
    V_WORK1     VARCHAR2(4000);
    V_WORK2     VARCHAR2(4000);
    V_WORK3     VARCHAR2(4000);
    i           INTEGER;

CURSOR  SYSEXE IS
    select distinct a.cm_exename
      from cmm0038 e,cmm0031 d,cmm0036 a
     where d.cm_syscd=SYSCD
       and d.cm_svrip=SVRIP
       and d.cm_svrcd=SVRCD
--       AND D.CM_SEQNO=SEQNO
       and d.cm_closedt is null
       and d.cm_syscd=e.cm_syscd
       and d.cm_svrcd=e.cm_svrcd
       and d.cm_seqno=e.cm_seqno
       and e.cm_syscd=a.cm_syscd
       and e.cm_rsrccd=a.cm_rsrccd
       AND SUBSTR(A.CM_INFO, 60, 1) = '0'
       and a.cm_closedt is null ;
CURSOR  SYSEXE_SCM IS
    select distinct substr(a.cr_rsrcname,instr(a.cr_rsrcname,'.',-1)) exename
      from cmr0020 a
     where a.cr_syscd=SYSCD
       and a.cr_lstver>0
       and a.cr_status not in ('9')
       and instr(a.cr_rsrcname,'.')>0
       AND A.CR_RSRCCD IN (SELECT A.CM_RSRCCD
                             FROM CMM0038 A,CMM0036 B
                            WHERE A.CM_SYSCD=SYSCD
                              AND A.CM_SVRCD=SVRCD
--                              AND A.CM_SEQNO=SEQNO
                              AND A.CM_SYSCD=B.CM_SYSCD
                              AND A.CM_RSRCCD=B.CM_RSRCCD
                              AND SUBSTR(B.CM_INFO, 60, 1) = '0'
                              AND B.CM_CLOSEDT IS NULL);

BEGIN
    V_WORK1 := EXENAME;
    IF EXECD = 'X' THEN
       RETURN 'NON';
    END IF;
    IF EXECD = 'E' OR EXECD = 'N' THEN
       RETURN EXENAME;
    END IF;
    For Lst In SYSEXE  Loop
        V_WORK2 := Lst.cm_exename;
        IF V_WORK1 IS NULL THEN
           V_WORK1 := V_WORK2;
        ELSE
            IF SUBSTR(V_WORK2,LENGTH(V_WORK2),1) <> ',' THEN
               V_WORK2 := V_WORK2 || ',';
            END IF;
            --dbms_OUTPUT.PUT_LINE('27 Line V_WORK2' || V_WORK2 );
            Loop
                i := INSTR(V_WORK2,',');
                IF i>0 THEN
                   V_WORK3 := SUBSTR(V_WORK2,1,i);
                   IF LENGTH(V_WORK2) = i THEN
                      V_WORK2 := null;
                   ELSE
                      V_WORK2 := SUBSTR(V_WORK2,i+1);
                   END IF;

                    --dbms_OUTPUT.PUT_LINE('37 Line v_work1,V_WORK2,V_WORK3' || V_WORK1 || ' ' || V_WORK2 || ' ' || V_WORK3 );
                   IF INSTR(V_WORK1,V_WORK3) = 0 THEN
                      V_WORK1 := V_WORK1 || V_WORK3;
                   END IF;
                ELSE
                   V_WORK2 := null;
                END IF;
                IF V_WORK2 IS NULL THEN
                   EXIT;
                END IF;

                --dbms_OUTPUT.PUT_LINE('47 Line V_WORK1' || V_WORK1 );
                exit;
            End Loop;
        END IF;
    End Loop;

    For Lst In SYSEXE_SCM  Loop
        V_WORK2 := Lst.exename || ',';

        IF INSTR(V_WORK1,V_WORK2)=0 THEN
           IF LENGTH(V_WORK1)>500 THEN
--              dbms_OUTPUT.PUT_LINE('91 Line V_WORK1' || V_WORK1 );
              EXIT;
           END IF;
           V_WORK1 := V_WORK1 || V_WORK2;
        END IF;
    End Loop;
    return SUBSTR(V_WORK1,1,4000);

END ;