-- GENERATED BY QueryOne AT 2021-03-04 14:18:02
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.SYSTESTENDYN
(SRID IN VARCHAR2,SCMUSER IN VARCHAR2,REQCD IN VARCHAR2,CASESEQ IN INTEGER,TESTGBN IN VARCHAR2)
RETURN VARCHAR2
IS
   VCNT INT := 0;
   PROGYN CHAR(1) := 'Y';
 --- 개발자별 통합테스트완료여부
BEGIN
    IF CASESEQ = 0 THEN
        select count(*) cnt
          into VCNT
          from CMC0210
         where CC_SRID=SRID
           AND CC_SCMUSER=SCMUSER
           AND CC_STATUS<>'3'
           AND CC_TESTGBN<>DECODE(REQCD,'54','A','B');

        IF VCNT = 0 THEN
           IF REQCD = '54' THEN
              RETURN 'NO';
           ELSE
              RETURN 'OK';
           END IF;
        END IF;
    END IF;

    BEGIN
        SELECT COUNT(*)
          INTO VCNT
          FROM (
                SELECT B.CC_CASESEQ,B.CC_TESTUSER,B.CC_TESTGBN,C.CC_GBNCD,C.CC_SEQNO
                  FROM CMC0210 A,CMC0211 B,CMC0212 C
                 WHERE A.CC_SRID=SRID
                   AND A.CC_SCMUSER=SCMUSER
                   AND A.CC_STATUS<>'3'
                   AND A.CC_CASESEQ=DECODE(CASESEQ,0,A.CC_CASESEQ,CASESEQ)
                   AND A.CC_SRID=B.CC_SRID
                   AND A.CC_CASESEQ=B.CC_CASESEQ
                   AND B.CC_TESTGBN=DECODE(REQCD,'XX',TESTGBN,'54','B','A')
                   AND B.CC_STATUS<>'3'
                   AND B.CC_SRID=C.CC_SRID
                   AND B.CC_CASESEQ=C.CC_CASESEQ
                   AND C.CC_GBNCD='R'
                   AND C.CC_STATUS<>'3'
                 MINUS
                SELECT B.CC_CASESEQ,B.CC_TESTUSER,B.CC_TESTGBN,C.CC_GBNCD,C.CC_SEQNO
                  FROM CMC0210 A,CMC0211 B,CMC0212 C,CMC0213 D
                 WHERE A.CC_SRID=SRID
                   AND A.CC_SCMUSER=SCMUSER
                   AND A.CC_STATUS<>'3'
                   AND A.CC_CASESEQ=DECODE(CASESEQ,0,A.CC_CASESEQ,CASESEQ)
                   AND A.CC_SRID=B.CC_SRID
                   AND A.CC_CASESEQ=B.CC_CASESEQ
                   AND B.CC_TESTGBN=DECODE(REQCD,'XX',TESTGBN,'54','B','A')
                   AND B.CC_STATUS<>'3'
                   AND B.CC_SRID=C.CC_SRID
                   AND B.CC_CASESEQ=C.CC_CASESEQ
                   AND C.CC_GBNCD='R'
                   AND C.CC_STATUS<>'3'
                   AND C.CC_SRID=D.CC_SRID
                   AND C.CC_CASESEQ=D.CC_CASESEQ
                   AND C.CC_GBNCD=D.CC_GBNCD
                   AND C.CC_SEQNO=D.CC_SEQNO
                   AND B.CC_TESTGBN=D.CC_TESTGBN
                   AND B.CC_TESTUSER=D.CC_TESTUSER
                   AND NVL(D.CC_TESTRST,'X')='0');
    END;
    IF VCNT = 0 THEN
       IF REQCD = '54' THEN
          SELECT COUNT(*)
            INTO VCNT
            FROM (
                  SELECT CC_ITEMID,CC_TESTER
                    FROM CMC0214
                   WHERE CC_SRID=SRID
                     AND CC_SCMUSER=SCMUSER
                     AND CC_CASESEQ=999
                   MINUS
                  SELECT CC_ITEMID,CC_TESTER
                    FROM CMC0214
                   WHERE CC_SRID=SRID
                     AND CC_SCMUSER=SCMUSER
                     AND CC_CASESEQ<>999);
          IF VCNT > 0 THEN
             RETURN 'NO';
          ELSE
             RETURN 'OK';
          END IF;
       ELSE
          RETURN 'OK';
       END IF;
    ELSE
       RETURN 'NO';
    END IF;
end;