-- GENERATED BY QueryOne AT 2021-03-04 14:17:58
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.ROLLBACK_SVR
(ACPTNO IN VARCHAR2,REQCD IN VARCHAR2,GBNCD VARCHAR2)
RETURN VARCHAR2
IS
   VCNT INT := 0;
   RETSVRCD VARCHAR2(10);

--ISR 내용 변경 가능여부
BEGIN
   BEGIN
       SELECT B.CR_SYSSTEP
         INTO VCNT
         FROM CMR1000 B
        WHERE B.CR_ACPTNO=ACPTNO
          AND B.CR_CNCLSTEP='SYSED';
        EXCEPTION
           WHEN  NO_DATA_FOUND  Then
              VCNT := 9;
   END;
   IF VCNT < 9 THEN
       IF VCNT = 0 THEN
          IF REQCD = '03' THEN
             RETSVRCD := '13';
          ELSE
             RETSVRCD := '03';
          END IF;
       ELSE
          IF GBNCD = 'F' OR (GBNCD = 'S' OR VCNT > 0) THEN
            IF REQCD = '03' THEN
               RETSVRCD := '15';
            ELSE
               RETSVRCD := '05';
            END IF;
          ELSE
            RETSVRCD := '00';
          END IF;
       END IF;
   END IF;
   IF RETSVRCD IS NOT NULL THEN
      RETURN RETSVRCD;
   END IF;
   BEGIN
       SELECT B.CR_SYSSTEP
         INTO VCNT
         FROM CMR1000 B
        WHERE B.CR_ACPTNO=ACPTNO
          AND B.CR_CNCLSTEP='SYSCB';
        EXCEPTION
           WHEN  NO_DATA_FOUND  Then
              VCNT := 9;
   END;
   IF VCNT < 9 THEN
       IF VCNT = 0 THEN
          RETURN '00';
       ELSE
          IF GBNCD = 'F' OR (GBNCD = 'S' OR VCNT > 0) THEN
            IF REQCD = '03' THEN
               RETSVRCD := '13';
            ELSE
               RETSVRCD := '03';
            END IF;
            RETURN RETSVRCD;
          ELSE
            RETURN '00';
          END IF;
       END IF;
   END IF;

   VCNT := 0;
   SELECT COUNT(*)
     INTO VCNT
     FROM CMR1000 B,CMR9900 A
    WHERE B.CR_ACPTNO=ACPTNO
      AND B.CR_ACPTNO=A.CR_ACPTNO
      AND A.CR_LOCAT<>'00'
      AND A.CR_TEAM='SYSCB'
      AND A.CR_STATUS='9';

   IF VCNT > 0 THEN
      IF REQCD = '03' THEN
         RETSVRCD := '13';
      ELSE
         RETSVRCD := '03';
      END IF;
      RETURN RETSVRCD;
   ELSE
      RETURN '00';
   END IF;
end;