-- GENERATED BY QueryOne AT 2021-03-04 14:17:51
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.AUTOSEQ_QRY  
(QRYCD IN VARCHAR2,INCNT IN INTEGER)     
RETURN VARCHAR2     
IS     
    ACPTNO VARCHAR2(12);  
    OUTACPT VARCHAR2(1000);        
    CNT INT := 0;        
-- 사용안함 (2018/08/21)
BEGIN    
    CNT := 0;  
    LOOP  
        CNT := CNT + 1;  
        IF QRYCD = '01' THEN   
            SELECT TO_CHAR(SYSDATE, 'YYYY') || QRYCD || LPAD(REQID_01_SEQ.NEXTVAL,6,'0')  
                INTO ACPTNO  
                FROM DUAL;  
        ELSIF QRYCD = '02' THEN  
            SELECT TO_CHAR(SYSDATE, 'YYYY') || QRYCD || LPAD(REQID_02_SEQ.NEXTVAL,6,'0')  
                INTO ACPTNO  
                FROM DUAL;  
        ELSIF QRYCD = '03' THEN  
            SELECT TO_CHAR(SYSDATE, 'YYYY') || QRYCD || LPAD(REQID_03_SEQ.NEXTVAL,6,'0')  
                INTO ACPTNO  
                FROM DUAL;  
        ELSIF QRYCD = '04' THEN  
            SELECT TO_CHAR(SYSDATE, 'YYYY') || QRYCD || LPAD(REQID_04_SEQ.NEXTVAL,6,'0')  
                INTO ACPTNO  
                FROM DUAL;  
        ELSIF QRYCD = '05' THEN  
            SELECT TO_CHAR(SYSDATE, 'YYYY') || QRYCD || LPAD(REQID_05_SEQ.NEXTVAL,6,'0')  
                INTO ACPTNO  
                FROM DUAL;  
        ELSIF QRYCD = '07' THEN  
            SELECT TO_CHAR(SYSDATE, 'YYYY') || QRYCD || LPAD(REQID_07_SEQ.NEXTVAL,6,'0')  
                INTO ACPTNO  
                FROM DUAL;  
        ELSIF QRYCD = '11' THEN  
            SELECT TO_CHAR(SYSDATE, 'YYYY') || QRYCD || LPAD(REQID_11_SEQ.NEXTVAL,6,'0')  
                INTO ACPTNO  
                FROM DUAL;  
        ELSIF QRYCD = '12' THEN  
            SELECT TO_CHAR(SYSDATE, 'YYYY') || QRYCD || LPAD(REQID_12_SEQ.NEXTVAL,6,'0')  
                INTO ACPTNO  
                FROM DUAL;  
        ELSIF QRYCD = '16' THEN  
            SELECT TO_CHAR(SYSDATE, 'YYYY') || QRYCD || LPAD(REQID_16_SEQ.NEXTVAL,6,'0')  
                INTO ACPTNO  
                FROM DUAL;  
         END IF;  
         IF LENGTH(OUTACPT) > 0 THEN OUTACPT := OUTACPT || ':';  
         END IF;  
         OUTACPT := OUTACPT || ACPTNO;  
         EXIT WHEN CNT >= INCNT;  
    END LOOP;  
      
    return OUTACPT;  
      
end;