-- GENERATED BY QueryOne AT 2021-03-04 14:17:56
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.NEXTCONF     
(ACPTNO IN VARCHAR2)              
RETURN VARCHAR2              
IS              
   VCNT   INTEGER;        
   VRETSTEP VARCHAR2(10);      
 --- 다음단계에서 처리해야 할 자동처리 찾기      
BEGIN         
    IF SUBSTR(ACPTNO,5,2) = '04' OR SUBSTR(ACPTNO,5,2) = '08' OR SUBSTR(ACPTNO,5,2) = '07' THEN   
       
        SELECT COUNT(*)      
          INTO VCNT      
          FROM CMR9900      
         WHERE CR_ACPTNO=ACPTNO      
           AND CR_LOCAT<>'00'      
           AND CR_STATUS='0'      
           AND CR_TEAMCD='1';      
              
        IF VCNT = 0 THEN      
           --VRETSTEP := 'NO';      
            SELECT COUNT(*)      
              INTO VCNT      
              FROM CMR9900      
             WHERE CR_ACPTNO=ACPTNO        
               AND CR_LOCAT<>'00'      
               AND CR_STATUS='0'  
               AND CR_CONGBN <> '4' 
               AND CR_TEAMCD <> '1';     
                 
            IF VCNT = 1 THEN      
                VRETSTEP := 'SYSED';     
            ELSE    
                SELECT COUNT(*)       
                  INTO VCNT      
                  FROM CMR9900      
                 WHERE CR_ACPTNO=ACPTNO        
                   AND CR_LOCAT<>'00'      
                   AND CR_STATUS='0'     
                   AND CR_TEAMCD <> '1'    
                   AND CR_TEAM = 'DBA'    
                   AND CR_ACPTNO IN (SELECT CR_ACPTNO     
                                       FROM CMR9900     
                                      WHERE CR_LOCAT='00'     
                                        AND CR_STATUS='0'     
                                         AND CR_TEAM='DBA');    
                IF VCNT = 2 THEN      
                    VRETSTEP := 'SYSTED';    
                ELSIF VCNT = 1 THEN     
                    VRETSTEP := 'SYSED';    
                END IF;    
            END IF;     
        ELSE      
            SELECT  A.CR_TEAM      
              INTO  VRETSTEP      
              FROM CMR9900 A,      
                   (SELECT MIN(CR_LOCAT) LOCAT      
                      FROM  CMR9900         
                     WHERE  CR_ACPTNO=ACPTNO        
                       AND  CR_LOCAT<>'00'      
                       AND  CR_STATUS='0'      
                       AND  CR_TEAMCD='1') B      
             WHERE CR_ACPTNO=ACPTNO      
               AND CR_LOCAT=B.LOCAT;        
         END IF;   
     ELSE   
        VRETSTEP := 'NO';   
     END IF;   
     RETURN VRETSTEP;      
end;