-- GENERATED BY QueryOne AT 2021-03-04 14:17:52
-- USING SYSTEM@172.31.120.104:1531(OSGGDB2)

CREATE OR REPLACE FUNCTION ECAMS.CHGHOMEPATH
  (SYSCD  IN VARCHAR2,
   RSRCCD IN VARCHAR2,
   JOBCD  IN VARCHAR2,
   DIRPATH IN VARCHAR2)
RETURN VARCHAR2
IS
  CHGPATH  VARCHAR2(200);
  CVSPRJM  VARCHAR2(50);
  CVSPRJS  VARCHAR2(50);
  CVSPRJ   VARCHAR2(50);

BEGIN
    CHGPATH := NULL;
    
    IF INSTR(DIRPATH,'?#') = 0 THEN
       RETURN DIRPATH;
    END IF;
    
    IF INSTR(DIRPATH,'?#CVSPRJ#') > 0 THEN 
        CVSPRJM := NULL;
        CVSPRJS := NULL;
        CVSPRJ  := NULL;
        
        BEGIN
            SELECT LOWER(A.CM_CVSPRJ),LOWER(B.CM_BASEDIR)
              INTO CVSPRJM, CVSPRJS
              FROM CMM0034 A,CMM0036 B
             WHERE A.CM_SYSCD=SYSCD
               AND A.CM_JOBCD=JOBCD
               AND A.CM_SYSCD=B.CM_SYSCD
               AND B.CM_RSRCCD=RSRCCD;
               
            EXCEPTION                              
                WHEN  NO_DATA_FOUND  Then                     
                RETURN DIRPATH;
        END;
        
        IF CVSPRJM = NULL OR CVSPRJM = '' THEN
           RETURN DIRPATH;
        ELSIF CVSPRJS = NULL OR CVSPRJS = '' THEN
           RETURN DIRPATH;
        END IF;
        CVSPRJ := CVSPRJM || '/' || CVSPRJM || CVSPRJS;
        CHGPATH := REPLACE(DIRPATH,'?#CVSPRJ#',CVSPRJ);
        
        RETURN CHGPATH;
    ELSIF INSTR(DIRPATH,'?#JOBETC#') > 0 THEN
        CVSPRJM := NULL;
        
        BEGIN
            SELECT LOWER(A.CM_CVSPRJ)
              INTO CVSPRJM
              FROM CMM0034 A
             WHERE A.CM_SYSCD=SYSCD
               AND A.CM_JOBCD=JOBCD;
             
            EXCEPTION                              
                WHEN  NO_DATA_FOUND  Then                     
                RETURN DIRPATH;
        END;
        
        IF CVSPRJM = NULL THEN
           RETURN DIRPATH;
        END IF;
        CHGPATH := REPLACE(DIRPATH,'?#JOBETC#',CVSPRJM);
        
        RETURN CHGPATH;
    ELSE
       RETURN DIRPATH;
    END IF;
    
END;