package app.ecams.user.dao;

import java.util.HashMap;
import java.util.List;

import app.ecams.user.model.UserInfo;


public interface IUserInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ECAMS.CMM0040
     *
     * @ibatorgenerated Wed Apr 28 09:45:29 KST 2010
     */
    UserInfo getUserInfo(String cmUserid) ;
    List getUserList(String cmUserid);
    int	chkUserId(String cmUserid) ;
    String	getUsername(String cmUserid) ;
    public String getMasterPasswd();
    public int setPasswd(HashMap param);
    
    public int getPwdnum();
	public int cntCmm0041(String userId);	
	public int updtPassWd_Cmm0041(HashMap param);	
	public int insertPassWd_Cmm0041(HashMap param);	
}