package app.ecams.user.dao;

import java.util.HashMap;
import java.util.List;

import app.ecams.user.model.UserInfo;




import org.apache.ibatis.session.SqlSession;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

@Repository
public class UserInfoDAO implements IUserInfoDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ECAMS.CMM0040
     *
     * @ibatorgenerated Wed Apr 28 09:45:29 KST 2010
     */
	
	@Autowired private SqlSession sqlSession;

   
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ECAMS.CMM0040
     *
     * @ibatorgenerated Wed Apr 28 09:45:29 KST 2010
     */
    public UserInfo getUserInfo(String cmUserid){
        try{
        	return (UserInfo) sqlSession.selectOne ("userinfo.getUserInfo", cmUserid);
    	}catch (Exception exception) {
    		return null;
    	}
    }
    
    public List getUserList(String cmUserid){
    	try{
    		return sqlSession.selectList("userinfo.getUserList", cmUserid);
    	}catch (Exception exception){
    		return null;
    	}
    }
    
    public int chkUserId(String cmUserid){
    	try{
    		return ((Integer)sqlSession.selectOne("userinfo.chkUserId", cmUserid)).intValue();
    	}catch (Exception exception) {
    		return -1;
    	}
    }
  
    public String getMasterPasswd(){
    	return (String) sqlSession.selectOne("userinfo.getMasterPasswd");
    }

    public String getUsername(String cmUserid){
    	try{
    		return (String) sqlSession.selectOne("userinfo.getUsername", cmUserid);
    	}catch (Exception exception) {
    		return null;
    	}
    }
    
    public int setPasswd(HashMap param){
    	try{
			return sqlSession.update("userinfo.setPasswd",param);
		}catch (Exception exception) {
			return -1;
		}
    }
    

    public int getPwdnum(){
		return ((Integer)sqlSession.selectOne("userinfo.getPwdnum")).intValue();
    }
	public int cntCmm0041(String userId){
		return ((Integer)sqlSession.selectOne("userinfo.cntCmm0041",userId)).intValue();
    }
	public int updtPassWd_Cmm0041(HashMap param){
    	try{
			return sqlSession.update("userinfo.updtPassWd_Cmm0041",param);
		}catch (Exception exception) {
			return -1;
		}
    }	
	public int insertPassWd_Cmm0041(HashMap param){
    	try{
			return sqlSession.insert("userinfo.insertPassWd_Cmm0041",param);
		}catch (Exception exception) {
			return -1;
		}
    }
}